<?php
/** R34/R60: keep Video Wall rendering aligned with public-safe DTOs and never present DB failure as an empty catalogue. */
defined('ABSPATH') || exit;
final class VWLB_R34_Frontend_Contract {
	public static function register(){remove_shortcode('vwlb_wall');add_shortcode('vwlb_wall',array(__CLASS__,'wall'));}
	private static function nav(){return '<nav class="vwlb-local-nav" aria-label="'.esc_attr__('Page navigation',VWLB_TEXT_DOMAIN).'"><button type="button" data-vwlb-back>'.esc_html__('Back',VWLB_TEXT_DOMAIN).'</button><a href="'.esc_url(home_url('/')).'">'.esc_html__('Home',VWLB_TEXT_DOMAIN).'</a></nav>';}
	private static function degraded(){return '<main class="vwlb-shell">'.self::nav().'<section class="vwlb-empty" role="alert"><h1>'.esc_html__('Video service temporarily unavailable',VWLB_TEXT_DOMAIN).'</h1><p>'.esc_html__('The video catalogue could not be read safely. Please retry after the service recovers.',VWLB_TEXT_DOMAIN).'</p></section></main>';}
	public static function wall(){
		wp_enqueue_style('vwlb');wp_enqueue_script('vwlb');$data=VWLB_Repository::browse_videos(array('per_page'=>12));
		if(!is_array($data)||!empty($data['error_code']))return self::degraded();
		global $wpdb;$wpdb->last_error='';$lives=$wpdb->get_results("SELECT public_id,title,scheduled_start,status FROM ".VWLB_Helpers::table('live_events')." WHERE visibility='public' AND status IN ('scheduled','live') AND deleted_at IS NULL ORDER BY scheduled_start ASC LIMIT 8",ARRAY_A);
		if(''!==(string)$wpdb->last_error){do_action('vwlb_operational_failure','frontend','vwlb_video_wall_live_read_failed',array());return self::degraded();}
		$lives=is_array($lives)?$lives:array();
		ob_start();?><main class="vwlb-shell" aria-labelledby="vwlb-wall-title"><?php echo self::nav();?><header class="vwlb-hero"><h1 id="vwlb-wall-title"><?php esc_html_e('Video Wall',VWLB_TEXT_DOMAIN);?></h1><p><?php esc_html_e('Verified educational videos, podcasts and live broadcasts.',VWLB_TEXT_DOMAIN);?></p></header>
		<?php if($lives):?><section aria-labelledby="vwlb-live-now"><h2 id="vwlb-live-now"><?php esc_html_e('Live and upcoming',VWLB_TEXT_DOMAIN);?></h2><div class="vwlb-grid" role="list"><?php foreach($lives as $l):?><article class="vwlb-card" role="listitem"><a href="<?php echo esc_url(home_url('/live/'.$l['public_id'].'/'));?>"><h3><?php echo esc_html($l['title']);?></h3><span class="vwlb-meta"><?php echo esc_html('live'===$l['status']?__('Live now',VWLB_TEXT_DOMAIN):get_date_from_gmt($l['scheduled_start'],get_option('date_format').' '.get_option('time_format')));?></span></a></article><?php endforeach;?></div></section><?php endif;?>
		<section aria-labelledby="vwlb-recorded"><h2 id="vwlb-recorded"><?php esc_html_e('Recorded videos',VWLB_TEXT_DOMAIN);?></h2><div class="vwlb-grid" role="list"><?php if(empty($data['items'])):?><section class="vwlb-empty" role="status"><h3><?php esc_html_e('No public videos yet',VWLB_TEXT_DOMAIN);?></h3><p><?php esc_html_e('Approved videos will appear here after review.',VWLB_TEXT_DOMAIN);?></p></section><?php else:foreach($data['items'] as $item):?><article class="vwlb-card" role="listitem"><a href="<?php echo esc_url($item['url']);?>"><div class="vwlb-thumb"><?php if(!empty($item['thumbnail_url'])):?><img src="<?php echo esc_url($item['thumbnail_url']);?>" alt="" loading="lazy" decoding="async"><?php else:?><span aria-hidden="true">▶</span><?php endif;?></div><h3><?php echo esc_html($item['title']);?></h3><p><?php echo esc_html($item['excerpt']);?></p><span class="vwlb-meta"><?php echo esc_html(gmdate('H:i:s',(int)$item['duration_seconds']));?></span></a></article><?php endforeach;endif;?></div></section></main><?php return ob_get_clean();
	}
}
