<?php
/** Private operational dashboard; native domain ownership remains File 10. */
defined( 'ABSPATH' ) || exit;
final class VWLB_Admin {
	public function register(){add_menu_page(__('Video & Live',VWLB_TEXT_DOMAIN),__('Video & Live',VWLB_TEXT_DOMAIN),VWLB_Contracts::CAP_MANAGE,'vwlb',array($this,'dashboard'),'dashicons-video-alt3',26);add_submenu_page('vwlb',__('Processing Queue',VWLB_TEXT_DOMAIN),__('Processing Queue',VWLB_TEXT_DOMAIN),VWLB_Contracts::CAP_MANAGE,'vwlb-jobs',array($this,'jobs'));add_submenu_page('vwlb',__('Moderation',VWLB_TEXT_DOMAIN),__('Moderation',VWLB_TEXT_DOMAIN),VWLB_Contracts::CAP_MODERATE,'vwlb-moderation',array($this,'moderation'));add_submenu_page('vwlb',__('Diagnostics',VWLB_TEXT_DOMAIN),__('Diagnostics',VWLB_TEXT_DOMAIN),VWLB_Contracts::CAP_DIAGNOSTICS,'vwlb-diagnostics',array($this,'diagnostics'));}
	public function enqueue($hook){if(false===strpos($hook,'vwlb'))return;wp_enqueue_style('vwlb-admin',VWLB_URL.'assets/css/admin.css',array(),VWLB_VERSION);}
	public function dashboard(){if(!current_user_can(VWLB_Contracts::CAP_MANAGE))wp_die(esc_html__('Access denied.',VWLB_TEXT_DOMAIN));global $wpdb;$counts=array();foreach(array('videos','live_events','media_assets','channels','playlists','moderation','takedowns') as $entity){$counts[$entity]=(int)$wpdb->get_var('SELECT COUNT(*) FROM '.VWLB_Helpers::table($entity));}?><div class="wrap vwlb-admin"><h1><?php esc_html_e('Video Wall and Live Broadcasting',VWLB_TEXT_DOMAIN);?></h1><p><?php esc_html_e('File 10 canonical command center for recorded and live media.',VWLB_TEXT_DOMAIN);?></p><div class="vwlb-admin-grid"><?php foreach($counts as $key=>$count):?><section class="vwlb-admin-card"><h2><?php echo esc_html(ucwords(str_replace('_',' ',$key)));?></h2><strong><?php echo esc_html(number_format_i18n($count));?></strong></section><?php endforeach;?></div><h2><?php esc_html_e('Operational gates',VWLB_TEXT_DOMAIN);?></h2><ul><li><?php esc_html_e('Safe mode:',VWLB_TEXT_DOMAIN);?> <strong><?php echo get_option('vwlb_safe_mode')?esc_html__('Enabled',VWLB_TEXT_DOMAIN):esc_html__('Normal',VWLB_TEXT_DOMAIN);?></strong></li><li><?php esc_html_e('Schema:',VWLB_TEXT_DOMAIN);?> <code><?php echo esc_html(get_option('vwlb_schema_version','missing'));?></code></li><li><?php esc_html_e('Provider adapters:',VWLB_TEXT_DOMAIN);?> <?php echo esc_html(implode(', ',array_keys(VWLB_Providers::all())));?></li></ul></div><?php }
	public function jobs(){global $wpdb;$rows=$wpdb->get_results('SELECT * FROM '.VWLB_Helpers::table('processing_jobs').' ORDER BY id DESC LIMIT 100',ARRAY_A);?><div class="wrap vwlb-admin"><h1><?php esc_html_e('Processing Queue',VWLB_TEXT_DOMAIN);?></h1><?php $this->table($rows,array('id','job_type','provider','status','attempts','available_at','error_code'));?></div><?php }
	public function moderation(){global $wpdb;$rows=$wpdb->get_results('SELECT * FROM '.VWLB_Helpers::table('moderation').' ORDER BY id DESC LIMIT 100',ARRAY_A);?><div class="wrap vwlb-admin"><h1><?php esc_html_e('Moderation Queue',VWLB_TEXT_DOMAIN);?></h1><?php $this->table($rows,array('id','target_type','target_id','reason','severity','status','created_at'));?></div><?php }
	public function diagnostics(){$report=VWLB_Diagnostics::full();?><div class="wrap vwlb-admin"><h1><?php esc_html_e('System Check',VWLB_TEXT_DOMAIN);?></h1><pre><?php echo esc_html(wp_json_encode($report,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));?></pre></div><?php }
	private function table($rows,$columns){if(!$rows){echo '<p>'.esc_html__('No records.',VWLB_TEXT_DOMAIN).'</p>';return;}echo '<table class="widefat striped"><thead><tr>';foreach($columns as $c)echo '<th>'.esc_html(ucwords(str_replace('_',' ',$c))).'</th>';echo '</tr></thead><tbody>';foreach($rows as $row){echo '<tr>';foreach($columns as $c)echo '<td>'.esc_html((string)($row[$c]??'')).'</td>';echo '</tr>';}echo '</tbody></table>';}
}
