<?php
/** Fourth-cycle review hardening: public-ID boundaries, retry/reconciliation and privacy-safe fallbacks. */
defined( 'ABSPATH' ) || exit;
final class VWLB_Review_Hardening {
	const INBOX_RETRY_PREFIX = 'vwlb_inbox_retry_';
	const AUDIT_FALLBACK_PREFIX = 'vwlb_audit_fallback_';
	const OUTBOX_FALLBACK_PREFIX = 'vwlb_outbox_fallback_';

	public static function register() {
		add_filter( 'rest_pre_dispatch', array( __CLASS__, 'reject_numeric_route_ids' ), 1, 3 );
		add_action( 'rest_api_init', array( __CLASS__, 'register_rest_overrides' ), 30 );
		add_filter( 'wp_privacy_personal_data_erasers', array( __CLASS__, 'erasers' ), 30 );
		add_action( 'init', array( __CLASS__, 'override_podcast_shortcode' ), 100 );
		add_action( 'vwlb_cleanup', array( __CLASS__, 'cleanup_hardening' ), 50 );
		add_action( 'vwlb_reconcile_states', array( __CLASS__, 'reconcile_fallbacks' ), 60 );
		add_action( 'vwlb_reconcile_states', array( __CLASS__, 'reconcile_inbox_retries' ), 70 );
		add_action( 'sabri_event_bus_consume_file10', array( __CLASS__, 'capture_inbox_retry' ), 1, 3 );
		add_action( 'sabri_event_bus_consume_file10', array( __CLASS__, 'release_processed_inbox_retry' ), 100, 3 );
	}

	private static function is_file10_route( $route ) {
		foreach ( VWLB_Contracts::namespaces() as $namespace ) {
			if ( str_starts_with( (string) $route, '/' . $namespace . '/' ) ) return true;
		}
		return false;
	}
	public static function reject_numeric_route_ids( $result, $server, $request ) {
		if ( null !== $result || ! ( $request instanceof WP_REST_Request ) || ! self::is_file10_route( $request->get_route() ) ) return $result;
		foreach ( array( 'id', 'scene', 'target' ) as $field ) {
			$value = (string) $request->get_param( $field );
			if ( '' !== $value && ctype_digit( $value ) ) return VWLB_Helpers::error( 'vwlb_public_identifier_required', __( 'An opaque public identifier is required.', VWLB_TEXT_DOMAIN ), 404 );
		}
		return $result;
	}
	private static function response( $value, $status = 200 ) {
		if ( is_wp_error( $value ) ) return $value;
		$response = rest_ensure_response( $value );
		$response->set_status( $status );
		$response->header( 'X-Sabri-File', '10' );
		$response->header( 'X-VWLB-Version', VWLB_VERSION );
		$response->header( 'X-VWLB-Canonical-API', VWLB_Contracts::CANONICAL_API_NAMESPACE );
		return $response;
	}
	private static function body( WP_REST_Request $request ) { $data = $request->get_json_params(); return is_array( $data ) ? $data : array(); }
	private static function idem( WP_REST_Request $request ) { return VWLB_Helpers::text( $request->get_header( 'Idempotency-Key' ), 128 ); }
	private static function internal_id_error( $field ) { return VWLB_Helpers::error( 'vwlb_internal_identifier_forbidden', sprintf( __( 'Internal identifier field %s is not accepted on the public API.', VWLB_TEXT_DOMAIN ), $field ), 422 ); }
	private static function row_by_public( $table, $public_id ) {
		$allowed = array( 'channels','playlists','media_assets','videos','captions','live_events','podcast_series','podcast_episodes','takedowns' );
		if ( ! in_array( $table, $allowed, true ) ) return null;
		global $wpdb; $t = VWLB_Helpers::table( $table );
		return $wpdb->get_row( $wpdb->prepare( "SELECT * FROM $t WHERE public_id=%s LIMIT 1", VWLB_Helpers::text( $public_id, 80 ) ), ARRAY_A );
	}
	private static function id_from_public( $table, $public_id ) { $row = self::row_by_public( $table, $public_id ); return $row ? (int) $row['id'] : 0; }
	private static function map_public_id( $data, $public_field, $internal_field, $table, $required = false ) {
		if ( array_key_exists( $internal_field, $data ) ) return self::internal_id_error( $internal_field );
		$public = VWLB_Helpers::text( $data[ $public_field ] ?? '', 80 );
		if ( ! $public ) {
			if ( $required ) return VWLB_Helpers::error( 'vwlb_public_identifier_required', sprintf( __( '%s is required.', VWLB_TEXT_DOMAIN ), $public_field ), 422 );
			$data[ $internal_field ] = 0; return $data;
		}
		$id = self::id_from_public( $table, $public );
		if ( ! $id ) return VWLB_Helpers::error( 'vwlb_not_found', __( 'The referenced object was not found.', VWLB_TEXT_DOMAIN ), 404 );
		$data[ $internal_field ] = $id; unset( $data[ $public_field ] ); return $data;
	}
	private static function sanitize_mutation_dto( $row, $fields ) { if ( is_wp_error( $row ) || ! is_array( $row ) ) return $row; $out=array(); foreach($fields as $field) if(array_key_exists($field,$row))$out[$field]=$row[$field]; return $out; }

	public static function register_rest_overrides() {
		foreach ( VWLB_Contracts::namespaces() as $n ) {
			register_rest_route($n,'/videos',array(
				array('methods'=>'GET','callback'=>array(__CLASS__,'browse_videos'),'permission_callback'=>'__return_true'),
				array('methods'=>'POST','callback'=>array(__CLASS__,'create_video'),'permission_callback'=>function(){return VWLB_Security::can(VWLB_Contracts::CAP_SUBMIT);}),
			),true);
			register_rest_route($n,'/videos/(?P<id>[A-Za-z0-9_-]+)/captions',array('methods'=>'POST','callback'=>array(__CLASS__,'add_caption'),'permission_callback'=>function(){return VWLB_Security::can(VWLB_Contracts::CAP_SUBMIT);}),true);
			register_rest_route($n,'/videos/(?P<id>[A-Za-z0-9_-]+)/playback',array('methods'=>'GET','callback'=>array(__CLASS__,'playback'),'permission_callback'=>'__return_true'),true);
			register_rest_route($n,'/playlists',array('methods'=>'POST','callback'=>array(__CLASS__,'create_playlist'),'permission_callback'=>function(){return VWLB_Security::can(VWLB_Contracts::CAP_PUBLISH);}),true);
			register_rest_route($n,'/playlists/(?P<id>[A-Za-z0-9_-]+)/items',array('methods'=>'PUT','callback'=>array(__CLASS__,'playlist_items'),'permission_callback'=>function(){return VWLB_Security::can(VWLB_Contracts::CAP_PUBLISH);}),true);
			register_rest_route($n,'/media/initiate',array('methods'=>'POST','callback'=>array(__CLASS__,'initiate_media'),'permission_callback'=>function(){return VWLB_Security::can(VWLB_Contracts::CAP_SUBMIT);}),true);
			register_rest_route($n,'/live-events',array(
				array('methods'=>'GET','callback'=>array(__CLASS__,'browse_live'),'permission_callback'=>'__return_true'),
				array('methods'=>'POST','callback'=>array(__CLASS__,'schedule_live'),'permission_callback'=>function(){return VWLB_Security::can(VWLB_Contracts::CAP_BROADCAST);}),
			),true);
			register_rest_route($n,'/live-events/(?P<id>[A-Za-z0-9_-]+)/credentials',array('methods'=>'POST','callback'=>array(__CLASS__,'issue_credential'),'permission_callback'=>function(){return VWLB_Security::can(VWLB_Contracts::CAP_BROADCAST);}),true);
			register_rest_route($n,'/live-events/(?P<id>[A-Za-z0-9_-]+)/replay',array('methods'=>'POST','callback'=>array(__CLASS__,'publish_replay'),'permission_callback'=>function(){return VWLB_Security::can(VWLB_Contracts::CAP_PUBLISH);}),true);
			register_rest_route($n,'/premieres',array('methods'=>'POST','callback'=>array(__CLASS__,'premiere_create'),'permission_callback'=>function(){return VWLB_Security::can(VWLB_Contracts::CAP_PUBLISH);}),true);
			register_rest_route($n,'/downloads',array('methods'=>'POST','callback'=>array(__CLASS__,'download_token'),'permission_callback'=>function(){return is_user_logged_in();}),true);
			register_rest_route($n,'/creator/studio',array('methods'=>'GET','callback'=>array(__CLASS__,'creator_studio'),'permission_callback'=>function(){return VWLB_Security::can(VWLB_Contracts::CAP_SUBMIT);}),true);
			register_rest_route($n,'/podcasts/series',array('methods'=>'POST','callback'=>array(__CLASS__,'podcast_series_create'),'permission_callback'=>function(){return VWLB_Security::can(VWLB_Contracts::CAP_PUBLISH);}),true);
			register_rest_route($n,'/podcasts/episodes',array('methods'=>'POST','callback'=>array(__CLASS__,'podcast_episode_create'),'permission_callback'=>function(){return VWLB_Security::can(VWLB_Contracts::CAP_SUBMIT);}),true);
			register_rest_route($n,'/podcasts/episodes/(?P<id>[A-Za-z0-9_-]+)',array('methods'=>'GET','callback'=>array(__CLASS__,'podcast_episode'),'permission_callback'=>'__return_true'),true);
			register_rest_route($n,'/podcasts/episodes/(?P<id>[A-Za-z0-9_-]+)/publish',array('methods'=>'POST','callback'=>array(__CLASS__,'podcast_publish'),'permission_callback'=>function(){return VWLB_Security::can(VWLB_Contracts::CAP_PUBLISH);}),true);
		}
	}

	public static function browse_videos( WP_REST_Request $r ) {
		if ( null !== $r->get_param('channel_id') ) return self::internal_id_error('channel_id');
		$channel_id=0;$public=VWLB_Helpers::text($r->get_param('channel_public_id')??'',80);if($public){$channel_id=self::id_from_public('channels',$public);if(!$channel_id)return VWLB_Helpers::error('vwlb_not_found',__('Channel not found.',VWLB_TEXT_DOMAIN),404);}
		return self::response(VWLB_Repository::browse_videos(array('per_page'=>$r['per_page'],'cursor'=>$r['cursor'],'channel_id'=>$channel_id,'language'=>$r['language'])));
	}
	public static function create_video( WP_REST_Request $r ) {
		$d=self::body($r);foreach(array(array('asset_public_id','asset_id','media_assets'),array('channel_public_id','channel_id','channels')) as $m){$d=self::map_public_id($d,$m[0],$m[1],$m[2],false);if(is_wp_error($d))return $d;}
		if(array_key_exists('thumbnail_id',$d))return self::internal_id_error('thumbnail_id');
		if(!empty($d['thumbnail_attachment_id'])){$attachment=absint($d['thumbnail_attachment_id']);if(!$attachment||!current_user_can('read_post',$attachment)||!apply_filters('vwlb_thumbnail_attachment_allowed',false,$attachment,get_current_user_id()))return VWLB_Helpers::error('vwlb_thumbnail_attachment_forbidden',__('The thumbnail attachment is unavailable or not approved for File 10 use.',VWLB_TEXT_DOMAIN),404);$d['thumbnail_id']=$attachment;unset($d['thumbnail_attachment_id']);}
		$v=VWLB_Videos::create($d,self::idem($r));if(!is_wp_error($v)&&is_array($v))unset($v['id']);return self::response($v,201);
	}
	public static function add_caption( WP_REST_Request $r ) {
		$v=VWLB_Videos::add_caption($r['id'],self::body($r));if(is_wp_error($v))return $v;$public='';if(!empty($v['id'])){global $wpdb;$public=(string)$wpdb->get_var($wpdb->prepare('SELECT public_id FROM '.VWLB_Helpers::table('captions').' WHERE id=%d',(int)$v['id']));}return self::response(array('public_id'=>$public,'status'=>$v['status']??'review','version'=>(int)($v['version']??0)),201);
	}
	public static function playback( WP_REST_Request $r ) {
		$video=VWLB_Repository::find('videos',$r['id']);$payload=VWLB_Videos::playback($r['id']);if(!is_wp_error($payload)&&is_array($payload)&&$video){$payload['chapters']=VWLB_Extensions::chapters('video',$video['id']);$payload['media_tracks']=VWLB_Future_Safety::published_tracks('video',$video['id']);$payload['preferences']=array('autoplay'=>false,'low_bandwidth'=>(bool)($r['low_bandwidth']??false),'reduced_motion'=>false);} $response=self::response($payload);if(!is_wp_error($response))$response->header('Cache-Control','private, no-store');return $response;
	}
	public static function create_playlist( WP_REST_Request $r ) {$d=self::map_public_id(self::body($r),'channel_public_id','channel_id','channels',false);if(is_wp_error($d))return $d;$v=VWLB_Videos::create_playlist($d);return self::response(is_wp_error($v)?$v:VWLB_Repository::playlist_mutation_dto($v),201);}
	public static function playlist_items( WP_REST_Request $r ) {$d=self::body($r);if(array_key_exists('video_ids',$d))return self::internal_id_error('video_ids');$ids=array();foreach((array)($d['video_public_ids']??array()) as $public){$id=self::id_from_public('videos',$public);if(!$id)return VWLB_Helpers::error('vwlb_video_missing',__('A playlist video was not found.',VWLB_TEXT_DOMAIN),404);$ids[]=$id;}$v=VWLB_Videos::set_playlist_items($r['id'],$ids,absint($d['version']??0));return self::response(is_wp_error($v)?$v:VWLB_Repository::playlist_mutation_dto($v));}
	public static function initiate_media( WP_REST_Request $r ) {$d=self::body($r);if(array_key_exists('source_object_id',$d))return self::internal_id_error('source_object_id');$d['source_object_id']=0;$v=VWLB_Media::initiate($d);if(!is_wp_error($v)&&is_array($v))unset($v['id']);return self::response($v,201);}
	public static function browse_live( WP_REST_Request $r ) {global $wpdb;$limit=max(1,min(24,absint($r['per_page']?:12)));$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM ".VWLB_Helpers::table('live_events')." WHERE visibility='public' AND status IN ('scheduled','live','interrupted','ended','recording_processing','replay_review','replay_published') AND deleted_at IS NULL ORDER BY scheduled_start DESC,id DESC LIMIT %d",$limit),ARRAY_A);$items=array();foreach((array)$rows as $row){$dto=VWLB_Repository::public_live_dto($row);if($dto)$items[]=$dto;}return self::response(array('items'=>$items));}
	public static function schedule_live( WP_REST_Request $r ) {$d=self::map_public_id(self::body($r),'channel_public_id','channel_id','channels',false);if(is_wp_error($d))return $d;if(!array_key_exists('recording_policy',$d))$d['recording_policy']=array('record'=>false,'publish_replay'=>false,'consent_required'=>true);else{$d['recording_policy']=is_array($d['recording_policy'])?$d['recording_policy']:array();$d['recording_policy']['record']=!empty($d['recording_policy']['record']);$d['recording_policy']['consent_required']=array_key_exists('consent_required',$d['recording_policy'])?(bool)$d['recording_policy']['consent_required']:true;}$d['recording_policy']['consent_version']=VWLB_Helpers::text($d['recording_policy']['consent_version']??'v1',64);$preferred=VWLB_Helpers::enum($d['provider']??'custom',array_keys(VWLB_Providers::all()),'custom');$selection=VWLB_Providers::select($preferred,'live',!empty($d['allow_provider_failover']));if(is_wp_error($selection))return $selection;$d['provider']=$selection['provider'];$result=VWLB_Live::schedule($d,self::idem($r));if(!is_wp_error($result)&&!empty($result['id'])){$extras=VWLB_Extensions::schedule_live_extras($result['id'],$d);if(is_wp_error($extras))return $extras;$fresh=VWLB_Repository::find('live_events',$result['id']);$safe=$fresh?VWLB_Repository::live_mutation_dto($fresh):array('public_id'=>$result['public_id']??'','status'=>$result['status']??'scheduled','version'=>(int)($result['version']??1));if(!empty($selection['failover']))$safe['provider_failover']=$selection;$result=$safe;}return self::response($result,201);}
	public static function issue_credential( WP_REST_Request $r ) {$d=self::body($r);$v=VWLB_Live::issue_credential($r['id'],$d['ttl']??21600);if(!is_wp_error($v)&&is_array($v))unset($v['credential_id']);return self::response($v,201);}
	public static function publish_replay( WP_REST_Request $r ) {$d=self::body($r);if(array_key_exists('video_id',$d))return self::internal_id_error('video_id');$video_id=self::id_from_public('videos',$d['video_public_id']??'');if(!$video_id)return VWLB_Helpers::error('vwlb_missing',__('Replay video not found.',VWLB_TEXT_DOMAIN),404);$v=VWLB_Live::publish_replay($r['id'],$video_id,absint($d['version']??0));return self::response(is_wp_error($v)?$v:VWLB_Repository::live_mutation_dto($v));}
	public static function premiere_create( WP_REST_Request $r ) {$d=self::body($r);if(array_key_exists('video_id',$d))return self::internal_id_error('video_id');$id=self::id_from_public('videos',$d['video_public_id']??'');if(!$id)return VWLB_Helpers::error('vwlb_premiere_video_invalid',__('A valid public video reference is required.',VWLB_TEXT_DOMAIN),422);$d['video_id']=$id;unset($d['video_public_id']);return self::response(VWLB_Extensions::create_premiere($d,self::idem($r)),201);}
	public static function download_token( WP_REST_Request $r ) {$d=self::body($r);if(array_key_exists('object_id',$d))return self::internal_id_error('object_id');$type=VWLB_Helpers::enum($d['object_type']??'',array('video','podcast'),'');$table='video'===$type?'videos':('podcast'===$type?'podcast_episodes':'');$id=$table?self::id_from_public($table,$d['object_public_id']??''):0;if(!$id)return VWLB_Helpers::error('vwlb_not_found',__('Media not found.',VWLB_TEXT_DOMAIN),404);return self::response(VWLB_Extensions::create_download_token($type,$id,$d['ttl']??900,$d['max_downloads']??1),201);}

	public static function podcast_series_create( WP_REST_Request $r ) {$d=self::map_public_id(self::body($r),'channel_public_id','channel_id','channels',false);if(is_wp_error($d))return $d;if(!empty($d['channel_id'])){$channel=VWLB_Repository::find('channels',$d['channel_id']);if(!$channel||!VWLB_Security::can(VWLB_Contracts::CAP_PUBLISH,$channel,'create_podcast_series'))return VWLB_Helpers::error('vwlb_channel_forbidden',__('The channel is unavailable.',VWLB_TEXT_DOMAIN),404);}$v=VWLB_Podcasts::create_series($d);return self::response(self::sanitize_mutation_dto($v,array('public_id','slug','status','version')),201);}
	public static function podcast_episode_create( WP_REST_Request $r ) {$d=self::body($r);foreach(array('series_id','asset_id','transcript_caption_id') as $field)if(array_key_exists($field,$d))return self::internal_id_error($field);$series=self::row_by_public('podcast_series',$d['series_public_id']??'');$asset=self::row_by_public('media_assets',$d['asset_public_id']??'');if(!$series||!$asset||!empty($series['deleted_at'])||!empty($asset['deleted_at']))return VWLB_Helpers::error('vwlb_episode_fields_required',__('A valid podcast series and audio asset reference are required.',VWLB_TEXT_DOMAIN),422);if(!VWLB_Security::can(VWLB_Contracts::CAP_SUBMIT,$series,'create_podcast_episode')||!VWLB_Security::can(VWLB_Contracts::CAP_SUBMIT,$asset,'create_podcast_episode'))return VWLB_Helpers::error('vwlb_not_found',__('Podcast series or audio asset not found.',VWLB_TEXT_DOMAIN),404);$d['series_id']=(int)$series['id'];$d['asset_id']=(int)$asset['id'];unset($d['series_public_id'],$d['asset_public_id']);if(!empty($d['transcript_caption_public_id'])){$caption=self::row_by_public('captions',$d['transcript_caption_public_id']);if(!$caption||'published'!==($caption['status']??'')||!apply_filters('vwlb_podcast_transcript_caption_allowed',false,$caption,$series,$asset,get_current_user_id()))return VWLB_Helpers::error('vwlb_transcript_invalid',__('Transcript caption reference is unavailable or not approved for this podcast.',VWLB_TEXT_DOMAIN),422);$d['transcript_caption_id']=(int)$caption['id'];unset($d['transcript_caption_public_id']);}$v=VWLB_Podcasts::create_episode($d);return self::response(self::sanitize_mutation_dto($v,array('public_id','slug','status','version')),201);}
	public static function podcast_episode( WP_REST_Request $r ) {$dto=self::podcast_public_dto($r['id']);return $dto?self::response($dto):VWLB_Helpers::error('vwlb_not_found',__('Podcast episode not found.',VWLB_TEXT_DOMAIN),404);}
	public static function podcast_publish( WP_REST_Request $r ) {$d=self::body($r);$v=VWLB_Podcasts::publish_episode($r['id'],absint($d['version']??0));if(is_wp_error($v))return $v;return self::response(self::podcast_mutation_dto($v));}
	private static function podcast_mutation_dto($row){$series_public='';if(!empty($row['series_id'])){$series=self::row_by_id('podcast_series',$row['series_id']);$series_public=$series['public_id']??'';}return array('public_id'=>$row['public_id']??'','series_public_id'=>$series_public,'status'=>$row['status']??'','visibility'=>$row['visibility']??'','version'=>(int)($row['version']??0),'published_at'=>VWLB_Helpers::iso_utc($row['published_at']??null));}
	private static function row_by_id($table,$id){global $wpdb;$t=VWLB_Helpers::table($table);return $wpdb->get_row($wpdb->prepare("SELECT * FROM $t WHERE id=%d LIMIT 1",absint($id)),ARRAY_A);}
	public static function podcast_public_dto( $id ) {
		if(ctype_digit((string)$id))return null;$ep=self::row_by_public('podcast_episodes',$id);if(!$ep||!empty($ep['deleted_at'])||'published'!==($ep['status']??'')||!VWLB_Security::can_view($ep,'podcast_playback'))return null;$asset=VWLB_Repository::find('media_assets',$ep['asset_id']);if(!$asset||'ready'!==($asset['status']??'')||'passed'!==($asset['scan_status']??''))return null;$der=VWLB_Helpers::json($asset['derivatives_json']??'{}');$audio='';
		if(in_array($ep['visibility'],array('public','unlisted'),true))$audio=esc_url_raw($der['audio_only']??$der['mp3']??$der['mp4_low']??'');else{$grant=apply_filters('vwlb_secure_podcast_playback_grant','',$ep,$asset,VWLB_Security::claims());$audio=esc_url_raw(is_string($grant)?$grant:'');if(!$audio)return null;}
		$series=self::row_by_id('podcast_series',$ep['series_id']);return array('id'=>$ep['public_id'],'public_id'=>$ep['public_id'],'series_public_id'=>$series['public_id']??'','title'=>$ep['title'],'slug'=>$ep['slug'],'description'=>$ep['description'],'language'=>$ep['language'],'duration_seconds'=>(int)$ep['duration_seconds'],'rights_status'=>$ep['rights_status'],'visibility'=>$ep['visibility'],'published_at'=>VWLB_Helpers::iso_utc($ep['published_at']),'audio_url'=>$audio,'download_available'=>(bool)$ep['download_allowed'],'transcript'=>($ep['transcript_status']??'')==='published'?(string)($ep['transcript_text']??''):'','chapters'=>VWLB_Extensions::chapters('podcast',$ep['id']));
	}
	public static function override_podcast_shortcode(){remove_shortcode('vwlb_podcast');add_shortcode('vwlb_podcast',array(__CLASS__,'podcast_shortcode'));}
	public static function podcast_shortcode(){wp_enqueue_style('vwlb');wp_enqueue_script('vwlb');$id=get_query_var('vwlb_podcast_id');$ep=self::podcast_public_dto($id);if(!$ep){status_header(404);return '<section class="vwlb-state vwlb-state-restricted" role="status"><h2>'.esc_html__('Podcast unavailable',VWLB_TEXT_DOMAIN).'</h2><p>'.esc_html__('This episode is unavailable.',VWLB_TEXT_DOMAIN).'</p></section>';}$html='<main class="vwlb-shell" data-vwlb-podcast="'.esc_attr($ep['public_id']).'"><article><h1>'.esc_html($ep['title']).'</h1>';if($ep['audio_url'])$html.='<audio controls preload="metadata" src="'.esc_url($ep['audio_url']).'"></audio>';$html.='<div>'.wp_kses_post(wpautop($ep['description'])).'</div></article></main>';return $html;}

	public static function creator_studio(){
		$v=VWLB_Extensions::creator_studio();if(is_wp_error($v)||!is_array($v))return $v;if(isset($v['copyright'])&&is_array($v['copyright']))foreach($v['copyright'] as &$case){$target_public='';if(!empty($case['target_type'])&&!empty($case['target_id'])&&in_array($case['target_type'],array('video','live'),true)){$table='video'===$case['target_type']?'videos':'live_events';$target=self::row_by_id($table,$case['target_id']);$target_public=$target['public_id']??'';}unset($case['target_id']);$case['target_public_id']=$target_public;}return self::response($v);
	}

	public static function erasers($erasers){$erasers['vwlb']=array('eraser_friendly_name'=>__('Video Wall and Live Broadcasting',VWLB_TEXT_DOMAIN),'callback'=>array(__CLASS__,'erase'));return $erasers;}
	private static function delete_ids($table,$ids){if(!$ids)return true;global $wpdb;$ids=array_values(array_unique(array_map('absint',$ids)));$sql='DELETE FROM '.VWLB_Helpers::table($table).' WHERE id IN ('.implode(',',array_fill(0,count($ids),'%d')).')';return false!==$wpdb->query($wpdb->prepare($sql,$ids));}
	private static function anonymized_user_id($event_id,$row_public_id){global $wpdb;$table=VWLB_Helpers::table('live_attendees');for($i=0;$i<10;$i++){$candidate=random_int(4611686018427387904,9223372036854775000);$exists=$wpdb->get_var($wpdb->prepare("SELECT id FROM $table WHERE live_event_id=%d AND user_id=%d LIMIT 1",absint($event_id),$candidate));if(!$exists&&!get_userdata($candidate))return $candidate;}return 0;}
	private static function privacy_has_more($uid){global $wpdb;$checks=array(array('playback_sessions','user_id'),array('interactions','user_id'),array('download_tokens','user_id'),array('upload_sessions','owner_id'),array('live_poll_responses','user_id'),array('broadcast_guests','user_id'),array('live_attendees','user_id'),array('live_questions','user_id'),array('moderation','reporter_id'),array('audit','actor_id'),array('creator_metrics_daily','owner_id'),array('production_sources','owner_id'),array('production_scenes','owner_id'),array('simulcast_targets','created_by'),array('media_tracks','created_by'),array('media_tracks','reviewed_by'),array('video_annotations','created_by'),array('video_annotations','reviewed_by'),array('live_polls','created_by'),array('consent_links','created_by'),array('watermark_policies','updated_by'),array('broadcast_guests','invited_by'),array('captions','created_by'),array('captions','reviewed_by'),array('stream_credentials','created_by'),array('moderation','reviewer_id'),array('takedowns','claimant_id'),array('takedowns','reviewer_id'));foreach($checks as $spec){$t=VWLB_Helpers::table($spec[0]);if($wpdb->get_var($wpdb->prepare("SELECT id FROM $t WHERE {$spec[1]}=%d LIMIT 1",$uid)))return true;}$idem=VWLB_Helpers::table('idempotency');$scope='%'.$wpdb->esc_like(':u'.$uid).'%';return (bool)$wpdb->get_var($wpdb->prepare("SELECT id FROM $idem WHERE scope LIKE %s LIMIT 1",$scope));}
	public static function erase($email,$page=1){
		$user=get_user_by('email',$email);if(!$user)return array('items_removed'=>false,'items_retained'=>false,'messages'=>array(),'done'=>true);global $wpdb;$uid=(int)$user->ID;$removed=false;$messages=array();
		$upload_rows=$wpdb->get_results($wpdb->prepare('SELECT id,private_filename,status FROM '.VWLB_Helpers::table('upload_sessions').' WHERE owner_id=%d ORDER BY id ASC LIMIT 100',$uid),ARRAY_A);foreach((array)$upload_rows as $s){if(!empty($s['private_filename'])){$base=trailingslashit(WP_CONTENT_DIR).VWLB_Extensions::PRIVATE_DIR;$path=$base.'/'.sanitize_file_name($s['private_filename']);if(is_file($path)&&!unlink($path))return array('items_removed'=>$removed,'items_retained'=>true,'messages'=>array(__('A private upload could not be deleted from storage; retry safely.',VWLB_TEXT_DOMAIN)),'done'=>false);}}
		$interaction_rows=$wpdb->get_results($wpdb->prepare('SELECT id,video_id FROM '.VWLB_Helpers::table('interactions').' WHERE user_id=%d ORDER BY id ASC LIMIT 100',$uid),ARRAY_A);$interaction_ids=array_column((array)$interaction_rows,'id');$affected=array_values(array_unique(array_map('intval',array_column((array)$interaction_rows,'video_id'))));
		$result=VWLB_DB::transaction(function()use($wpdb,$uid,$upload_rows,$interaction_ids,$affected,&$removed){
			foreach(array(array('playback_sessions','user_id'),array('download_tokens','user_id'),array('live_poll_responses','user_id'),array('broadcast_guests','user_id')) as $spec){$t=VWLB_Helpers::table($spec[0]);$n=$wpdb->query($wpdb->prepare("DELETE FROM $t WHERE {$spec[1]}=%d ORDER BY id ASC LIMIT 100",$uid));if(false===$n)return VWLB_Helpers::error('vwlb_privacy_delete_failed',__('Privacy erasure failed safely.',VWLB_TEXT_DOMAIN),500);$removed=$removed||$n>0;}
			if($upload_rows){$ids=array_column($upload_rows,'id');if(!self::delete_ids('upload_sessions',$ids))return VWLB_Helpers::error('vwlb_privacy_delete_failed',__('Private upload records could not be erased.',VWLB_TEXT_DOMAIN),500);$removed=true;}
			if($interaction_ids){if(!self::delete_ids('interactions',$interaction_ids))return VWLB_Helpers::error('vwlb_privacy_delete_failed',__('Interaction records could not be erased.',VWLB_TEXT_DOMAIN),500);$removed=true;foreach($affected as $video_id)foreach(array('like','dislike') as $type){$count=(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.VWLB_Helpers::table('interactions').' WHERE video_id=%d AND interaction=%s',$video_id,$type));$changed=$wpdb->update(VWLB_Helpers::table('videos'),array($type.'_count'=>$count),array('id'=>$video_id));if(false===$changed)return VWLB_Helpers::error('vwlb_privacy_counter_failed',__('Interaction counters could not be reconciled.',VWLB_TEXT_DOMAIN),500);}}
			$attendees=$wpdb->get_results($wpdb->prepare('SELECT id,public_id,live_event_id FROM '.VWLB_Helpers::table('live_attendees').' WHERE user_id=%d ORDER BY id ASC LIMIT 100',$uid),ARRAY_A);foreach((array)$attendees as $row){$anon=self::anonymized_user_id($row['live_event_id'],$row['public_id']);if(!$anon)return VWLB_Helpers::error('vwlb_privacy_anonymize_failed',__('An anonymous attendee identity could not be allocated safely.',VWLB_TEXT_DOMAIN),500);$changed=$wpdb->update(VWLB_Helpers::table('live_attendees'),array('user_id'=>$anon,'state'=>'anonymized','updated_at'=>VWLB_Helpers::now()),array('id'=>$row['id'],'user_id'=>$uid));if(1!==$changed)return VWLB_Helpers::error('vwlb_privacy_anonymize_failed',__('Attendance could not be anonymized safely.',VWLB_TEXT_DOMAIN),500);}
			$anonymize=array(array('live_questions','user_id',array('user_id'=>0,'question'=>'[erased by privacy request]')),array('moderation','reporter_id',array('reporter_id'=>0,'note'=>'[anonymized by privacy erasure]')),array('audit','actor_id',array('actor_id'=>0)),array('creator_metrics_daily','owner_id',array('owner_id'=>0)),array('production_sources','owner_id',array('owner_id'=>0)),array('production_scenes','owner_id',array('owner_id'=>0)),array('simulcast_targets','created_by',array('created_by'=>0)),array('media_tracks','created_by',array('created_by'=>0)),array('media_tracks','reviewed_by',array('reviewed_by'=>0)),array('video_annotations','created_by',array('created_by'=>0)),array('video_annotations','reviewed_by',array('reviewed_by'=>0)),array('live_polls','created_by',array('created_by'=>0)),array('consent_links','created_by',array('created_by'=>0)),array('watermark_policies','updated_by',array('updated_by'=>0)),array('broadcast_guests','invited_by',array('invited_by'=>0)),array('captions','created_by',array('created_by'=>0)),array('captions','reviewed_by',array('reviewed_by'=>0)),array('stream_credentials','created_by',array('created_by'=>0)),array('moderation','reviewer_id',array('reviewer_id'=>0)),array('takedowns','claimant_id',array('claimant_id'=>0,'claimant_contact_hash'=>'')),array('takedowns','reviewer_id',array('reviewer_id'=>0)));
			foreach($anonymize as $spec){$sets=array();$args=array();foreach($spec[2] as $field=>$value){$sets[]="$field=%s";$args[]=(string)$value;}$args[]=$uid;$args[]=100;$t=VWLB_Helpers::table($spec[0]);$n=$wpdb->query($wpdb->prepare("UPDATE $t SET ".implode(',',$sets)." WHERE {$spec[1]}=%d ORDER BY id ASC LIMIT %d",$args));if(false===$n)return VWLB_Helpers::error('vwlb_privacy_anonymize_failed',__('Retained privacy data could not be anonymized.',VWLB_TEXT_DOMAIN),500);}
			$idem=VWLB_Helpers::table('idempotency');$like='%'.$wpdb->esc_like(':u'.$uid).'%';$n=$wpdb->query($wpdb->prepare("DELETE FROM $idem WHERE scope LIKE %s LIMIT 200",$like));if(false===$n)return VWLB_Helpers::error('vwlb_privacy_delete_failed',__('Historical idempotency records could not be erased.',VWLB_TEXT_DOMAIN),500);return true;
		});
		if(is_wp_error($result))return array('items_removed'=>$removed,'items_retained'=>true,'messages'=>array($result->get_error_message()),'done'=>false);$done=!self::privacy_has_more($uid);if($done){VWLB_Helpers::audit('privacy',VWLB_Helpers::public_id('erase'),'erase','','complete','Eligible File 10 data erased/anonymized.',array('purpose'=>'privacy_erasure','subject'=>'anonymized'));$messages[]=__('Retained safety/rights evidence was anonymized where required.',VWLB_TEXT_DOMAIN);}else{$messages[]=__('One bounded File 10 erasure batch completed; additional eligible records remain.',VWLB_TEXT_DOMAIN);}return array('items_removed'=>$removed,'items_retained'=>true,'messages'=>$messages,'done'=>$done);
	}

	public static function cleanup_hardening(){global $wpdb;$now=VWLB_Helpers::now();foreach(array('idempotency'=>'expires_at','rate_limits'=>'window_ends_at','playback_sessions'=>'expires_at','rollback_snapshots'=>'expires_at') as $table=>$column){$n=$wpdb->query($wpdb->prepare('DELETE FROM '.VWLB_Helpers::table($table)." WHERE $column IS NOT NULL AND $column<%s LIMIT 1000",$now));if(false===$n)do_action('vwlb_operational_failure','cleanup','vwlb_cleanup_delete_failed',array('table'=>$table));}$n=$wpdb->query($wpdb->prepare('UPDATE '.VWLB_Helpers::table('stream_credentials')." SET status='expired' WHERE status='active' AND expires_at IS NOT NULL AND expires_at<%s LIMIT 1000",$now));if(false===$n)do_action('vwlb_operational_failure','cleanup','vwlb_stream_credential_expiry_failed',array());$n=$wpdb->query($wpdb->prepare('UPDATE '.VWLB_Helpers::table('download_tokens')." SET status='expired',updated_at=%s WHERE status='active' AND expires_at<%s LIMIT 1000",$now,$now));if(false===$n)do_action('vwlb_operational_failure','cleanup','vwlb_download_token_expiry_failed',array());}

	public static function capture_inbox_retry($event_id,$event_name,$payload){$event_id=VWLB_Helpers::text($event_id,100);if(!$event_id)return;$key=self::INBOX_RETRY_PREFIX.hash('sha256',$event_id);$record=array('event_id'=>$event_id,'event_name'=>VWLB_Helpers::text($event_name,100),'payload'=>(array)$payload,'payload_hash'=>hash('sha256',VWLB_Helpers::json_encode($payload)),'captured_at'=>VWLB_Helpers::now());update_option($key,$record,false);}
	public static function release_processed_inbox_retry($event_id,$event_name,$payload){global $wpdb;$status=$wpdb->get_var($wpdb->prepare('SELECT status FROM '.VWLB_Helpers::table('inbox').' WHERE event_id=%s LIMIT 1',VWLB_Helpers::text($event_id,100)));if('processed'===$status)delete_option(self::INBOX_RETRY_PREFIX.hash('sha256',VWLB_Helpers::text($event_id,100)));}
	private static function retry_options($prefix,$limit=50){global $wpdb;$like=$wpdb->esc_like($prefix).'%';return $wpdb->get_results($wpdb->prepare("SELECT option_name,option_value FROM {$wpdb->options} WHERE option_name LIKE %s ORDER BY option_id ASC LIMIT %d",$like,max(1,min(100,$limit))),ARRAY_A);}
	public static function reconcile_inbox_retries(){global $wpdb;$table=VWLB_Helpers::table('inbox');foreach(self::retry_options(self::INBOX_RETRY_PREFIX,25) as $option){$record=maybe_unserialize($option['option_value']);if(!is_array($record)||empty($record['event_id'])){delete_option($option['option_name']);continue;}$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM $table WHERE event_id=%s LIMIT 1",$record['event_id']),ARRAY_A);if($row&&'processed'===$row['status']){delete_option($option['option_name']);continue;}if($row&&'processing'===$row['status']&&strtotime($row['received_at'].' UTC')>time()-15*MINUTE_IN_SECONDS)continue;if($row&&!hash_equals((string)$row['payload_hash'],(string)$record['payload_hash'])){do_action('vwlb_operational_failure','inbox','vwlb_inbox_retry_hash_conflict',array('event_id_hash'=>hash('sha256',$record['event_id'])));continue;}if($row){$deleted=$wpdb->delete($table,array('id'=>$row['id']),array('%d'));if(1!==$deleted)continue;}$consumer=new VWLB_Integrations();$result=$consumer->consume($record['event_id'],$record['event_name'],$record['payload']);if(!is_wp_error($result)&&!empty($result['processed']))delete_option($option['option_name']);}}

	public static function reconcile_fallbacks(){global $wpdb;foreach(self::retry_options(self::AUDIT_FALLBACK_PREFIX,50) as $option){$r=maybe_unserialize($option['option_value']);if(!is_array($r)){delete_option($option['option_name']);continue;}$saved=$wpdb->insert(VWLB_Helpers::table('audit'),$r);if($saved)delete_option($option['option_name']);}foreach(self::retry_options(self::OUTBOX_FALLBACK_PREFIX,50) as $option){$r=maybe_unserialize($option['option_value']);if(!is_array($r)){delete_option($option['option_name']);continue;}$saved=$wpdb->insert(VWLB_Helpers::table('outbox'),$r);if($saved)delete_option($option['option_name']);}}
}
