<?php
/** R97: privacy erasure must remove every resumable private upload file before deleting its database row. */
defined('ABSPATH') || exit;
final class VWLB_R97_Privacy_Storage_Erasure_Guard {
	const BATCH=100;
	public static function register(){add_filter('wp_privacy_personal_data_erasers',array(__CLASS__,'replace_eraser'),110);}
	public static function replace_eraser($erasers){$erasers['vwlb']=array('eraser_friendly_name'=>__('Video Wall and Live Broadcasting',VWLB_TEXT_DOMAIN),'callback'=>array(__CLASS__,'erase'));return $erasers;}
	private static function path($filename){$base=trailingslashit(WP_CONTENT_DIR).VWLB_Extensions::PRIVATE_DIR;if(is_link($base)||!is_dir($base))return VWLB_Helpers::error('vwlb_privacy_private_storage_unavailable',__('Private upload storage could not be verified for erasure.',VWLB_TEXT_DOMAIN),503);$root=realpath($base);$content=realpath(WP_CONTENT_DIR);if(!$root||!$content||0!==strpos($root,$content.DIRECTORY_SEPARATOR))return VWLB_Helpers::error('vwlb_privacy_private_storage_escape',__('Private upload storage escaped the approved content boundary.',VWLB_TEXT_DOMAIN),503);$name=sanitize_file_name(basename((string)$filename));if(!$name||!str_ends_with($name,'.part'))return VWLB_Helpers::error('vwlb_privacy_private_filename_invalid',__('A private upload filename could not be verified for erasure.',VWLB_TEXT_DOMAIN),503);$path=trailingslashit($root).$name;if(is_link($path))return VWLB_Helpers::error('vwlb_privacy_private_upload_symlink',__('A private upload symlink prevented safe erasure.',VWLB_TEXT_DOMAIN),503);return $path;}
	private static function erase_upload_files($uid){global $wpdb;$table=VWLB_Helpers::table('upload_sessions');$wpdb->last_error='';$rows=$wpdb->get_results($wpdb->prepare("SELECT id,private_filename,status FROM {$table} WHERE owner_id=%d ORDER BY id ASC LIMIT %d",(int)$uid,self::BATCH),ARRAY_A);if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_privacy_upload_read_failed',__('Private upload state could not be read safely for erasure.',VWLB_TEXT_DOMAIN),503);foreach((array)$rows as $row){if(empty($row['private_filename']))continue;$path=self::path($row['private_filename']);if(is_wp_error($path))return $path;if(!file_exists($path))continue;if(!is_file($path))return VWLB_Helpers::error('vwlb_privacy_private_upload_invalid',__('A private upload path is not a regular file.',VWLB_TEXT_DOMAIN),503,array('session_id'=>(int)$row['id']));$fp=@fopen($path,'rb');if(!$fp)return VWLB_Helpers::error('vwlb_privacy_private_upload_open_failed',__('A private upload could not be opened for safe erasure.',VWLB_TEXT_DOMAIN),503,array('session_id'=>(int)$row['id']));if(!flock($fp,LOCK_EX|LOCK_NB)){fclose($fp);return VWLB_Helpers::error('vwlb_privacy_private_upload_busy',__('A private upload is still being written; retry erasure safely.',VWLB_TEXT_DOMAIN),409,array('session_id'=>(int)$row['id']));}$deleted=@unlink($path);flock($fp,LOCK_UN);fclose($fp);if(!$deleted&&file_exists($path))return VWLB_Helpers::error('vwlb_privacy_private_upload_delete_failed',__('A private upload could not be deleted; database erasure was stopped for retry.',VWLB_TEXT_DOMAIN),503,array('session_id'=>(int)$row['id']));}return true;}
	public static function erase($email,$page=1){$user=get_user_by('email',$email);if(!$user)return array('items_removed'=>false,'items_retained'=>false,'messages'=>array(),'done'=>true);$storage=self::erase_upload_files((int)$user->ID);if(is_wp_error($storage)){do_action('vwlb_operational_failure','privacy',$storage->get_error_code(),array('phase'=>'r97-private-storage-erasure'));return array('items_removed'=>false,'items_retained'=>true,'messages'=>array($storage->get_error_message()),'done'=>false);}return VWLB_R50_Privacy_Proof::erase($email,$page);}
}
