<?php
/** R03 playback isolation: anonymous-session uniqueness, secure delivery and observable counters. */
defined( 'ABSPATH' ) || exit;
final class VWLB_R3_Playback {
	public static function register(){add_action('rest_api_init',array(__CLASS__,'register_rest_overrides'),40);}
	public static function register_rest_overrides(){foreach(VWLB_Contracts::namespaces() as $n){register_rest_route($n,'/videos/(?P<id>[A-Za-z0-9_-]+)/playback',array('methods'=>'GET','callback'=>array(__CLASS__,'playback'),'permission_callback'=>'__return_true'),true);}}
	private static function response($value,$status=200){if(is_wp_error($value))return $value;$r=rest_ensure_response($value);$r->set_status($status);$r->header('X-Sabri-File','10');$r->header('X-VWLB-Version',VWLB_VERSION);$r->header('Cache-Control','private, no-store');return $r;}
	private static function anonymous_session_surrogate($video){$seed=hash_hmac('sha256','anon-playback|'.(int)$video['id'].'|'.VWLB_Helpers::ip_hash().'|'.VWLB_Helpers::ua_hash(),wp_salt('logged_in'));$base=4611686018427387904;$span=4000000000000000000;$candidate=$base+(hexdec(substr($seed,0,13))%$span);for($i=0;$i<16;$i++){if(!get_userdata($candidate))return $candidate;$candidate++;}return 0;}
	private static function playback_session($video){global $wpdb;$real_user=get_current_user_id();$user=$real_user;if(!$user){$user=self::anonymous_session_surrogate($video);if(!$user)return VWLB_Helpers::error('vwlb_playback_session_failed',__('Anonymous playback session could not be isolated safely.',VWLB_TEXT_DOMAIN),503);}$now=VWLB_Helpers::now();$token=VWLB_Helpers::public_id('play');$hash=hash_hmac('sha256',$token,wp_salt('logged_in'));$table=VWLB_Helpers::table('playback_sessions');$row=$wpdb->get_row($wpdb->prepare("SELECT id,progress_seconds FROM $table WHERE user_id=%d AND object_type=%s AND object_id=%d",$user,'video',$video['id']),ARRAY_A);if($row){$changed=$wpdb->update($table,array('token_hash'=>$hash,'ip_hash'=>VWLB_Helpers::ip_hash(),'user_agent_hash'=>VWLB_Helpers::ua_hash(),'updated_at'=>$now,'expires_at'=>gmdate('Y-m-d H:i:s',time()+($real_user?30*DAY_IN_SECONDS:2*HOUR_IN_SECONDS))),array('id'=>$row['id']));if(false===$changed)return VWLB_Helpers::error('vwlb_playback_session_failed',__('Playback session could not be refreshed.',VWLB_TEXT_DOMAIN),503);return array('token'=>$token,'resume_seconds'=>$real_user?(int)$row['progress_seconds']:0);}$saved=$wpdb->insert($table,array('public_id'=>VWLB_Helpers::public_id('ses'),'user_id'=>$user,'object_type'=>'video','object_id'=>$video['id'],'token_hash'=>$hash,'progress_seconds'=>0,'duration_seconds'=>(int)$video['duration_seconds'],'ip_hash'=>VWLB_Helpers::ip_hash(),'user_agent_hash'=>VWLB_Helpers::ua_hash(),'created_at'=>$now,'updated_at'=>$now,'expires_at'=>gmdate('Y-m-d H:i:s',time()+($real_user?30*DAY_IN_SECONDS:2*HOUR_IN_SECONDS))));if(!$saved)return VWLB_Helpers::error('vwlb_playback_session_failed',__('Playback session could not be created.',VWLB_TEXT_DOMAIN),503);return array('token'=>$token,'resume_seconds'=>0);}
	private static function count_view($video){if(is_admin()||current_user_can(VWLB_Contracts::CAP_MANAGE))return;$ua=strtolower((string)($_SERVER['HTTP_USER_AGENT']??''));if(preg_match('/bot|crawler|spider|preview|monitor/',$ua))return;$key='vwlb_view_'.hash('sha256',$video['id'].'|'.get_current_user_id().'|'.VWLB_Helpers::ip_hash());if(get_transient($key))return;set_transient($key,1,6*HOUR_IN_SECONDS);global $wpdb;$changed=$wpdb->query($wpdb->prepare('UPDATE '.VWLB_Helpers::table('videos').' SET view_count=view_count+1 WHERE id=%d',$video['id']));if(false===$changed)do_action('vwlb_operational_failure','video_metrics','vwlb_view_counter_failed',array('video_public_id'=>$video['public_id']??''));}
	public static function playback(WP_REST_Request $r){$video=VWLB_Repository::video_bundle($r['id']);if(!$video||!VWLB_Security::can_view($video))return VWLB_Helpers::error('vwlb_not_found',__('Video not found.',VWLB_TEXT_DOMAIN),404);$provider=VWLB_Providers::get($video['provider']);if(!$provider)return VWLB_Helpers::error('vwlb_provider_missing',__('Playback provider is unavailable.',VWLB_TEXT_DOMAIN),503);$payload=$provider->playback($video,VWLB_Security::claims());if(is_wp_error($payload))return $payload;$session=self::playback_session($video);if(is_wp_error($session))return $session;if(!in_array($video['visibility'],array('public','unlisted'),true)){$secure=apply_filters('vwlb_secure_playback_grant','',$video,$payload,$session,VWLB_Security::claims());if(!$secure)return VWLB_Helpers::error('vwlb_secure_delivery_required',__('Secure playback delivery is not configured.',VWLB_TEXT_DOMAIN),503);$payload['url']=esc_url_raw($secure);}self::count_view($video);$result=array('video'=>VWLB_Repository::public_video_dto($video),'playback'=>$payload,'session'=>$session,'chapters'=>VWLB_Extensions::chapters('video',$video['id']),'media_tracks'=>VWLB_Future_Safety::published_tracks('video',$video['id']),'preferences'=>array('autoplay'=>false,'low_bandwidth'=>(bool)($r['low_bandwidth']??false),'reduced_motion'=>false));return self::response($result);}
}
