<?php
/** Reports, live moderation, copyright/takedown and appeal history. */
defined( 'ABSPATH' ) || exit;
final class VWLB_Moderation {
	private static function resolve_public_target($target_type,$target_ref,$purpose='report'){
		$target_ref=VWLB_Helpers::text($target_ref,191);if(!$target_ref||ctype_digit($target_ref))return VWLB_Helpers::error('vwlb_public_target_required',__('Use the target public identifier, not an internal database ID.',VWLB_TEXT_DOMAIN),422);
		if(in_array($target_type,array('video','live'),true)){$entity='video'===$target_type?'videos':'live_events';$row=VWLB_Repository::find($entity,$target_ref);if(!$row||!VWLB_Security::can_view($row,$purpose))return VWLB_Helpers::error('vwlb_not_found',__('Moderation target not found.',VWLB_TEXT_DOMAIN),404);return array('id'=>(int)$row['id'],'public_id'=>$row['public_id']);}
		if('caption'===$target_type){$caption=VWLB_Repository::find('captions',$target_ref);$video=$caption?VWLB_Repository::find('videos',$caption['video_id']):null;if(!$caption||!$video||!VWLB_Security::can_view($video,$purpose))return VWLB_Helpers::error('vwlb_not_found',__('Moderation target not found.',VWLB_TEXT_DOMAIN),404);return array('id'=>(int)$caption['id'],'public_id'=>$caption['public_id']);}
		if('chat'===$target_type){$resolved=apply_filters('vwlb_live_chat_report_target',null,$target_ref,get_current_user_id());if(!is_array($resolved)||empty($resolved['id'])||empty($resolved['public_id']))return VWLB_Helpers::error('vwlb_chat_target_unavailable',__('The contextual live-chat target could not be verified by File 17.',VWLB_TEXT_DOMAIN),422);return array('id'=>absint($resolved['id']),'public_id'=>VWLB_Helpers::text($resolved['public_id'],191));}
		return VWLB_Helpers::error('vwlb_report_invalid',__('Target type is invalid.',VWLB_TEXT_DOMAIN),422);
	}

	public static function report($data){
		if(!is_user_logged_in())return VWLB_Helpers::error('vwlb_login_required',__('Sign in to report content.',VWLB_TEXT_DOMAIN),401);$rate=VWLB_Security::rate_limit('media_report',10,HOUR_IN_SECONDS);if(is_wp_error($rate))return $rate;$target_type=VWLB_Helpers::enum($data['target_type']??'',array('video','live','caption','chat'),'');$reason=VWLB_Helpers::text($data['reason']??'',191);if(!$target_type||!$reason)return VWLB_Helpers::error('vwlb_report_invalid',__('Target and reason are required.',VWLB_TEXT_DOMAIN),422);$target=self::resolve_public_target($target_type,$data['target_id']??($data['target_public_id']??''),'report');if(is_wp_error($target))return $target;
		global $wpdb;$now=VWLB_Helpers::now();$public=VWLB_Helpers::public_id('mod');$saved=$wpdb->insert(VWLB_Helpers::table('moderation'),array('public_id'=>$public,'target_type'=>$target_type,'target_id'=>$target['id'],'reason'=>$reason,'action'=>'reported','status'=>'open','severity'=>VWLB_Helpers::enum($data['severity']??'medium',array('low','medium','high','critical'),'medium'),'note'=>VWLB_Helpers::textarea($data['note']??'',10000),'evidence_json'=>VWLB_Helpers::json_encode($data['evidence']??array()),'reporter_id'=>get_current_user_id(),'created_at'=>$now,'updated_at'=>$now));if(!$saved||!(int)$wpdb->insert_id)return VWLB_Helpers::error('vwlb_database_error',__('Moderation report could not be saved.',VWLB_TEXT_DOMAIN),500);$id=(int)$wpdb->insert_id;VWLB_Helpers::audit('moderation',$id,'report','','open',$reason,array('target_public_id'=>$target['public_id']));do_action('vwlb_moderation_reported',$id,array_merge($data,array('target_public_id'=>$target['public_id'])));return array('public_id'=>$public,'status'=>'open');
	}
	private static function safe_restore_status($target_type,$previous,$target){
		$previous=sanitize_key($previous);if('video'===$target_type&&in_array($previous,array('published','scheduled'),true))return $previous;if('live'===$target_type){if(in_array($previous,array('scheduled','ended','replay_published'),true))return $previous;if(in_array($previous,array('live','interrupted'),true))return 'interrupted';if(in_array($previous,array('rehearsal','ready'),true))return 'scheduled';}return VWLB_Helpers::error('vwlb_restore_state_unproven',__('The pre-restriction state is unavailable or unsafe to restore automatically.',VWLB_TEXT_DOMAIN),409);
	}

	public static function decide($report_id,$action,$note){
		$report=VWLB_Repository::find('moderation',$report_id);if(!$report)return VWLB_Helpers::error('vwlb_report_missing',__('Report not found.',VWLB_TEXT_DOMAIN),404);if(!VWLB_Security::can(VWLB_Contracts::CAP_MODERATE,null,'moderation_decision'))return VWLB_Helpers::error('vwlb_forbidden',__('You cannot moderate media.',VWLB_TEXT_DOMAIN),403);$action=VWLB_Helpers::enum($action,array('dismiss','restrict','remove','block','slow_mode','restore','escalate'),'');if(!$action||!trim($note))return VWLB_Helpers::error('vwlb_moderation_note_required',__('A decision and reason are required.',VWLB_TEXT_DOMAIN),422);
		return VWLB_DB::transaction(function()use($report,$action,$note){global $wpdb;$table=VWLB_Helpers::table('moderation');$fresh=$wpdb->get_row($wpdb->prepare("SELECT * FROM $table WHERE id=%d FOR UPDATE",$report['id']),ARRAY_A);if(!$fresh)return VWLB_Helpers::error('vwlb_report_missing',__('Report not found.',VWLB_TEXT_DOMAIN),404);$restore_case='restore'===$action&&'closed'===$fresh['status']&&in_array($fresh['action'],array('restrict','remove'),true);if(!$restore_case&&!in_array($fresh['status'],array('open','escalated'),true))return VWLB_Helpers::error('vwlb_moderation_conflict',__('This report is no longer open for this decision.',VWLB_TEXT_DOMAIN),409);$status=in_array($action,array('dismiss','restrict','remove','block','restore'),true)?'closed':'escalated';$evidence=VWLB_Helpers::json($fresh['evidence_json']??'{}');
			if('live'===$fresh['target_type']&&'slow_mode'===$action){$live=VWLB_Repository::find('live_events',$fresh['target_id'],true);if(!$live)return VWLB_Helpers::error('vwlb_target_missing',__('Moderation target no longer exists.',VWLB_TEXT_DOMAIN),404);$changed=VWLB_Repository::update_versioned('live_events',$live['id'],$live['version'],array('slow_mode_seconds'=>(int)apply_filters('vwlb_moderation_slow_mode_seconds',30,$fresh)));if(is_wp_error($changed))return $changed;}
			if(in_array($fresh['target_type'],array('video','live'),true)&&in_array($action,array('restrict','remove','restore'),true)){$entity='video'===$fresh['target_type']?'videos':'live_events';$row=VWLB_Repository::find($entity,$fresh['target_id'],true);if(!$row)return VWLB_Helpers::error('vwlb_target_missing',__('Moderation target no longer exists.',VWLB_TEXT_DOMAIN),404);if('restore'===$action){if(!in_array($row['status'],array('restricted','removed'),true))return VWLB_Helpers::error('vwlb_restore_target_not_restricted',__('Only content restricted by this case may be restored.',VWLB_TEXT_DOMAIN),409);$new=self::safe_restore_status($fresh['target_type'],$evidence['target_previous_status']??'',$row);if(is_wp_error($new))return $new;}else{if(empty($evidence['target_previous_status'])&&!in_array($row['status'],array('restricted','removed'),true))$evidence['target_previous_status']=$row['status'];$new='remove'===$action?'removed':'restricted';}$changed=VWLB_Repository::update_versioned($entity,$row['id'],$row['version'],array('status'=>$new));if(is_wp_error($changed))return $changed;VWLB_Helpers::outbox(ucfirst($fresh['target_type']).ucfirst($new),$fresh['target_type'],$row['id'],array('reason_category'=>$fresh['reason'],'case_public_id'=>$fresh['public_id']));}
			$changed=$wpdb->update($table,array('action'=>$action,'status'=>$status,'note'=>VWLB_Helpers::textarea($note,10000),'evidence_json'=>VWLB_Helpers::json_encode($evidence),'reviewer_id'=>get_current_user_id(),'updated_at'=>VWLB_Helpers::now(),'closed_at'=>'closed'===$status?VWLB_Helpers::now():null),array('id'=>$fresh['id'],'status'=>$fresh['status'],'action'=>$fresh['action']));if(1!==$changed)return VWLB_Helpers::error('vwlb_moderation_conflict',__('Moderation report changed concurrently.',VWLB_TEXT_DOMAIN),409);if(in_array($fresh['target_type'],array('chat','live'),true)&&in_array($action,array('block','slow_mode'),true))do_action('vwlb_live_chat_moderation',$action,$fresh);VWLB_Helpers::audit('moderation',$fresh['id'],'decide',$fresh['status'],$status,$note,array('action'=>$action));return array('public_id'=>$fresh['public_id'],'status'=>$status,'action'=>$action);
		});
	}
	public static function file_takedown($data){
		$rate=VWLB_Security::rate_limit('takedown',5,DAY_IN_SECONDS);if(is_wp_error($rate))return $rate;$target_type=VWLB_Helpers::enum($data['target_type']??'',array('video','live'),'');$basis=VWLB_Helpers::text($data['rights_basis']??'',191);if(!$target_type||!$basis)return VWLB_Helpers::error('vwlb_takedown_invalid',__('Target and rights basis are required.',VWLB_TEXT_DOMAIN),422);$target=self::resolve_public_target($target_type,$data['target_id']??($data['target_public_id']??''),'takedown');if(is_wp_error($target))return $target;
		global $wpdb;$now=VWLB_Helpers::now();$public=VWLB_Helpers::public_id('td');$saved=$wpdb->insert(VWLB_Helpers::table('takedowns'),array('public_id'=>$public,'target_type'=>$target_type,'target_id'=>$target['id'],'claimant_id'=>get_current_user_id(),'claimant_contact_hash'=>hash_hmac('sha256',sanitize_email($data['contact']??''),wp_salt('auth')),'rights_basis'=>$basis,'evidence_json'=>VWLB_Helpers::json_encode($data['evidence']??array()),'status'=>'reported','created_at'=>$now,'updated_at'=>$now));if(!$saved||!(int)$wpdb->insert_id)return VWLB_Helpers::error('vwlb_database_error',__('Takedown report could not be saved.',VWLB_TEXT_DOMAIN),500);$id=(int)$wpdb->insert_id;VWLB_Helpers::audit('takedown',$id,'file','','reported',$basis,array('target_public_id'=>$target['public_id']));do_action('vwlb_takedown_filed',$id,array_merge($data,array('target_public_id'=>$target['public_id'])));return array('public_id'=>$public,'status'=>'reported');
	}
	public static function transition_takedown($id,$to,$expected_version,$reason){
		$case=VWLB_Repository::find('takedowns',$id);if(!$case)return VWLB_Helpers::error('vwlb_takedown_missing',__('Takedown case not found.',VWLB_TEXT_DOMAIN),404);$owner=(int)$case['claimant_id']===get_current_user_id();$moderator=VWLB_Security::can(VWLB_Contracts::CAP_MODERATE,null,'takedown_decision');$to=VWLB_Helpers::enum($to,VWLB_Contracts::TAKEDOWN_STATES,'');if($owner&&!$moderator&&!in_array($to,array('appealed','closed'),true))return VWLB_Helpers::error('vwlb_takedown_decision_forbidden',__('Claimants may appeal or close their own case, but cannot issue moderation decisions.',VWLB_TEXT_DOMAIN),403);if(!$owner&&!$moderator)return VWLB_Helpers::error('vwlb_forbidden',__('You cannot update this case.',VWLB_TEXT_DOMAIN),403);$assert=VWLB_State_Machine::assert('takedown',$case['status'],$to);if(is_wp_error($assert))return $assert;if(!$reason)return VWLB_Helpers::error('vwlb_reason_required',__('A reason is required.',VWLB_TEXT_DOMAIN),422);
		return VWLB_DB::transaction(function()use($case,$to,$expected_version,$reason,$moderator){$fresh=VWLB_Repository::find('takedowns',$case['id'],true);if(!$fresh||(int)$fresh['version']!==(int)$expected_version)return VWLB_Helpers::error('vwlb_version_conflict',__('Takedown case changed. Refresh and try again.',VWLB_TEXT_DOMAIN),409);$evidence=VWLB_Helpers::json($fresh['evidence_json']??'{}');if(in_array($to,array('restricted','removed','restored'),true)){$entity='video'===$fresh['target_type']?'videos':'live_events';$target=VWLB_Repository::find($entity,$fresh['target_id'],true);if(!$target)return VWLB_Helpers::error('vwlb_target_missing',__('Copyright target no longer exists.',VWLB_TEXT_DOMAIN),404);if('restored'===$to){if(!in_array($target['status'],array('restricted','removed'),true))return VWLB_Helpers::error('vwlb_restore_target_not_restricted',__('Copyright target is not in a restricted state.',VWLB_TEXT_DOMAIN),409);$status=self::safe_restore_status($fresh['target_type'],$evidence['target_previous_status']??'',$target);if(is_wp_error($status))return $status;}else{if(empty($evidence['target_previous_status'])&&!in_array($target['status'],array('restricted','removed'),true))$evidence['target_previous_status']=$target['status'];$status='removed'===$to?'removed':'restricted';}$changed=VWLB_Repository::update_versioned($entity,$target['id'],$target['version'],array('status'=>$status));if(is_wp_error($changed))return $changed;VWLB_Helpers::outbox('Copyright'.ucfirst($to),$fresh['target_type'],$target['id'],array('case_public_id'=>$fresh['public_id']));}$updated=VWLB_Repository::update_versioned('takedowns',$fresh['id'],$fresh['version'],array('status'=>$to,'evidence_json'=>VWLB_Helpers::json_encode($evidence),'decision_reason'=>VWLB_Helpers::textarea($reason,10000),'reviewer_id'=>$moderator?get_current_user_id():0,'closed_at'=>in_array($to,array('removed','restored','closed'),true)?VWLB_Helpers::now():null));if(is_wp_error($updated))return $updated;VWLB_Helpers::audit('takedown',$fresh['id'],'transition',$fresh['status'],$to,$reason);return $updated;});
	}
}
