<?php
/** R79/R81: forensic watermark grants are session-aware and reuse one verified policy snapshot. */
defined( 'ABSPATH' ) || exit;
final class VWLB_R79_Watermark_Session_Guard {
	public static function register(){add_filter('rest_request_before_callbacks',array(__CLASS__,'guard'),24,3);}
	private static function matches($request){if(!$request instanceof WP_REST_Request||'POST'!==strtoupper((string)$request->get_method()))return false;$route=(string)$request->get_route();foreach(VWLB_Contracts::namespaces() as $n){if(preg_match('#^/'.preg_quote($n,'#').'/watermarks/(video|live)/([A-Za-z0-9_-]+)/grant$#',$route))return true;}return false;}
	private static function object($type,$id){return 'video'===$type?VWLB_Repository::find('videos',$id):('live'===$type?VWLB_Repository::find('live_events',$id):null);}
	private static function policy($type,$object){global $wpdb;$table=VWLB_Helpers::table('watermark_policies');$wpdb->last_error='';$row=$wpdb->get_row($wpdb->prepare("SELECT mode,status,version FROM {$table} WHERE object_type=%s AND object_id=%d LIMIT 1",$type,(int)$object['id']),ARRAY_A);if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_watermark_policy_unreadable',__('Watermark policy could not be verified safely.',VWLB_TEXT_DOMAIN),503);return $row;}
	private static function video_session($request,$object){
		$token=VWLB_Helpers::text($request->get_header('X-VWLB-Playback-Token'),200);if(!$token)return VWLB_Helpers::error('vwlb_watermark_session_required',__('A current playback session is required for forensic watermarking.',VWLB_TEXT_DOMAIN),401);
		global $wpdb;$table=VWLB_Helpers::table('playback_sessions');$hash=hash_hmac('sha256',$token,wp_salt('logged_in'));$wpdb->last_error='';$row=$wpdb->get_row($wpdb->prepare("SELECT public_id,user_id,ip_hash,user_agent_hash,expires_at FROM {$table} WHERE object_type='video' AND object_id=%d AND token_hash=%s LIMIT 1",(int)$object['id'],$hash),ARRAY_A);if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_watermark_session_unreadable',__('Playback session could not be verified safely.',VWLB_TEXT_DOMAIN),503);if(!$row||empty($row['public_id'])||(!empty($row['expires_at'])&&strtotime($row['expires_at'].' UTC')<=time()))return VWLB_Helpers::error('vwlb_watermark_session_invalid',__('The playback session is unavailable or expired.',VWLB_TEXT_DOMAIN),401);
		$uid=get_current_user_id();if($uid){if((int)$row['user_id']!==$uid)return VWLB_Helpers::error('vwlb_watermark_session_invalid',__('The playback session does not belong to this viewer.',VWLB_TEXT_DOMAIN),401);}else{if(!hash_equals((string)($row['ip_hash']??''),VWLB_Helpers::ip_hash())||!hash_equals((string)($row['user_agent_hash']??''),VWLB_Helpers::ua_hash()))return VWLB_Helpers::error('vwlb_watermark_session_invalid',__('The anonymous playback session context changed.',VWLB_TEXT_DOMAIN),401);}
		return VWLB_Helpers::text($row['public_id'],80);
	}
	private static function live_session($object){if(!is_user_logged_in())return VWLB_Helpers::error('vwlb_watermark_session_required',__('A joined live session is required for forensic watermarking.',VWLB_TEXT_DOMAIN),401);global $wpdb;$table=VWLB_Helpers::table('live_attendees');$wpdb->last_error='';$row=$wpdb->get_row($wpdb->prepare("SELECT public_id FROM {$table} WHERE live_event_id=%d AND user_id=%d AND state IN ('approved','joined') LIMIT 1",(int)$object['id'],get_current_user_id()),ARRAY_A);if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_watermark_session_unreadable',__('Live viewer session could not be verified safely.',VWLB_TEXT_DOMAIN),503);if(!$row||empty($row['public_id']))return VWLB_Helpers::error('vwlb_watermark_session_invalid',__('A current approved or joined live session is required.',VWLB_TEXT_DOMAIN),401);return VWLB_Helpers::text($row['public_id'],80);}
	private static function grant_payload($policy,$type,$object,$session_ref){
		$mode=is_array($policy)&&'active'===($policy['status']??'')?($policy['mode']??'off'):'off';if('off'===$mode)return array('mode'=>'off');
		$nonce=wp_generate_uuid4();$fingerprint=hash_hmac('sha256',(int)get_current_user_id().'|'.($object['public_id']??$object['id']).'|'.$session_ref.'|'.$nonce,wp_salt('auth'));$token=substr($fingerprint,0,32);$expires=gmdate('c',time()+15*MINUTE_IN_SECONDS);
		if(in_array($mode,array('forensic','both'),true))VWLB_Helpers::audit('watermark_grant',$object['id'],'issue','','','',array('object_type'=>$type,'object_public_id'=>VWLB_Helpers::text($object['public_id']??'',80),'policy_version'=>(int)($policy['version']??0),'token_hash'=>hash('sha256',$token),'session_ref_hash'=>$session_ref?hash('sha256',$session_ref):'','expires_at'=>$expires));
		return array('mode'=>$mode,'token'=>$token,'visible_label'=>in_array($mode,array('visible','both'),true)?VWLB_Helpers::text(apply_filters('vwlb_visible_watermark_label',__('Protected educational media',VWLB_TEXT_DOMAIN),$type,$object),128):'','expires_at'=>$expires,'non_guarantee'=>'Watermarking is deterrence/trace evidence, not an absolute copying-prevention guarantee.');
	}
	private static function response($value){if(is_wp_error($value))return $value;$r=rest_ensure_response($value);$r->header('X-Sabri-File','10');$r->header('X-VWLB-Version',VWLB_VERSION);$r->header('X-VWLB-Future','24');$r->header('Cache-Control','private, no-store');return $r;}
	public static function guard($response,$handler,$request){
		if(null!==$response||!self::matches($request))return $response;$type=VWLB_Helpers::enum($request['object_type'],array('video','live'),'');$object=self::object($type,$request['id']);if(!$type||!$object||!VWLB_Security::can_view($object))return VWLB_Helpers::error('vwlb_not_found',__('Media not found.',VWLB_TEXT_DOMAIN),404);$policy=self::policy($type,$object);if(is_wp_error($policy))return $policy;
		$session_ref='';$mode=is_array($policy)&&'active'===($policy['status']??'')?($policy['mode']??'off'):'off';if(in_array($mode,array('forensic','both'),true)){$session_ref='video'===$type?self::video_session($request,$object):self::live_session($object);if(is_wp_error($session_ref))return $session_ref;}
		try{$payload=self::grant_payload($policy,$type,$object,$session_ref);}catch(Throwable $e){do_action('vwlb_operational_failure','watermark','vwlb_watermark_grant_exception',array('object_type'=>$type,'object_public_id'=>$object['public_id']??''));return VWLB_Helpers::error('vwlb_watermark_grant_failed',__('Watermark grant could not be issued safely.',VWLB_TEXT_DOMAIN),503);}return self::response($payload);
	}
}
