<?php
/** WordPress privacy exporters/erasers and private-history controls. */
defined( 'ABSPATH' ) || exit;
final class VWLB_Privacy {
	public function exporters($exporters){$exporters['vwlb']=array('exporter_friendly_name'=>__('Video Wall and Live Broadcasting',VWLB_TEXT_DOMAIN),'callback'=>array($this,'export'));return $exporters;}
	public function erasers($erasers){$erasers['vwlb']=array('eraser_friendly_name'=>__('Video Wall and Live Broadcasting',VWLB_TEXT_DOMAIN),'callback'=>array($this,'erase'));return $erasers;}
	public function policy($content){$text='<p>'.esc_html__('File 10 stores private watch progress, saved videos, reports, creator records, moderation history and short-lived playback/security metadata as needed for the service. Public media metadata remains public while eligible. Credentials are stored only as hashes. Users may export or erase eligible private data; safety, rights and audit records may be anonymized or retained under a scoped legal hold.',VWLB_TEXT_DOMAIN).'</p>';return $content.$text;}
	public function export($email,$page=1){$user=get_user_by('email',$email);if(!$user)return array('data'=>array(),'done'=>true);global $wpdb;$limit=100;$offset=(max(1,(int)$page)-1)*$limit;$data=array();$sessions=$wpdb->get_results($wpdb->prepare('SELECT object_type,object_id,progress_seconds,duration_seconds,completed,updated_at FROM '.VWLB_Helpers::table('playback_sessions').' WHERE user_id=%d ORDER BY id LIMIT %d OFFSET %d',$user->ID,$limit,$offset),ARRAY_A);foreach($sessions as $s)$data[]=array('group_id'=>'vwlb-history','group_label'=>__('Video history',VWLB_TEXT_DOMAIN),'item_id'=>'session-'.$s['object_type'].'-'.$s['object_id'],'data'=>array_map(function($k,$v){return array('name'=>ucwords(str_replace('_',' ',$k)),'value'=>$v);},array_keys($s),array_values($s)));$interactions=$wpdb->get_results($wpdb->prepare('SELECT video_id,interaction,created_at,updated_at FROM '.VWLB_Helpers::table('interactions').' WHERE user_id=%d ORDER BY id LIMIT %d OFFSET %d',$user->ID,$limit,$offset),ARRAY_A);foreach($interactions as $i)$data[]=array('group_id'=>'vwlb-interactions','group_label'=>__('Video interactions',VWLB_TEXT_DOMAIN),'item_id'=>'interaction-'.$i['video_id'].'-'.$i['interaction'],'data'=>array(array('name'=>'Video ID','value'=>$i['video_id']),array('name'=>'Interaction','value'=>$i['interaction']),array('name'=>'Updated','value'=>$i['updated_at'])));return array('data'=>$data,'done'=>count($sessions)<$limit&&count($interactions)<$limit);}
	public function erase($email,$page=1){$user=get_user_by('email',$email);if(!$user)return array('items_removed'=>false,'items_retained'=>false,'messages'=>array(),'done'=>true);global $wpdb;$removed=false;$affected=$wpdb->get_col($wpdb->prepare('SELECT DISTINCT video_id FROM '.VWLB_Helpers::table('interactions').' WHERE user_id=%d',$user->ID));foreach(array('playback_sessions','interactions') as $table){$result=$wpdb->delete(VWLB_Helpers::table($table),array('user_id'=>$user->ID));$removed=$removed||$result>0;}foreach($affected as $video_id){foreach(array('like','dislike') as $type){$count=(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.VWLB_Helpers::table('interactions').' WHERE video_id=%d AND interaction=%s',$video_id,$type));$wpdb->update(VWLB_Helpers::table('videos'),array($type.'_count'=>$count),array('id'=>$video_id));}}$wpdb->update(VWLB_Helpers::table('moderation'),array('reporter_id'=>0,'note'=>'[anonymized by privacy erasure]'),array('reporter_id'=>$user->ID));$wpdb->update(VWLB_Helpers::table('audit'),array('actor_id'=>0),array('actor_id'=>$user->ID));VWLB_Helpers::audit('privacy',$user->ID,'erase','','complete','Eligible private File 10 data erased; retained safety audit anonymized');return array('items_removed'=>$removed,'items_retained'=>true,'messages'=>array(__('Safety, copyright and audit records were anonymized where retention was required.',VWLB_TEXT_DOMAIN)),'done'=>true);}
	public function private_headers(){if(is_page(array_values((array)get_option('vwlb_page_map',array())))&&(is_user_logged_in()||is_page('video-history')||is_page('studio-video')||is_page('studio-live')))VWLB_Helpers::no_cache_private();}
}
