<?php
/** R64: durable retry/reconciliation guard for external video-intelligence suggestion effects. */
defined( 'ABSPATH' ) || exit;
final class VWLB_R64_Intelligence_Guard {
	private static $active=array();
	private static $shutdown=false;
	public static function register(){add_filter('rest_request_before_callbacks',array(__CLASS__,'before'),7,3);add_filter('rest_request_after_callbacks',array(__CLASS__,'after'),8,3);}
	private static function route($request){return $request instanceof WP_REST_Request&&'POST'===strtoupper((string)$request->get_method())&&preg_match('#/(?:video-wall-live-broadcasting/v1|vwlb/v1)/videos/[^/]+/intelligence/suggest$#',(string)$request->get_route());}
	private static function actor(){return get_current_user_id()?'u'.get_current_user_id():'a'.substr(VWLB_Helpers::ip_hash(),0,32);}
	private static function hash($request){$query=$request->get_query_params();if(is_array($query))ksort($query);return hash('sha256',strtoupper((string)$request->get_method()).'|'.$request->get_route().'|'.VWLB_Helpers::json_encode($query).'|'.hash('sha256',(string)$request->get_body()));}
	private static function option($request,$key){return VWLB_R60_Final_Hardening::EXTERNAL_GUARD_PREFIX.hash('sha256',$request->get_route().'|'.self::actor().'|'.$key);}
	private static function persist_reconcile($ctx,$reason){$record=$ctx['record'];$record['status']='reconcile_required';$record['reason']=sanitize_key($reason);$record['updated_at']=VWLB_Helpers::now();$saved=update_option($ctx['option'],$record,false);if(!$saved&&get_option($ctx['option'],null)!==$record){do_action('vwlb_operational_failure','external_effect','vwlb_external_guard_update_failed',array('guard_id'=>$record['guard_id']??''));return false;}do_action('vwlb_operational_failure','external_effect','vwlb_external_reconcile_required',array('guard_id'=>$record['guard_id']??'','route'=>$record['route']??'','reason'=>$record['reason']));return true;}
	public static function before($response,$handler,$request){
		if(null!==$response||!self::route($request))return $response;$key=VWLB_Helpers::text($request->get_header('Idempotency-Key'),128);if(!$key)return $response;$option=self::option($request,$key);$hash=self::hash($request);$existing=get_option($option,false);
		if(is_array($existing)){if(!hash_equals((string)($existing['request_hash']??''),$hash))return VWLB_Helpers::error('vwlb_external_guard_conflict',__('This idempotency key is bound to a different external-effect request.',VWLB_TEXT_DOMAIN),409,array('guard_id'=>$existing['guard_id']??''));return VWLB_Helpers::error('vwlb_external_reconcile_required',__('A previous video-intelligence processor attempt has an unverified external outcome. Reconcile it before retrying this key.',VWLB_TEXT_DOMAIN),503,array('guard_id'=>$existing['guard_id']??'','reconcile_required'=>true));}
		$record=array('guard_id'=>VWLB_Helpers::public_id('reconcile'),'status'=>'processing','request_hash'=>$hash,'route'=>VWLB_Helpers::text($request->get_route(),191),'actor'=>self::actor(),'created_at'=>VWLB_Helpers::now(),'updated_at'=>VWLB_Helpers::now());if(!add_option($option,$record,'',false)){return VWLB_Helpers::error('vwlb_external_guard_persist_failed',__('Video-intelligence retry protection could not be persisted safely.',VWLB_TEXT_DOMAIN),503);}self::$active[spl_object_hash($request)]=array('option'=>$option,'record'=>$record);if(!self::$shutdown){register_shutdown_function(array(__CLASS__,'shutdown'));self::$shutdown=true;}return $response;
	}
	public static function after($response,$handler,$request){$hash=spl_object_hash($request);if(empty(self::$active[$hash]))return $response;$ctx=self::$active[$hash];unset(self::$active[$hash]);$uncertain=is_wp_error($response)&&in_array($response->get_error_code(),array('vwlb_video_intelligence_processor_exception'),true);if($uncertain){self::persist_reconcile($ctx,$response->get_error_code());$data=(array)$response->get_error_data();$data['guard_id']=$ctx['record']['guard_id'];$data['reconcile_required']=true;$response->add_data($data,$response->get_error_code());return $response;}$deleted=delete_option($ctx['option']);if(!$deleted&&false!==get_option($ctx['option'],false)){self::persist_reconcile($ctx,'guard_release_failed');return VWLB_Helpers::error('vwlb_external_guard_release_failed',__('Video-intelligence operation finished but its retry guard could not be released safely. Reconciliation is required.',VWLB_TEXT_DOMAIN),503,array('guard_id'=>$ctx['record']['guard_id'],'reconcile_required'=>true));}return $response;}
	public static function shutdown(){foreach(self::$active as $ctx)self::persist_reconcile($ctx,'request_terminated_before_completion');self::$active=array();}
}
