<?php
/** Public-only VideoObject/BroadcastEvent structured data. */
defined( 'ABSPATH' ) || exit;
final class VWLB_SEO {
	public function output(){
		if(get_query_var('vwlb_video_id')){$video=VWLB_Repository::video_bundle(get_query_var('vwlb_video_id'));if(!$video||'published'!==($video['status']??'')||'public'!==($video['visibility']??''))return;$dto=VWLB_Repository::public_video_dto($video);if(!$dto)return;$data=array('@context'=>'https://schema.org','@type'=>'VideoObject','name'=>$dto['title'],'description'=>wp_strip_all_tags($dto['description']),'uploadDate'=>$dto['published_at'],'duration'=>'PT'.(int)$dto['duration_seconds'].'S','url'=>$dto['url']);if(!empty($dto['thumbnail_url']))$data['thumbnailUrl']=array($dto['thumbnail_url']);if($video['provider']!=='local'&&!empty($video['embed_url']))$data['embedUrl']=$video['embed_url'];$public_content=apply_filters('vwlb_public_seo_content_url','',$video);if($public_content)$data['contentUrl']=esc_url_raw($public_content,array('https'));$this->script($data);}
		elseif(get_query_var('vwlb_live_id')){$raw=VWLB_Repository::find('live_events',get_query_var('vwlb_live_id'));if(!$raw||'public'!==($raw['visibility']??'')||!in_array($raw['status']??'',array('scheduled','live','ended','replay_published'),true))return;$event=VWLB_Live::state($raw['public_id']);if(is_wp_error($event))return;$status='live'===$event['status']?'https://schema.org/EventInProgress':('ended'===$event['status']||'replay_published'===$event['status']?'https://schema.org/EventCompleted':'https://schema.org/EventScheduled');$data=array('@context'=>'https://schema.org','@type'=>'BroadcastEvent','name'=>$event['title'],'description'=>wp_strip_all_tags($event['description']),'startDate'=>$event['scheduled_start'],'endDate'=>$event['scheduled_end'],'eventStatus'=>$status,'url'=>$event['url']);if('live'===$event['status'])$data['isLiveBroadcast']=true;$this->script($data);}
	}
	private function script($data){echo '<script type="application/ld+json">'.wp_json_encode(array_filter($data),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE).'</script>' . "\n";}
}
