<?php
/**
 * Fail-closed provider/AI orchestration for the File 10 Future 24 layer.
 * External services are processors only; returned material is mapped back to File 10
 * canonical IDs and remains review-gated where content/medical/rights meaning exists.
 */
defined( 'ABSPATH' ) || exit;

final class VWLB_Future_Adapters {
	private static function event( $id ) { return VWLB_Repository::find( 'live_events', $id ); }
	private static function video( $id ) { return VWLB_Repository::find( 'videos', $id ); }
	private static function future_row( $table, $public_id ) { global $wpdb; $t=VWLB_Helpers::table($table); return $wpdb->get_row($wpdb->prepare("SELECT * FROM $t WHERE public_id=%s LIMIT 1",VWLB_Helpers::text($public_id,64)),ARRAY_A); }
	private static function future_row_by_id( $table, $id ) { global $wpdb; $t=VWLB_Helpers::table($table); return $wpdb->get_row($wpdb->prepare("SELECT * FROM $t WHERE id=%d LIMIT 1",absint($id)),ARRAY_A); }

	private static function safe_processor_context($object_type,$object){
		if(!is_array($object))return array();$base=array('object_type'=>$object_type,'public_id'=>VWLB_Helpers::text($object['public_id']??'',80),'language'=>VWLB_Helpers::text($object['language']??'',32));if('video'===$object_type){$base['duration_seconds']=max(0,(int)($object['duration_seconds']??0));$base['topics']=VWLB_Helpers::json($object['topics_json']??'[]');}else{$base['status']=VWLB_Helpers::enum($object['status']??'',VWLB_Contracts::LIVE_STATES,'');}return $base;
	}
	private static function safe_processor_options($options,$object_type,$object){try{$safe=(array)apply_filters('vwlb_media_track_generation_safe_options',array(),(array)$options,$object_type,self::safe_processor_context($object_type,$object));}catch(Throwable $e){return VWLB_Helpers::error('vwlb_processor_options_failed',__('Processor options could not be prepared safely.',VWLB_TEXT_DOMAIN),503,array('exception'=>get_class($e)));}$encoded=VWLB_Helpers::json_encode($safe);if(strlen($encoded)>16384)return VWLB_Helpers::error('vwlb_processor_options_too_large',__('Processor options are too large.',VWLB_TEXT_DOMAIN),422);$deny=function($v)use(&$deny){if(!is_array($v))return false;foreach($v as $k=>$child){$key=sanitize_key((string)$k);if(!str_ends_with($key,'_ref')&&in_array($key,array('secret','password','api_key','access_token','refresh_token','private_key','token','stream_key'),true))return true;if(is_array($child)&&$deny($child))return true;}return false;};if($deny($safe))return VWLB_Helpers::error('vwlb_processor_secret_forbidden',__('Raw credentials cannot be sent in processor options.',VWLB_TEXT_DOMAIN),422);return $safe;}
	private static function config( $event_id ) {
		global $wpdb;
		return $wpdb->get_row( $wpdb->prepare( 'SELECT * FROM ' . VWLB_Helpers::table('future_live_config') . ' WHERE live_event_id=%d', absint($event_id) ), ARRAY_A );
	}

	/** F10-FUT-004/005/006/008 — apply saved DVR/latency/ingest/redundancy policy to an adapter. */
	public static function apply_live_policy( $live_id ) {
		$event=self::event($live_id);if(!$event||!VWLB_Security::can(VWLB_Contracts::CAP_OPERATE,$event,'future_apply_live_policy'))return VWLB_Helpers::error('vwlb_forbidden',__('You cannot apply this live-provider policy.',VWLB_TEXT_DOMAIN),403);
		$config=self::config($event['id']);if(!$config)return VWLB_Helpers::error('vwlb_future_config_missing',__('Future live configuration is not set.',VWLB_TEXT_DOMAIN),409);
		$payload=array('event_public_id'=>$event['public_id'],'provider'=>$event['provider'],'latency_mode'=>$config['latency_mode'],'dvr_window_seconds'=>(int)$config['dvr_window_seconds'],'backup_provider'=>$config['backup_provider'],'redundant_recording'=>(bool)$config['redundant_recording'],'protocols'=>VWLB_Helpers::json($config['protocols_json']),'translation_languages'=>VWLB_Helpers::json($config['translation_languages_json']));
		try{$result=apply_filters('vwlb_provider_apply_future_live_policy',null,$event,$payload);}catch(Throwable $e){do_action('vwlb_operational_failure','provider','vwlb_provider_future_policy_exception',array('live_public_id'=>$event['public_id'],'provider'=>$event['provider'],'exception'=>get_class($e)));return VWLB_Helpers::error('vwlb_provider_future_policy_reconcile_required',__('The provider policy operation ended with an unverified provider outcome. Reconciliation is required before retry.',VWLB_TEXT_DOMAIN),503,array('provider'=>$event['provider'],'reconcile_required'=>true));}
		if(!is_array($result)||empty($result['accepted']))return VWLB_Helpers::error('vwlb_provider_future_policy_unavailable',__('The configured provider adapter cannot apply this live policy.',VWLB_TEXT_DOMAIN),503,array('provider'=>$event['provider']));
		$safe=array('accepted'=>true,'provider'=>$event['provider'],'mode'=>VWLB_Helpers::enum($result['mode']??$config['latency_mode'],array('standard','low','ultra_low'),$config['latency_mode']),'dvr_window_seconds'=>max(0,min(6*HOUR_IN_SECONDS,(int)($result['dvr_window_seconds']??$config['dvr_window_seconds']))),'protocol'=>VWLB_Helpers::enum($result['protocol']??'',array('rtmp','srt','webrtc'),''),'backup_ready'=>!empty($result['backup_ready']),'recording_redundant'=>!empty($result['recording_redundant']));
		VWLB_Helpers::audit('live',$event['id'],'future_provider_policy_applied',$event['status'],$event['status'],'',array('provider'=>$event['provider'],'result'=>$safe));
		return $safe;
	}

	/** F10-FUT-007 — activate/deactivate one configured simulcast target through an adapter. */
	public static function transition_simulcast($live_id,$target_id,$action,$expected_version=0) {
		$event=self::event($live_id);if(!$event||!VWLB_Security::can(VWLB_Contracts::CAP_OPERATE,$event,'future_simulcast_transition'))return VWLB_Helpers::error('vwlb_forbidden',__('You cannot operate simulcast.',VWLB_TEXT_DOMAIN),403);
		$target=self::future_row('simulcast_targets',$target_id);if(!$target||(int)$target['live_event_id']!==(int)$event['id'])return VWLB_Helpers::error('vwlb_simulcast_missing',__('Simulcast target not found.',VWLB_TEXT_DOMAIN),404);$action=VWLB_Helpers::enum($action,array('start','stop','retry'),'');if(!$action)return VWLB_Helpers::error('vwlb_simulcast_action_invalid',__('Simulcast action is invalid.',VWLB_TEXT_DOMAIN),422);if(!$expected_version||(int)$target['version']!==(int)$expected_version)return VWLB_Helpers::error('vwlb_version_conflict',__('Simulcast target changed. Refresh and submit its current version.',VWLB_TEXT_DOMAIN),409);if('transitioning'===$target['status'])return VWLB_Helpers::error('vwlb_simulcast_busy',__('Simulcast target is already changing state.',VWLB_TEXT_DOMAIN),409);
		global $wpdb;$table=VWLB_Helpers::table('simulcast_targets');$reserved=$wpdb->update($table,array('status'=>'transitioning','version'=>(int)$target['version']+1,'updated_at'=>VWLB_Helpers::now()),array('id'=>$target['id'],'version'=>$target['version']));if(1!==$reserved)return VWLB_Helpers::error('vwlb_version_conflict',__('Simulcast target changed before the operation could start.',VWLB_TEXT_DOMAIN),409);$reserved_version=(int)$target['version']+1;
		try{$result=apply_filters('vwlb_simulcast_adapter_transition',null,$event,$target,$action,array('credential_ref'=>$target['credential_ref'],'provider_target_ref'=>$target['provider_target_ref']));}catch(Throwable $e){$state=array('status'=>'failed','provider_code'=>'exception','provider_outcome_unverified'=>true,'exception'=>get_class($e),'updated_at'=>gmdate('c'));$failed=$wpdb->update($table,array('status'=>'failed','version'=>$reserved_version+1,'last_state_json'=>VWLB_Helpers::json_encode($state),'updated_at'=>VWLB_Helpers::now()),array('id'=>$target['id'],'version'=>$reserved_version,'status'=>'transitioning'));do_action('vwlb_operational_failure','simulcast','vwlb_simulcast_adapter_exception',array('target_public_id'=>$target['public_id'],'local_failure_state_persisted'=>1===$failed,'exception'=>get_class($e)));return VWLB_Helpers::error('vwlb_simulcast_reconcile_required',__('The simulcast adapter ended unexpectedly and the provider outcome is unverified. Reconciliation is required.',VWLB_TEXT_DOMAIN),503,array('reconcile_required'=>true,'local_state'=>1===$failed?'failed':'transitioning'));}
		if(is_wp_error($result)){$failed=$wpdb->update($table,array('status'=>'failed','version'=>$reserved_version+1,'last_state_json'=>VWLB_Helpers::json_encode(array('status'=>'failed','provider_code'=>$result->get_error_code(),'updated_at'=>gmdate('c'))),'updated_at'=>VWLB_Helpers::now()),array('id'=>$target['id'],'version'=>$reserved_version,'status'=>'transitioning'));if(1!==$failed)return VWLB_Helpers::error('vwlb_simulcast_reconcile_required',__('The provider failed and local failure state could not be finalized; reconciliation is required.',VWLB_TEXT_DOMAIN),503,array('provider_code'=>$result->get_error_code()));return $result;}
		if(!is_array($result)||empty($result['accepted'])){$failed=$wpdb->update($table,array('status'=>'failed','version'=>$reserved_version+1,'last_state_json'=>VWLB_Helpers::json_encode(array('status'=>'failed','provider_code'=>'unavailable','updated_at'=>gmdate('c'))),'updated_at'=>VWLB_Helpers::now()),array('id'=>$target['id'],'version'=>$reserved_version,'status'=>'transitioning'));if(1!==$failed)return VWLB_Helpers::error('vwlb_simulcast_reconcile_required',__('The provider was unavailable and local failure state could not be finalized; reconciliation is required.',VWLB_TEXT_DOMAIN),503);return VWLB_Helpers::error('vwlb_simulcast_adapter_unavailable',__('Simulcast provider adapter is unavailable.',VWLB_TEXT_DOMAIN),503);}
		$default='stop'===$action?'ready':'active';$allowed='stop'===$action?array('ready','disabled'):array('active','degraded');$status=VWLB_Helpers::enum($result['status']??$default,$allowed,$default);$safe=array('status'=>$status,'provider_code'=>VWLB_Helpers::text($result['provider_code']??'',64),'message'=>VWLB_Helpers::text($result['message']??'',500),'updated_at'=>gmdate('c'));
		$ok=$wpdb->update($table,array('status'=>$status,'last_state_json'=>VWLB_Helpers::json_encode($safe),'version'=>$reserved_version+1,'updated_at'=>VWLB_Helpers::now()),array('id'=>$target['id'],'version'=>$reserved_version,'status'=>'transitioning'));if(1!==$ok)return VWLB_Helpers::error('vwlb_simulcast_reconcile_required',__('Provider accepted the action but local state could not be finalized; reconciliation is required.',VWLB_TEXT_DOMAIN),503);
		VWLB_Helpers::audit('live',$event['id'],'simulcast_'.$action,$event['status'],$event['status'],'',array('target_public_id'=>$target['public_id'],'result'=>$safe));return self::future_row_by_id('simulcast_targets',$target['id']);
	}

	/** F10-FUT-012/013/014/015 — request a processor-generated auxiliary track. */
	public static function request_track_generation( $object_type, $object_id, $track_type, $language='', $options=array() ) {
		$object_type=VWLB_Helpers::enum($object_type,array('video','live'),'');$track_type=VWLB_Helpers::enum($track_type,array('translation','dub','audio_description','sign_language'),'');if(!$object_type||!$track_type)return VWLB_Helpers::error('vwlb_track_type_invalid',__('Track generation type is invalid.',VWLB_TEXT_DOMAIN),422);
		$object='video'===$object_type?self::video($object_id):self::event($object_id);$cap='video'===$object_type?VWLB_Contracts::CAP_PUBLISH:VWLB_Contracts::CAP_BROADCAST;if(!$object||!VWLB_Security::can($cap,$object,'future_generate_track'))return VWLB_Helpers::error('vwlb_forbidden',__('You cannot request this media track.',VWLB_TEXT_DOMAIN),403);
		$safe_options=self::safe_processor_options($options,$object_type,$object);if(is_wp_error($safe_options))return $safe_options;$context=self::safe_processor_context($object_type,$object);$request=array('object_type'=>$object_type,'object_public_id'=>$object['public_id'],'track_type'=>$track_type,'language'=>VWLB_Helpers::text($language,32),'options'=>$safe_options,'require_human_review'=>true,'medical_interpretation_authority'=>false);
		try{$result=apply_filters('vwlb_media_track_generation_request',null,$request,$context);}catch(Throwable $e){do_action('vwlb_operational_failure','processor','vwlb_track_generation_exception',array('object_public_id'=>$object['public_id'],'exception'=>get_class($e)));return VWLB_Helpers::error('vwlb_track_generation_reconcile_required',__('The media-track processor ended unexpectedly and its external outcome is unverified. Reconciliation is required.',VWLB_TEXT_DOMAIN),503,array('reconcile_required'=>true));}
		if(!is_array($result)||empty($result['accepted']))return VWLB_Helpers::error('vwlb_track_generator_unavailable',__('No approved media-track processor is configured.',VWLB_TEXT_DOMAIN),503);
		$data=array('track_type'=>$track_type,'language'=>$request['language'],'source'=>!empty($result['ai_assisted'])?'ai_assisted':'provider','status'=>'candidate','file_ref'=>esc_url_raw($result['file_ref']??''),'provider_ref'=>VWLB_Helpers::text($result['provider_ref']??'',191),'metadata'=>array('request_ref'=>VWLB_Helpers::text($result['request_ref']??'',191),'processor'=>VWLB_Helpers::text($result['processor']??'',64),'human_review_required'=>true,'original_preserved'=>true));
		$track=VWLB_Future_Intelligence::create_track($object_type,$object['id'],$data);
		if(is_wp_error($track)){
			try{$cancel=apply_filters('vwlb_media_track_generation_cancel',null,array('request_ref'=>$data['metadata']['request_ref'],'provider_ref'=>$data['provider_ref'],'processor'=>$data['metadata']['processor']),$request,$context);}catch(Throwable $e){do_action('vwlb_operational_failure','processor','vwlb_track_generation_cancel_exception',array('object_public_id'=>$object['public_id'],'exception'=>get_class($e)));return VWLB_Helpers::error('vwlb_track_generation_reconcile_required',__('The processor accepted the request, local persistence failed, and cancellation could not be verified. Reconciliation is required.',VWLB_TEXT_DOMAIN),503,array('local_error'=>$track->get_error_code(),'reconcile_required'=>true));}
			if(!is_array($cancel)||empty($cancel['accepted']))return VWLB_Helpers::error('vwlb_track_generation_reconcile_required',__('The processor accepted the request but File 10 could not persist its candidate and cancellation was not confirmed. Reconciliation is required.',VWLB_TEXT_DOMAIN),503,array('local_error'=>$track->get_error_code()));
			return $track;
		}
		return $track;
	}

	/** F10-FUT-016/017/018/024 — request AI/knowledge suggestions, always candidate/reviewed later. */
	public static function suggest_annotations( $video_id, $kinds=array('key_moment') ) {
		$video=self::video($video_id);if(!$video||!VWLB_Security::can(VWLB_Contracts::CAP_PUBLISH,$video,'future_suggest_annotations'))return VWLB_Helpers::error('vwlb_forbidden',__('You cannot request suggestions for this video.',VWLB_TEXT_DOMAIN),403);
		$allowed=array('key_moment','citation','overlay','knowledge_bridge');$kinds=array_values(array_unique(array_intersect(array_map('sanitize_key',(array)$kinds),$allowed)));if(!$kinds)$kinds=array('key_moment');
		$context=self::safe_processor_context('video',$video);try{$result=apply_filters('vwlb_video_intelligence_suggestions',null,array('video_public_id'=>$video['public_id'],'kinds'=>$kinds,'require_sources'=>true,'auto_publish'=>false,'clinical_authority'=>false),$context);}catch(Throwable $e){do_action('vwlb_operational_failure','processor','vwlb_video_intelligence_exception',array('video_public_id'=>$video['public_id'],'exception'=>get_class($e)));return VWLB_Helpers::error('vwlb_video_intelligence_processor_exception',__('The video-intelligence processor ended unexpectedly.',VWLB_TEXT_DOMAIN),503,array('processor_outcome_unverified'=>true));}
		if(!is_array($result)||empty($result['accepted'])||!is_array($result['items']??null))return VWLB_Helpers::error('vwlb_video_intelligence_unavailable',__('No approved video-intelligence suggestion processor is configured.',VWLB_TEXT_DOMAIN),503);
		return VWLB_DB::transaction(function()use($result,$allowed,$kinds,$video){
			$created=array();
			foreach(array_slice($result['items'],0,100) as $item){
				if(!is_array($item))continue;$kind=VWLB_Helpers::enum($item['kind']??'', $allowed, '');if(!$kind||!in_array($kind,$kinds,true))continue;
				$data=array('kind'=>$kind,'source'=>'ai_assisted','start_ms'=>max(0,(int)($item['start_ms']??0)),'end_ms'=>max(0,(int)($item['end_ms']??0)),'title'=>VWLB_Helpers::text($item['title']??'',255),'body'=>VWLB_Helpers::textarea($item['body']??''),'source_owner'=>VWLB_Helpers::text($item['source_owner']??'',64),'source_ref'=>VWLB_Helpers::text($item['source_ref']??'',191),'metadata'=>array('processor'=>VWLB_Helpers::text($result['processor']??'',64),'confidence'=>isset($item['confidence'])?max(0,min(1,(float)$item['confidence'])):null,'human_review_required'=>true));
				$row=VWLB_Future_Intelligence::create_annotation($video['id'],$data);if(is_wp_error($row))return $row;$created[]=$row;
			}
			return array('accepted'=>true,'created_candidates'=>count($created),'items'=>$created);
		});
	}
}
