<?php
/** R70: fail-closed, lock-safe resumable upload completion and DB-readable upload session preflight. */
defined( 'ABSPATH' ) || exit;
final class VWLB_R70_Upload_Completion_Guard {
	public static function register(){add_filter('rest_request_before_callbacks',array(__CLASS__,'guard'),19,3);}
	private static function route_kind($request){
		if(!$request instanceof WP_REST_Request)return '';$method=strtoupper((string)$request->get_method());$route=(string)$request->get_route();
		foreach(VWLB_Contracts::namespaces() as $n){$q=preg_quote($n,'#');if('PUT'===$method&&preg_match('#^/'.$q.'/media/resumable/[A-Za-z0-9_-]+/chunk$#',$route))return 'chunk';if('POST'===$method&&preg_match('#^/'.$q.'/media/resumable/[A-Za-z0-9_-]+/complete$#',$route))return 'complete';}
		return '';
	}
	private static function session($id){global $wpdb;$table=VWLB_Helpers::table('upload_sessions');$wpdb->last_error='';$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$table} WHERE public_id=%s LIMIT 1",VWLB_Helpers::text($id,64)),ARRAY_A);if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_upload_session_unreadable',__('Upload session state could not be verified safely.',VWLB_TEXT_DOMAIN),503);return $row;}
	private static function token($request){$token=VWLB_Helpers::text($request->get_header('X-VWLB-Upload-Token'),200);if($token)return $token;$json=$request->get_json_params();return is_array($json)?VWLB_Helpers::text($json['upload_token']??'',200):'';}
	private static function authorize($session,$token){if(!$session||'active'!==($session['status']??'')||strtotime(($session['expires_at']??'').' UTC')<=time())return VWLB_Helpers::error('vwlb_upload_session_expired',__('The upload session is unavailable or expired.',VWLB_TEXT_DOMAIN),410);if((int)$session['owner_id']!==get_current_user_id()||!VWLB_Security::can(VWLB_Contracts::CAP_SUBMIT,null,'write_upload_chunk'))return VWLB_Helpers::error('vwlb_not_found',__('Upload session not found.',VWLB_TEXT_DOMAIN),404);if(!$token||!password_verify((string)$token,(string)$session['token_hash']))return VWLB_Helpers::error('vwlb_upload_token_invalid',__('Upload token is invalid.',VWLB_TEXT_DOMAIN),401);return true;}
	private static function path($session){$base=trailingslashit(WP_CONTENT_DIR).VWLB_Extensions::PRIVATE_DIR;if(is_link($base)||!is_dir($base))return VWLB_Helpers::error('vwlb_private_storage_unavailable',__('Private media storage is unavailable.',VWLB_TEXT_DOMAIN),503);$real_base=realpath($base);$real_content=realpath(WP_CONTENT_DIR);if(!$real_base||!$real_content||0!==strpos($real_base,$real_content.DIRECTORY_SEPARATOR))return VWLB_Helpers::error('vwlb_private_storage_root_escape',__('Private media storage escaped the approved content boundary.',VWLB_TEXT_DOMAIN),503);$name=sanitize_file_name(basename((string)($session['private_filename']??'')));if(!$name||!str_ends_with($name,'.part'))return VWLB_Helpers::error('vwlb_private_filename_invalid',__('Private upload path is invalid.',VWLB_TEXT_DOMAIN),500);$path=trailingslashit($real_base).$name;if(is_link($path)||!is_file($path))return VWLB_Helpers::error('vwlb_upload_missing',__('The private upload file is missing or unsafe.',VWLB_TEXT_DOMAIN),410);return $path;}
	public static function guard($response,$handler,$request){
		if(null!==$response)return $response;$kind=self::route_kind($request);if(!$kind)return $response;$session=self::session($request['id']);if(is_wp_error($session))return $session;if(!$session)return $response;
		$auth=self::authorize($session,self::token($request));if(is_wp_error($auth))return $auth;if('chunk'===$kind)return $response;
		if((int)$session['received_bytes']!==(int)$session['expected_bytes'])return $response;$path=self::path($session);if(is_wp_error($path))return $path;$fp=@fopen($path,'rb');if(!$fp)return VWLB_Helpers::error('vwlb_private_storage_unavailable',__('Private upload file could not be opened safely.',VWLB_TEXT_DOMAIN),503);if(!flock($fp,LOCK_EX)){fclose($fp);return VWLB_Helpers::error('vwlb_upload_lock_failed',__('Upload completion is busy. Retry safely.',VWLB_TEXT_DOMAIN),409);}clearstatcache(true,$path);$size=filesize($path);if(false===$size||(int)$size!==(int)$session['expected_bytes']){flock($fp,LOCK_UN);fclose($fp);return VWLB_Helpers::error('vwlb_upload_storage_offset_conflict',__('Stored upload size does not match durable session state.',VWLB_TEXT_DOMAIN),409,array('expected_bytes'=>(int)$session['expected_bytes'],'stored_bytes'=>false===$size?null:(int)$size));}$sha=hash_file('sha256',$path);if(!is_string($sha)||!preg_match('/^[a-f0-9]{64}$/',$sha)){flock($fp,LOCK_UN);fclose($fp);return VWLB_Helpers::error('vwlb_upload_checksum_unreadable',__('Completed upload checksum could not be verified safely.',VWLB_TEXT_DOMAIN),503);}global $wpdb;$wpdb->last_error='';$result=VWLB_Extensions::complete_resumable($request['id'],self::token($request));$db_error=(string)$wpdb->last_error;flock($fp,LOCK_UN);fclose($fp);if(''!== $db_error)return VWLB_Helpers::error('vwlb_upload_completion_unverifiable',__('Upload completion database state became unreadable; retry only after verification.',VWLB_TEXT_DOMAIN),503);return $result;
	}
}
