<?php
/** R77: bounded live-poll work and option metadata alignment. */
defined( 'ABSPATH' ) || exit;
final class VWLB_R77_Poll_Integrity {
	const MAX_OPTIONS=20;
	public static function register(){add_filter('rest_request_before_callbacks',array(__CLASS__,'guard'),22,3);}
	private static function route($request,$kind){if(!$request instanceof WP_REST_Request||'POST'!==strtoupper((string)$request->get_method()))return false;$route=(string)$request->get_route();foreach(VWLB_Contracts::namespaces() as $n){$q=preg_quote($n,'#');if('create'===$kind&&preg_match('#^/'.$q.'/live-events/([A-Za-z0-9_-]+)/polls$#',$route))return true;if('answer'===$kind&&preg_match('#^/'.$q.'/live-polls/([A-Za-z0-9_-]+)/answers$#',$route))return true;}return false;}
	private static function normalized_options($raw){$out=array();foreach((array)$raw as $item){$a=is_array($item)?$item:array('text'=>$item);$text=VWLB_Helpers::text($a['text']??'',255);if(!$text)continue;$out[]=array('text'=>$text,'is_correct'=>!empty($a['is_correct']));if(count($out)>self::MAX_OPTIONS)return VWLB_Helpers::error('vwlb_poll_option_limit',__('A live poll may contain at most 20 non-empty options.',VWLB_TEXT_DOMAIN),422);}return $out;}
	private static function create($request){$data=$request->get_json_params();$data=is_array($data)?$data:array();$event=VWLB_Repository::find('live_events',$request['id']);if(!$event||!VWLB_Security::can(VWLB_Contracts::CAP_BROADCAST,$event,'future_live_poll'))return VWLB_Helpers::error('vwlb_forbidden',__('You cannot create this poll.',VWLB_TEXT_DOMAIN),403);$q=VWLB_Helpers::textarea($data['question']??'');$options=self::normalized_options($data['options']??array());if(is_wp_error($options))return $options;if(!$q||count($options)<2)return VWLB_Helpers::error('vwlb_poll_fields_required',__('A question and at least two options are required.',VWLB_TEXT_DOMAIN),422);$tz=$data['timezone']??'UTC';$opens=!empty($data['opens_at'])?VWLB_Helpers::datetime_in_timezone($data['opens_at'],$tz):null;$closes=!empty($data['closes_at'])?VWLB_Helpers::datetime_in_timezone($data['closes_at'],$tz):null;if((!empty($data['opens_at'])&&!$opens)||(!empty($data['closes_at'])&&!$closes)||($opens&&$closes&&strtotime($closes.' UTC')<=strtotime($opens.' UTC')))return VWLB_Helpers::error('vwlb_poll_time_invalid',__('Poll opening and closing times are invalid.',VWLB_TEXT_DOMAIN),422);global $wpdb;$now=VWLB_Helpers::now();return VWLB_DB::transaction(function()use($wpdb,$event,$data,$q,$options,$now,$opens,$closes){$public=VWLB_Helpers::public_id('poll');$saved=$wpdb->insert(VWLB_Helpers::table('live_polls'),array('public_id'=>$public,'live_event_id'=>$event['id'],'question'=>$q,'poll_type'=>VWLB_Helpers::enum($data['poll_type']??'single',array('single','multiple','knowledge_check'),'single'),'status'=>VWLB_Helpers::enum($data['status']??'draft',array('draft','open','closed','removed'),'draft'),'opens_at'=>$opens,'closes_at'=>$closes,'metadata_json'=>VWLB_Helpers::json_encode(array('educational_only'=>true,'not_diagnostic'=>true)),'version'=>1,'created_by'=>get_current_user_id(),'created_at'=>$now,'updated_at'=>$now));if(!$saved||!$wpdb->insert_id)return VWLB_Helpers::error('vwlb_database_error',__('Poll could not be saved.',VWLB_TEXT_DOMAIN),500);$poll_id=(int)$wpdb->insert_id;foreach($options as $idx=>$option){$ok=$wpdb->insert(VWLB_Helpers::table('live_poll_options'),array('poll_id'=>$poll_id,'public_id'=>VWLB_Helpers::public_id('opt'),'option_text'=>$option['text'],'is_correct'=>$option['is_correct']?1:0,'sort_order'=>$idx));if(!$ok)return VWLB_Helpers::error('vwlb_database_error',__('Poll option could not be saved.',VWLB_TEXT_DOMAIN),500);}VWLB_Helpers::audit('live_poll',$poll_id,'create','','',$q,array('live_event_id'=>$event['id']));VWLB_Helpers::outbox('LivePollChanged','live',$event['id'],array('poll_public_id'=>$public));return VWLB_Future_Intelligence::poll($public,true);});}
	public static function guard($response,$handler,$request){if(null!==$response)return $response;if(self::route($request,'create')){return self::create($request);}if(self::route($request,'answer')){$d=$request->get_json_params();$ids=is_array($d)?(array)($d['option_ids']??array()):array();if(count($ids)>self::MAX_OPTIONS)return VWLB_Helpers::error('vwlb_poll_option_limit',__('A poll response contains too many option identifiers.',VWLB_TEXT_DOMAIN),422);}return $response;}
}
