<?php
/** Public/private File 10 experiences: mobile-first, keyboard-first, RTL-safe and no autoplay by default. */
defined( 'ABSPATH' ) || exit;
final class VWLB_Frontend {
	public function register(){
		add_shortcode('vwlb_wall',array($this,'wall'));add_shortcode('vwlb_video',array($this,'video'));add_shortcode('vwlb_live',array($this,'live'));
		add_shortcode('vwlb_channel',array($this,'channel'));add_shortcode('vwlb_studio_video',array($this,'studio_video'));add_shortcode('vwlb_studio_live',array($this,'studio_live'));
		add_shortcode('vwlb_history',array($this,'history'));add_shortcode('vwlb_podcasts',array($this,'podcasts'));add_shortcode('vwlb_podcast',array($this,'podcast'));
	}
	public function assets(){
		wp_register_style('vwlb',VWLB_URL.'assets/css/vwlb.css',array(),VWLB_VERSION);
		wp_register_script('vwlb',VWLB_URL.'assets/js/vwlb.js',array(),VWLB_VERSION,true);
		wp_localize_script('vwlb','VWLB',array(
			'root'=>esc_url_raw(rest_url(VWLB_Contracts::CANONICAL_API_NAMESPACE)),
			'compatRoot'=>esc_url_raw(rest_url(VWLB_Contracts::API_NAMESPACE)),'nonce'=>wp_create_nonce('wp_rest'),
			'locale'=>determine_locale(),'dir'=>is_rtl()?'rtl':'ltr',
			'i18n'=>array('error'=>__('Something went wrong. Please retry.',VWLB_TEXT_DOMAIN),'saved'=>__('Saved.',VWLB_TEXT_DOMAIN),'startingSoon'=>__('Starting soon',VWLB_TEXT_DOMAIN),'lowBandwidth'=>__('Low bandwidth mode',VWLB_TEXT_DOMAIN),'sessionRest'=>__('You have been watching for a while. Consider a short rest.',VWLB_TEXT_DOMAIN))
		));
	}
	private function enqueue(){wp_enqueue_style('vwlb');wp_enqueue_script('vwlb');}
	private function nav(){return '<nav class="vwlb-local-nav" aria-label="'.esc_attr__('Page navigation',VWLB_TEXT_DOMAIN).'"><button type="button" data-vwlb-back>'.esc_html__('Back',VWLB_TEXT_DOMAIN).'</button><a href="'.esc_url(home_url('/')).'">'.esc_html__('Home',VWLB_TEXT_DOMAIN).'</a></nav>';}
	public function wall($atts=array()){
		$this->enqueue();$data=VWLB_Repository::browse_videos(array('per_page'=>12));
		global $wpdb;$lives=$wpdb->get_results("SELECT public_id,title,scheduled_start,status FROM ".VWLB_Helpers::table('live_events')." WHERE visibility='public' AND status IN ('scheduled','live') AND deleted_at IS NULL ORDER BY scheduled_start ASC LIMIT 8",ARRAY_A);
		ob_start();?><main class="vwlb-shell" aria-labelledby="vwlb-wall-title"><?php echo $this->nav();?><header class="vwlb-hero"><h1 id="vwlb-wall-title"><?php esc_html_e('Video Wall',VWLB_TEXT_DOMAIN);?></h1><p><?php esc_html_e('Verified educational videos, podcasts and live broadcasts.',VWLB_TEXT_DOMAIN);?></p></header>
		<?php if($lives):?><section aria-labelledby="vwlb-live-now"><h2 id="vwlb-live-now"><?php esc_html_e('Live and upcoming',VWLB_TEXT_DOMAIN);?></h2><div class="vwlb-grid" role="list"><?php foreach($lives as $l):?><article class="vwlb-card" role="listitem"><a href="<?php echo esc_url(home_url('/live/'.$l['public_id'].'/'));?>"><h3><?php echo esc_html($l['title']);?></h3><span class="vwlb-meta"><?php echo esc_html('live'===$l['status']?__('Live now',VWLB_TEXT_DOMAIN):get_date_from_gmt($l['scheduled_start'],get_option('date_format').' '.get_option('time_format')));?></span></a></article><?php endforeach;?></div></section><?php endif;?>
		<section aria-labelledby="vwlb-recorded"><h2 id="vwlb-recorded"><?php esc_html_e('Recorded videos',VWLB_TEXT_DOMAIN);?></h2><div class="vwlb-grid" role="list"><?php if(empty($data['items'])):?><section class="vwlb-empty" role="status"><h3><?php esc_html_e('No public videos yet',VWLB_TEXT_DOMAIN);?></h3><p><?php esc_html_e('Approved videos will appear here after review.',VWLB_TEXT_DOMAIN);?></p></section><?php else:foreach($data['items'] as $item):?><article class="vwlb-card" role="listitem"><a href="<?php echo esc_url($item['url']);?>"><div class="vwlb-thumb"><?php if($item['thumbnail_id']):echo wp_get_attachment_image($item['thumbnail_id'],'medium_large',false,array('loading'=>'lazy'));else:?><span aria-hidden="true">▶</span><?php endif;?></div><h3><?php echo esc_html($item['title']);?></h3><p><?php echo esc_html($item['excerpt']);?></p><span class="vwlb-meta"><?php echo esc_html(gmdate('H:i:s',(int)$item['duration_seconds']));?></span></a></article><?php endforeach;endif;?></div></section></main><?php return ob_get_clean();
	}
	public function video(){
		VWLB_Helpers::no_cache_private();$this->enqueue();$id=get_query_var('vwlb_video_id');if(!$id&&isset($_GET['video']))$id=sanitize_text_field(wp_unslash($_GET['video']));
		$payload=$id?VWLB_Videos::playback($id):null;if(is_wp_error($payload)||!$payload)return $this->state('restricted',__('Video unavailable',VWLB_TEXT_DOMAIN),__('The video is unavailable or you do not have access.',VWLB_TEXT_DOMAIN));
		$v=$payload['video'];$p=$payload['playback'];$chapters=VWLB_Extensions::chapters('video',$v['id']);
		ob_start();?><main class="vwlb-shell vwlb-player-page" data-vwlb-video="<?php echo esc_attr($v['public_id']);?>" data-vwlb-session-minutes="45"><?php echo $this->nav();?><article><h1><?php echo esc_html($v['title']);?></h1>
		<div class="vwlb-player-tools" role="group" aria-label="<?php esc_attr_e('Playback preferences',VWLB_TEXT_DOMAIN);?>"><button type="button" data-vwlb-bandwidth aria-pressed="false"><?php esc_html_e('Low bandwidth mode',VWLB_TEXT_DOMAIN);?></button><button type="button" data-vwlb-transcript-toggle aria-expanded="false"><?php esc_html_e('Transcript',VWLB_TEXT_DOMAIN);?></button></div>
		<?php if('iframe'===$p['type']):?><div class="vwlb-player-frame"><iframe src="<?php echo esc_url($p['url']);?>" title="<?php echo esc_attr($v['title']);?>" loading="lazy" allow="fullscreen; picture-in-picture" sandbox="<?php echo esc_attr($p['sandbox']);?>" allowfullscreen></iframe></div><?php else:?><video class="vwlb-player" controls playsinline preload="metadata" src="<?php echo esc_url($p['url']);?>" data-resume="<?php echo esc_attr($payload['session']['resume_seconds']??0);?>" data-no-autoplay="1"><?php foreach($v['captions'] as $c):?><track kind="<?php echo esc_attr('captions'===$c['kind']?'captions':'subtitles');?>" srclang="<?php echo esc_attr($c['language']);?>" label="<?php echo esc_attr($c['language']);?>" src="<?php echo esc_url(rest_url(VWLB_Contracts::CANONICAL_API_NAMESPACE.'/captions/'.$c['public_id']));?>"><?php endforeach;?><?php esc_html_e('Your browser does not support video playback.',VWLB_TEXT_DOMAIN);?></video><?php endif;?>
		<?php if($chapters):?><nav class="vwlb-chapters" aria-label="<?php esc_attr_e('Video chapters',VWLB_TEXT_DOMAIN);?>"><h2><?php esc_html_e('Chapters',VWLB_TEXT_DOMAIN);?></h2><ol><?php foreach($chapters as $c):?><li><button type="button" data-vwlb-seek="<?php echo esc_attr($c['start_seconds']);?>"><span><?php echo esc_html(gmdate('H:i:s',(int)$c['start_seconds']));?></span> <?php echo esc_html($c['title']);?></button></li><?php endforeach;?></ol></nav><?php endif;?>
		<section class="vwlb-transcript" hidden data-vwlb-transcript><h2><?php esc_html_e('Transcript',VWLB_TEXT_DOMAIN);?></h2><p><?php esc_html_e('Choose an available transcript/caption track in the player. Reviewed text tracks remain the authoritative accessible alternative.',VWLB_TEXT_DOMAIN);?></p></section>
		<div class="vwlb-actions" role="group" aria-label="<?php esc_attr_e('Video actions',VWLB_TEXT_DOMAIN);?>"><button type="button" data-vwlb-action="like" aria-pressed="false">👍 <?php esc_html_e('Like',VWLB_TEXT_DOMAIN);?></button><button type="button" data-vwlb-action="dislike" aria-pressed="false">👎 <?php esc_html_e('Dislike',VWLB_TEXT_DOMAIN);?></button><button type="button" data-vwlb-action="save" aria-pressed="false">🔖 <?php esc_html_e('Save',VWLB_TEXT_DOMAIN);?></button></div>
		<div class="vwlb-status" role="status" aria-live="polite"></div><div class="vwlb-description"><?php echo wp_kses_post(wpautop($v['description']));?></div></article></main><?php return ob_get_clean();
	}
	public function live(){
		VWLB_Helpers::no_cache_private();$this->enqueue();$id=get_query_var('vwlb_live_id');if(!$id&&isset($_GET['live']))$id=sanitize_text_field(wp_unslash($_GET['live']));
		$event=$id?VWLB_Live::state($id):null;if(is_wp_error($event)||!$event)return $this->state('restricted',__('Live event unavailable',VWLB_TEXT_DOMAIN),__('The event is unavailable or restricted.',VWLB_TEXT_DOMAIN));
		$raw=VWLB_Repository::find('live_events',$id);$extras=VWLB_Extensions::live_extras($raw);
		ob_start();?><main class="vwlb-shell" data-vwlb-live="<?php echo esc_attr($event['public_id']);?>"><?php echo $this->nav();?><h1><?php echo esc_html($event['title']);?></h1><div class="vwlb-live-state" role="status" aria-live="polite"><strong><?php echo esc_html(ucwords(str_replace('_',' ',$event['status'])));?></strong><?php if('scheduled'===$event['status']):?><time datetime="<?php echo esc_attr($event['scheduled_start']);?>" data-vwlb-countdown><?php echo esc_html(get_date_from_gmt($event['scheduled_start'],get_option('date_format').' '.get_option('time_format')));?></time><?php endif;?></div>
		<?php if(!empty($event['provider_degraded'])):?><div class="vwlb-warning" role="alert"><?php esc_html_e('The streaming provider is degraded. The page will retry safely.',VWLB_TEXT_DOMAIN);?></div><?php endif;?>
		<?php if(!empty($event['playback']['url'])):?><div class="vwlb-player-frame"><iframe src="<?php echo esc_url($event['playback']['url']);?>" title="<?php echo esc_attr($event['title']);?>" allowfullscreen></iframe></div><?php endif;?>
		<?php if(is_user_logged_in()&&in_array($event['status'],array('scheduled','rehearsal','ready','live'),true)):?><section class="vwlb-live-participation"><h2><?php esc_html_e('Live participation',VWLB_TEXT_DOMAIN);?></h2><button type="button" data-vwlb-waiting-room><?php esc_html_e('Join waiting room',VWLB_TEXT_DOMAIN);?></button><label><input type="checkbox" data-vwlb-recording-consent> <?php esc_html_e('I consent to recording when this event explicitly records participant contributions.',VWLB_TEXT_DOMAIN);?></label><form data-vwlb-question-form><label><?php esc_html_e('Ask a question',VWLB_TEXT_DOMAIN);?><textarea name="question" maxlength="4000" required></textarea></label><button type="submit"><?php esc_html_e('Send question',VWLB_TEXT_DOMAIN);?></button></form><div class="vwlb-status" role="status" aria-live="polite"></div></section><?php endif;?>
		<?php if(!empty($extras['resources'])):?><section><h2><?php esc_html_e('Resources',VWLB_TEXT_DOMAIN);?></h2><ul><?php foreach($extras['resources'] as $res):?><li><?php if($res['url']):?><a href="<?php echo esc_url($res['url']);?>" rel="noopener noreferrer"><?php echo esc_html($res['title']);?></a><?php else:echo esc_html($res['title']);endif;?></li><?php endforeach;?></ul></section><?php endif;?>
		<div><?php echo wp_kses_post(wpautop($event['description']));?></div></main><?php return ob_get_clean();
	}
	public function channel(){
		$this->enqueue();$slug=get_query_var('vwlb_channel_slug');if(!$slug&&isset($_GET['channel']))$slug=sanitize_title(wp_unslash($_GET['channel']));
		global $wpdb;$channel=$slug?$wpdb->get_row($wpdb->prepare('SELECT * FROM '.VWLB_Helpers::table('channels').' WHERE slug=%s AND status=%s LIMIT 1',$slug,'active'),ARRAY_A):null;
		if(!$channel)return $this->state('empty',__('Channel unavailable',VWLB_TEXT_DOMAIN),__('This channel is not public or does not exist.',VWLB_TEXT_DOMAIN));
		$videos=VWLB_Repository::browse_videos(array('per_page'=>24,'channel_id'=>$channel['id']));
		ob_start();?><main class="vwlb-shell"><?php echo $this->nav();?><header><h1><?php echo esc_html($channel['title']);?></h1><p><?php echo esc_html($channel['description']);?></p></header><div class="vwlb-grid" role="list"><?php foreach($videos['items'] as $item):?><article class="vwlb-card" role="listitem"><a href="<?php echo esc_url($item['url']);?>"><h2><?php echo esc_html($item['title']);?></h2><p><?php echo esc_html($item['excerpt']);?></p></a></article><?php endforeach;?></div></main><?php return ob_get_clean();
	}
	public function podcasts(){
		$this->enqueue();global $wpdb;$rows=$wpdb->get_results("SELECT public_id,title,slug,description,language FROM ".VWLB_Helpers::table('podcast_series')." WHERE status='published' AND visibility='public' AND deleted_at IS NULL ORDER BY updated_at DESC LIMIT 100",ARRAY_A);
		ob_start();?><main class="vwlb-shell"><?php echo $this->nav();?><h1><?php esc_html_e('Podcasts',VWLB_TEXT_DOMAIN);?></h1><div class="vwlb-grid" role="list"><?php foreach($rows as $r):?><article class="vwlb-card" role="listitem"><h2><?php echo esc_html($r['title']);?></h2><p><?php echo esc_html(wp_trim_words(wp_strip_all_tags($r['description']),35));?></p></article><?php endforeach;?></div></main><?php return ob_get_clean();
	}
	public function podcast(){
		$this->enqueue();$id=get_query_var('vwlb_podcast_id');$ep=VWLB_Podcasts::public_episode_dto($id);if(!$ep)return $this->state('restricted',__('Podcast unavailable',VWLB_TEXT_DOMAIN),__('This episode is unavailable.',VWLB_TEXT_DOMAIN));
		ob_start();?><main class="vwlb-shell" data-vwlb-podcast="<?php echo esc_attr($ep['id']);?>"><?php echo $this->nav();?><article><h1><?php echo esc_html($ep['title']);?></h1><?php if($ep['audio_url']):?><audio controls preload="metadata" src="<?php echo esc_url($ep['audio_url']);?>"><?php esc_html_e('Your browser does not support audio playback.',VWLB_TEXT_DOMAIN);?></audio><?php endif;?><div><?php echo wp_kses_post(wpautop($ep['description']));?></div><?php if($ep['chapters']):?><ol class="vwlb-chapters"><?php foreach($ep['chapters'] as $c):?><li><?php echo esc_html(gmdate('H:i:s',(int)$c['start_seconds']).' — '.$c['title']);?></li><?php endforeach;?></ol><?php endif;?></article></main><?php return ob_get_clean();
	}
	public function studio_video(){VWLB_Helpers::no_cache_private();if(!VWLB_Security::can(VWLB_Contracts::CAP_SUBMIT))return $this->state('restricted',__('Sign in required',VWLB_TEXT_DOMAIN),__('Only approved publishers can use Video Studio.',VWLB_TEXT_DOMAIN));$this->enqueue();return '<main class="vwlb-shell">'.$this->nav().'<h1>'.esc_html__('Video Studio',VWLB_TEXT_DOMAIN).'</h1><div id="vwlb-studio-video" data-vwlb-studio="video"><p>'.esc_html__('Create, resumably upload, scan, transcode, caption, chapter, review and publish recorded video or podcast media through File 10.',VWLB_TEXT_DOMAIN).'</p></div></main>';}
	public function studio_live(){VWLB_Helpers::no_cache_private();if(!VWLB_Security::can(VWLB_Contracts::CAP_BROADCAST))return $this->state('restricted',__('Access restricted',VWLB_TEXT_DOMAIN),__('Live Studio requires broadcaster authorization.',VWLB_TEXT_DOMAIN));$this->enqueue();return '<main class="vwlb-shell">'.$this->nav().'<h1>'.esc_html__('Live Studio',VWLB_TEXT_DOMAIN).'</h1><div id="vwlb-studio-live" data-vwlb-studio="live"><p>'.esc_html__('Schedule, set reminders/capacity/waiting room, rehearse, issue a one-time stream key, moderate Q&A, collect recording consent, end and publish replay.',VWLB_TEXT_DOMAIN).'</p></div></main>';}
	public function history(){VWLB_Helpers::no_cache_private();if(!is_user_logged_in())return $this->state('restricted',__('Sign in required',VWLB_TEXT_DOMAIN),__('Sign in to view private watch history.',VWLB_TEXT_DOMAIN));global $wpdb;$rows=$wpdb->get_results($wpdb->prepare('SELECT s.progress_seconds,s.completed,s.updated_at,v.public_id,v.slug,v.title FROM '.VWLB_Helpers::table('playback_sessions').' s JOIN '.VWLB_Helpers::table('videos').' v ON v.id=s.object_id WHERE s.user_id=%d AND s.object_type=%s ORDER BY s.updated_at DESC LIMIT 100',get_current_user_id(),'video'),ARRAY_A);ob_start();?><main class="vwlb-shell"><?php echo $this->nav();?><h1><?php esc_html_e('Video History',VWLB_TEXT_DOMAIN);?></h1><button type="button" data-vwlb-clear-history><?php esc_html_e('Clear watch history',VWLB_TEXT_DOMAIN);?></button><?php if(!$rows):echo $this->state('empty',__('No history yet',VWLB_TEXT_DOMAIN),__('Videos you watch while signed in will appear here.',VWLB_TEXT_DOMAIN));else:?><ol class="vwlb-history"><?php foreach($rows as $r):?><li><a href="<?php echo esc_url(home_url('/video/'.$r['public_id'].'/'.$r['slug'].'/'));?>"><?php echo esc_html($r['title']);?></a> <span><?php echo esc_html(gmdate('H:i:s',(int)$r['progress_seconds']));?></span></li><?php endforeach;?></ol><?php endif;?><div class="vwlb-status" role="status" aria-live="polite"></div></main><?php return ob_get_clean();}
	private function state($class,$title,$message){return '<section class="vwlb-state vwlb-state-'.esc_attr($class).'" role="status"><h2>'.esc_html($title).'</h2><p>'.esc_html($message).'</p><p><a href="'.esc_url(home_url('/')).'">'.esc_html__('Home',VWLB_TEXT_DOMAIN).'</a></p></section>';}
}
