<?php
/** Live scheduling, credentials, lifecycle, playback grants and replay. */
defined( 'ABSPATH' ) || exit;
final class VWLB_Live {
	public static function schedule($data,$idempotency_key){
		if(!VWLB_Security::can(VWLB_Contracts::CAP_BROADCAST,null,'schedule_live'))return VWLB_Helpers::error('vwlb_forbidden',__('You cannot schedule live broadcasts.',VWLB_TEXT_DOMAIN),403);
		$title=VWLB_Helpers::text($data['title']??'');$timezone=VWLB_Helpers::text($data['timezone']??'UTC',64);$start=VWLB_Helpers::datetime_in_timezone($data['scheduled_start']??null,$timezone);$end=VWLB_Helpers::datetime_in_timezone($data['scheduled_end']??null,$timezone);
		if(!$title||!$start)return VWLB_Helpers::error('vwlb_live_fields_required',__('Title and start time are required.',VWLB_TEXT_DOMAIN));
		if($end&&strtotime($end)<=strtotime($start))return VWLB_Helpers::error('vwlb_live_time_invalid',__('End time must be after start time.',VWLB_TEXT_DOMAIN),422);
		$channel_id=absint($data['channel_id']??0);if($channel_id){$channel=VWLB_Repository::find('channels',$channel_id);if(!$channel||!VWLB_Security::can(VWLB_Contracts::CAP_BROADCAST,$channel,'schedule_live'))return VWLB_Helpers::error('vwlb_channel_forbidden',__('The channel is unavailable.',VWLB_TEXT_DOMAIN),404);}
		$hash=hash('sha256',VWLB_Helpers::json_encode($data));$idem=VWLB_Security::idempotency_begin($idempotency_key,'schedule_live',$hash);if(is_wp_error($idem))return $idem;if($idem['replay'])return $idem['response'];
		$provider_id=VWLB_Helpers::enum($data['provider']??'local',array_keys(VWLB_Providers::all()),'local');$provider=VWLB_Providers::get($provider_id);if(!$provider){VWLB_Security::idempotency_abort($idempotency_key,'schedule_live');return VWLB_Helpers::error('vwlb_provider_missing',__('The selected live provider is unavailable.',VWLB_TEXT_DOMAIN),503);}
		$visibility=VWLB_Helpers::enum($data['visibility']??'private',VWLB_Contracts::VISIBILITIES,'private');$now=VWLB_Helpers::now();$public=VWLB_Helpers::public_id('live');
		$event=array('public_id'=>$public,'channel_id'=>$channel_id,'owner_id'=>get_current_user_id(),'title'=>$title,'slug'=>sanitize_title($data['slug']??$title.'-'.substr($public,-6)),'description'=>VWLB_Helpers::textarea($data['description']??''),'topics_json'=>VWLB_Helpers::json_encode($data['topics']??array()),'language'=>VWLB_Helpers::text($data['language']??'en-US',20),'timezone'=>$timezone,'provider'=>$provider_id,'visibility'=>$visibility,'status'=>'scheduled','scheduled_start'=>$start,'scheduled_end'=>$end,'access_policy_json'=>VWLB_Helpers::json_encode($data['access_policy']??array('audience'=>$visibility)),'chat_policy_json'=>VWLB_Helpers::json_encode($data['chat_policy']??array('enabled'=>true,'slow_mode_seconds'=>0)),'recording_policy_json'=>VWLB_Helpers::json_encode($data['recording_policy']??array('record'=>true,'publish_replay'=>false)),'provider_state_json'=>'{}','slow_mode_seconds'=>max(0,min(300,absint($data['slow_mode_seconds']??0))),'created_at'=>$now,'updated_at'=>$now);
		$provider_result=$provider->create_live($event);if(is_wp_error($provider_result)){VWLB_Security::idempotency_abort($idempotency_key,'schedule_live');return $provider_result;}
		if(!is_array($provider_result)||empty($provider_result['provider_event_ref'])){VWLB_Security::idempotency_abort($idempotency_key,'schedule_live');return VWLB_Helpers::error('vwlb_provider_contract_invalid',__('The live provider returned an invalid creation response.',VWLB_TEXT_DOMAIN),503);}
		$event['provider_event_ref']=VWLB_Helpers::text($provider_result['provider_event_ref'],191);$safe_provider=array_intersect_key((array)$provider_result,array_flip(array('provider_event_ref','status','degraded','region')));$event['provider_state_json']=VWLB_Helpers::json_encode($safe_provider);
		global $wpdb;$result=VWLB_DB::transaction(function()use($wpdb,$event,$public,$start,$idempotency_key){$saved=$wpdb->insert(VWLB_Helpers::table('live_events'),$event);if(!$saved||!(int)$wpdb->insert_id)return VWLB_Helpers::error('vwlb_database_error',__('Live event could not be created.',VWLB_TEXT_DOMAIN),500);$id=(int)$wpdb->insert_id;VWLB_Helpers::audit('live',$id,'schedule','draft','scheduled');VWLB_Helpers::outbox('LiveEventScheduled','live',$id,array('public_id'=>$public,'scheduled_start'=>$start));$response=array('public_id'=>$public,'status'=>'scheduled','version'=>1);$idem_done=VWLB_Security::idempotency_finish($idempotency_key,'schedule_live',$response);return is_wp_error($idem_done)?$idem_done:$response;});
		if(!is_wp_error($result))return $result;
		$abort=VWLB_Security::idempotency_abort($idempotency_key,'schedule_live');$cancel=apply_filters('vwlb_provider_cancel_live',null,$provider_id,array('provider_event_ref'=>$event['provider_event_ref'],'live_public_id'=>$public));
		if(is_wp_error($abort)||!is_array($cancel)||empty($cancel['accepted'])){do_action('vwlb_provider_live_orphaned',$provider_id,array('provider_event_ref'=>$event['provider_event_ref']),array('public_id'=>$public,'local_error'=>$result->get_error_code()));return VWLB_Helpers::error('vwlb_provider_live_reconcile_required',__('The provider created the live event but File 10 could not persist it or confirm provider cancellation. Reconciliation is required.',VWLB_TEXT_DOMAIN),503,array('provider'=>$provider_id,'live_public_id'=>$public,'local_error'=>$result->get_error_code()));}
		return $result;
	}
	public static function issue_credential($live_id,$ttl=21600){
		$event=VWLB_Repository::find('live_events',$live_id);if(!$event)return VWLB_Helpers::error('vwlb_live_missing',__('Live event not found.',VWLB_TEXT_DOMAIN),404);
		if(!VWLB_Security::can(VWLB_Contracts::CAP_BROADCAST,$event,'issue_stream_credential'))return VWLB_Helpers::error('vwlb_forbidden',__('You cannot issue credentials.',VWLB_TEXT_DOMAIN),403);
		$step=VWLB_Security::require_step_up('issue_stream_credential');if(is_wp_error($step))return $step;if(!in_array($event['status'],array('scheduled','rehearsal','ready'),true))return VWLB_Helpers::error('vwlb_live_state_invalid',__('Credentials cannot be issued in this state.',VWLB_TEXT_DOMAIN),409);
		$provider=VWLB_Providers::get($event['provider']);if(!$provider)return VWLB_Helpers::error('vwlb_provider_missing',__('The live provider is unavailable.',VWLB_TEXT_DOMAIN),503);
		$ingest=$provider->issue_ingest($event);if(is_wp_error($ingest))return $ingest;if(!is_array($ingest)||empty($ingest['ingest_url']))return VWLB_Helpers::error('vwlb_provider_ingest_contract_invalid',__('The live provider returned an invalid ingest credential response.',VWLB_TEXT_DOMAIN),503);
		$ingest_url=VWLB_Helpers::remote_url($ingest['ingest_url']);if(!$ingest_url)return VWLB_Helpers::error('vwlb_provider_ingest_contract_invalid',__('The live provider returned an unsafe ingest URL.',VWLB_TEXT_DOMAIN),503);
		$provider_supplied_key=array_key_exists('stream_key',$ingest)&&''!==(string)$ingest['stream_key'];$secret=$provider_supplied_key?(string)$ingest['stream_key']:VWLB_Providers::stream_secret();if(strlen($secret)<16||strlen($secret)>512)return VWLB_Helpers::error('vwlb_provider_ingest_contract_invalid',__('The live provider returned an unsafe stream credential.',VWLB_TEXT_DOMAIN),503);
		$provider_ref=VWLB_Helpers::text($ingest['provider_ref']??'',191);$credential_ref=VWLB_Helpers::text($ingest['credential_ref']??'',191);unset($ingest['stream_key']);$ingest['ingest_url']=$ingest_url;global $wpdb;$now=VWLB_Helpers::now();
		$result=VWLB_DB::transaction(function()use($wpdb,$event,$ingest,$secret,$ttl,$now){$rotated=$wpdb->update(VWLB_Helpers::table('stream_credentials'),array('status'=>'rotated','rotated_at'=>$now),array('live_event_id'=>$event['id'],'status'=>'active'));if(false===$rotated)return VWLB_Helpers::error('vwlb_database_error',__('Existing stream credentials could not be rotated.',VWLB_TEXT_DOMAIN),500);$public=VWLB_Helpers::public_id('key');$saved=$wpdb->insert(VWLB_Helpers::table('stream_credentials'),array('public_id'=>$public,'live_event_id'=>$event['id'],'provider'=>$event['provider'],'credential_hash'=>VWLB_Providers::hash_secret($secret),'ingest_url'=>$ingest['ingest_url'],'scope'=>'broadcast','status'=>'active','expires_at'=>gmdate('Y-m-d H:i:s',time()+max(300,min(DAY_IN_SECONDS,(int)$ttl))),'created_by'=>get_current_user_id(),'created_at'=>$now));if(!$saved||!(int)$wpdb->insert_id)return VWLB_Helpers::error('vwlb_database_error',__('Stream credential could not be recorded.',VWLB_TEXT_DOMAIN),500);VWLB_Helpers::audit('live',$event['id'],'issue_stream_credential',$event['status'],$event['status'],'Credential issued; secret redacted from audit',array('credential_public_id'=>$public));return array('public_id'=>$public,'ingest_url'=>$ingest['ingest_url'],'stream_key'=>$secret,'display_once'=>true,'expires_at'=>gmdate('c',time()+max(300,min(DAY_IN_SECONDS,(int)$ttl))));});
		if(!is_wp_error($result))return $result;
		$revoke=apply_filters('vwlb_provider_revoke_ingest',null,$event,array('provider_ref'=>$provider_ref,'credential_ref'=>$credential_ref,'provider_supplied_key'=>$provider_supplied_key));if(!is_array($revoke)||empty($revoke['accepted']))return VWLB_Helpers::error('vwlb_stream_credential_reconcile_required',__('The provider issued an ingest credential but File 10 could not persist it or confirm revocation. Reconciliation is required.',VWLB_TEXT_DOMAIN),503,array('local_error'=>$result->get_error_code(),'live_public_id'=>$event['public_id']));
		return $result;
	}
	public static function transition($live_id,$to,$expected_version,$note='',$provider_proof=array()){$event=VWLB_Repository::find('live_events',$live_id);if(!$event)return VWLB_Helpers::error('vwlb_live_missing',__('Live event not found.',VWLB_TEXT_DOMAIN),404);if(!VWLB_Security::can(VWLB_Contracts::CAP_BROADCAST,$event,'transition_live'))return VWLB_Helpers::error('vwlb_forbidden',__('You cannot control this broadcast.',VWLB_TEXT_DOMAIN),403);$to=VWLB_Helpers::enum($to,VWLB_Contracts::LIVE_STATES,'');if(!$to)return VWLB_Helpers::error('vwlb_live_state_invalid',__('Invalid live state.',VWLB_TEXT_DOMAIN));$assert=VWLB_State_Machine::assert('live',$event['status'],$to);if(is_wp_error($assert))return $assert;if(in_array($to,array('live','ended','restricted'),true)){$step=VWLB_Security::require_step_up('transition_live_'.$to);if(is_wp_error($step))return $step;}if('live'===$to){$active=self::active_credential($event['id']);if(!$active)return VWLB_Helpers::error('vwlb_stream_credential_required',__('An active stream credential is required.',VWLB_TEXT_DOMAIN),422);}$safe_proof=array_intersect_key((array)$provider_proof,array_flip(array('provider_event_ref','status','degraded','region','health_code')));$changes=array('status'=>$to,'provider_state_json'=>VWLB_Helpers::json_encode(array_merge(VWLB_Helpers::json($event['provider_state_json']),$safe_proof)));if('live'===$to)$changes['actual_start']=VWLB_Helpers::now();if('ended'===$to)$changes['actual_end']=VWLB_Helpers::now();$updated=VWLB_DB::transaction(function()use($event,$expected_version,$changes,$to){$changed=VWLB_Repository::update_versioned('live_events',$event['id'],$expected_version,$changes);if(is_wp_error($changed))return $changed;if('ended'===$to){$queued=self::queue_recording($changed);if(is_wp_error($queued))return $queued;}return $changed;});if(is_wp_error($updated))return $updated;VWLB_Helpers::audit('live',$event['id'],'transition',$event['status'],$to,$note,array('provider_proof'=>array_keys($provider_proof)));VWLB_Helpers::outbox(self::event_for_state($to),'live',$event['id'],array('public_id'=>$event['public_id'],'from'=>$event['status'],'to'=>$to));return $updated;}
	private static function event_for_state($state){$map=array('scheduled'=>'LiveEventScheduled','live'=>'LiveBroadcastStarted','interrupted'=>'LiveBroadcastInterrupted','ended'=>'LiveBroadcastEnded','replay_published'=>'LiveReplayPublished','restricted'=>'LiveRestricted');return $map[$state]??'LiveStateChanged';}
	private static function active_credential($event_id){global $wpdb;return $wpdb->get_row($wpdb->prepare('SELECT * FROM '.VWLB_Helpers::table('stream_credentials').' WHERE live_event_id=%d AND status=%s AND (expires_at IS NULL OR expires_at>%s) ORDER BY id DESC LIMIT 1',$event_id,'active',VWLB_Helpers::now()),ARRAY_A);}
	public static function kill($live_id,$expected_version,$reason){$event=VWLB_Repository::find('live_events',$live_id);if(!$event)return VWLB_Helpers::error('vwlb_live_missing',__('Live event not found.',VWLB_TEXT_DOMAIN),404);if(!in_array($event['status'],array('rehearsal','ready','live','interrupted'),true))return VWLB_Helpers::error('vwlb_live_state_invalid',__('Emergency end is not available in this state.',VWLB_TEXT_DOMAIN),409);if(!VWLB_Security::can(VWLB_Contracts::CAP_MODERATE,$event,'emergency_end'))return VWLB_Helpers::error('vwlb_forbidden',__('You cannot end this broadcast.',VWLB_TEXT_DOMAIN),403);$step=VWLB_Security::require_step_up('emergency_end');if(is_wp_error($step))return $step;global $wpdb;return VWLB_DB::transaction(function()use($event,$expected_version,$reason,$wpdb){$updated=VWLB_Repository::update_versioned('live_events',$event['id'],$expected_version,array('status'=>'ended','kill_switch'=>1,'actual_end'=>VWLB_Helpers::now()));if(is_wp_error($updated))return $updated;$revoked=$wpdb->update(VWLB_Helpers::table('stream_credentials'),array('status'=>'revoked','revoked_at'=>VWLB_Helpers::now()),array('live_event_id'=>$event['id'],'status'=>'active'));if(false===$revoked)return VWLB_Helpers::error('vwlb_database_error',__('Active stream credentials could not be revoked.',VWLB_TEXT_DOMAIN),500);do_action('vwlb_provider_emergency_end',$event,$reason);VWLB_Helpers::audit('live',$event['id'],'emergency_end',$event['status'],'ended',$reason);VWLB_Helpers::outbox('LiveBroadcastEnded','live',$event['id'],array('emergency'=>true,'reason_category'=>sanitize_key($reason)));$queued=self::queue_recording($updated);if(is_wp_error($queued))return $queued;return $updated;});}
	private static function queue_recording($event){$policy=VWLB_Helpers::json($event['recording_policy_json']);if(empty($policy['record']))return true;global $wpdb;$saved=$wpdb->insert(VWLB_Helpers::table('processing_jobs'),array('public_id'=>VWLB_Helpers::public_id('job'),'asset_id'=>(int)$event['recording_asset_id'],'job_type'=>'finalize_live_recording','provider'=>$event['provider'],'status'=>'pending','priority'=>10,'attempts'=>0,'max_attempts'=>8,'available_at'=>VWLB_Helpers::now(),'input_json'=>VWLB_Helpers::json_encode(array('live_event_id'=>$event['id'])),'output_json'=>'{}','created_at'=>VWLB_Helpers::now(),'updated_at'=>VWLB_Helpers::now()));if(!$saved||!(int)$wpdb->insert_id)return VWLB_Helpers::error('vwlb_recording_queue_failed',__('Recording finalization could not be queued durably.',VWLB_TEXT_DOMAIN),503);return true;}
	public static function state($live_id){$event=VWLB_Repository::find('live_events',$live_id);if(!$event||!VWLB_Security::can_view($event))return VWLB_Helpers::error('vwlb_not_found',__('Live event not found.',VWLB_TEXT_DOMAIN),404);self::request_time_reconcile($event);$event=VWLB_Repository::find('live_events',$event['id']);$dto=VWLB_Repository::public_live_dto($event);if('live'===$event['status']){$provider=VWLB_Providers::get($event['provider']);if(!$provider){$dto['playback']=array('error'=>'vwlb_provider_missing');}else{$playback=$provider->playback($event,VWLB_Security::claims());if(!is_wp_error($playback)&&!in_array($event['visibility'],array('public','unlisted'),true)){$secure=apply_filters('vwlb_secure_live_playback_grant','',$event,$playback,VWLB_Security::claims());$playback=$secure?array_merge($playback,array('url'=>esc_url_raw($secure))):VWLB_Helpers::error('vwlb_secure_delivery_required',__('Secure live delivery is not configured.',VWLB_TEXT_DOMAIN),503);}$dto['playback']=is_wp_error($playback)?array('error'=>$playback->get_error_code()):$playback;}}return $dto;}
	private static function request_time_reconcile($event){$now=time();if('scheduled'===$event['status']&&$event['scheduled_end']&&strtotime($event['scheduled_end'])<$now){global $wpdb;$changed=$wpdb->update(VWLB_Helpers::table('live_events'),array('status'=>'ended','actual_end'=>VWLB_Helpers::now(),'version'=>(int)$event['version']+1,'updated_at'=>VWLB_Helpers::now()),array('id'=>$event['id'],'version'=>$event['version']));if(1===$changed){VWLB_Helpers::audit('live',$event['id'],'request_time_reconcile','scheduled','ended','Scheduled window elapsed');VWLB_Helpers::outbox('LiveBroadcastEnded','live',$event['id'],array('reason'=>'scheduled_window_elapsed'));}}}
	public static function publish_replay($live_id,$video_id,$expected_version){$event=VWLB_Repository::find('live_events',$live_id);$video=VWLB_Repository::find('videos',$video_id);if(!$event||!$video)return VWLB_Helpers::error('vwlb_missing',__('Live event or replay video not found.',VWLB_TEXT_DOMAIN),404);if(!VWLB_Security::can(VWLB_Contracts::CAP_BROADCAST,$event,'publish_replay')||!VWLB_Security::can(VWLB_Contracts::CAP_PUBLISH,$video,'publish_replay'))return VWLB_Helpers::error('vwlb_forbidden',__('You cannot publish this replay.',VWLB_TEXT_DOMAIN),403);if('published'!==$video['status'])return VWLB_Helpers::error('vwlb_replay_video_unpublished',__('Replay video must be published first.',VWLB_TEXT_DOMAIN),422);$assert=VWLB_State_Machine::assert('live',$event['status'],'replay_published');if(is_wp_error($assert))return $assert;$updated=VWLB_Repository::update_versioned('live_events',$event['id'],$expected_version,array('status'=>'replay_published','replay_video_id'=>$video['id']));if(is_wp_error($updated))return $updated;VWLB_Helpers::audit('live',$event['id'],'publish_replay',$event['status'],'replay_published','Canonical replay linked',array('video_id'=>$video['id']));VWLB_Helpers::outbox('LiveReplayPublished','live',$event['id'],array('video_public_id'=>$video['public_id']));return $updated;}
}
