<?php
/** R73: recording consent must be explicit/version-bound and finalization proof must fail closed on unreadable DB state. */
defined( 'ABSPATH' ) || exit;
final class VWLB_R73_Recording_Consent_Guard {
	public static function register(){add_filter('rest_request_before_callbacks',array(__CLASS__,'rest_consent'),18,3);add_filter('vwlb_finalize_live_recording',array(__CLASS__,'finalization_proof'),2,3);}
	private static function consent_route($request){if(!$request instanceof WP_REST_Request||'POST'!==strtoupper((string)$request->get_method()))return false;$route=(string)$request->get_route();foreach(VWLB_Contracts::namespaces() as $n)if(preg_match('#^/'.preg_quote($n,'#').'/live-events/[A-Za-z0-9_-]+/recording-consent$#',$route))return true;return false;}
	public static function rest_consent($response,$handler,$request){if(null!==$response||!self::consent_route($request))return $response;$d=$request->get_json_params();if(!is_array($d)||empty($d['consent']))return $response;$version=VWLB_Helpers::text($d['consent_version']??'',64);if(!$version)return VWLB_Helpers::error('vwlb_recording_consent_version_required',__('Recording consent requires the explicit current consent-text version.',VWLB_TEXT_DOMAIN),422);$event=VWLB_Repository::find('live_events',$request['id']);if(!$event)return $response;$policy=VWLB_Helpers::json($event['recording_policy_json']??'{}');$required=VWLB_Helpers::text($policy['consent_version']??'v1',64);if(!hash_equals($required,$version))return VWLB_Helpers::error('vwlb_recording_consent_version_stale',__('The recording-consent text changed. Review the current policy before consenting.',VWLB_TEXT_DOMAIN),409,array('required_consent_version'=>$required));return $response;}
	public static function finalization_proof($result,$input,$job){$live_id=absint($input['live_event_id']??0);if(!$live_id)return $result;$event=VWLB_Repository::find('live_events',$live_id);if(!$event){if(method_exists('VWLB_Repository','read_failed')&&VWLB_Repository::read_failed())return VWLB_Helpers::error('vwlb_recording_consent_unverifiable',__('Recording consent state could not be verified safely.',VWLB_TEXT_DOMAIN),503);return $result;}$policy=VWLB_Helpers::json($event['recording_policy_json']??'{}');if(empty($policy['record'])||empty($policy['consent_required']))return $result;global $wpdb;$required=VWLB_Helpers::text($policy['consent_version']??'v1',64);$wpdb->last_error='';$missing=$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM ".VWLB_Helpers::table('live_attendees')." WHERE live_event_id=%d AND state IN ('approved','joined') AND (recording_consent=0 OR consent_version<>%s)",$event['id'],$required));if(''!==(string)$wpdb->last_error){do_action('vwlb_operational_failure','recording','vwlb_recording_consent_unverifiable',array('live_public_id'=>$event['public_id']??''));return VWLB_Helpers::error('vwlb_recording_consent_unverifiable',__('Recording finalization stopped because attendee consent state was unreadable.',VWLB_TEXT_DOMAIN),503);}if((int)$missing>0)return VWLB_Helpers::error('vwlb_recording_consent_incomplete',__('Recording cannot be finalized while required attendee consent is incomplete or stale.',VWLB_TEXT_DOMAIN),409);return $result;}
}
