<?php
/** Versioned cross-file contracts without direct foreign writes. */
defined( 'ABSPATH' ) || exit;
final class VWLB_Integrations {
	public function register(){add_filter('sabri_contract_registry',array($this,'contracts'));add_filter('sabri_route_registry',array($this,'routes'));add_filter('sabri_owner_registry',array($this,'owners'));add_action('vwlb_domain_event',array($this,'publish_event'),10,3);add_action('vwlb_verified_webhook',array($this,'process_webhook'),10,3);}
	public function contracts($registry){$registry=is_array($registry)?$registry:array();$registry['file10.media.v1']=array('owner'=>'File 10','queries'=>array('get_media_asset','get_video_playback','get_live_state'),'commands'=>array('initiate_upload','publish_video','schedule_live','issue_stream_credential'),'events'=>array('VideoPublished.v1','VideoRestricted.v1','LiveEventScheduled.v1','LiveBroadcastStarted.v1','LiveBroadcastEnded.v1','LiveReplayPublished.v1'));$registry['file10.reels-source.v1']=array('consumer'=>'File 11','rule'=>'File 11 may reference eligible File 10 derivatives but may not own raw assets.');return $registry;}
	public function routes($routes){$routes=is_array($routes)?$routes:array();foreach(array('/video-wall/'=>'public','/video/{id}/{slug}/'=>'conditional','/live/{id}/'=>'conditional','/channel/{slug}/'=>'public','/studio/video/'=>'private','/studio/live/'=>'private') as $path=>$access)$routes[$path]=array('owner'=>'File 10','version'=>1,'access'=>$access,'layout'=>'content');return $routes;}
	public function owners($owners){$owners=is_array($owners)?$owners:array();foreach(array('recorded_video','video_channel','video_playlist','media_asset','caption_track','live_event','stream_credential','playback_session','media_moderation','copyright_takedown') as $entity)$owners[$entity]='File 10';return $owners;}
	public function publish_event($name,$payload,$event){do_action('sabri_event_bus_publish',$name,$payload,array('owner'=>'File 10','event_id'=>$event['public_id']));}
	public function process_webhook($provider,$data,$webhook_id){do_action('vwlb_provider_webhook_'.$provider,$data,$webhook_id);}
	public function consume($event_id,$event_name,$payload){global $wpdb;$hash=hash('sha256',VWLB_Helpers::json_encode($payload));$result=$wpdb->insert(VWLB_Helpers::table('inbox'),array('event_id'=>VWLB_Helpers::text($event_id,100),'event_name'=>VWLB_Helpers::text($event_name,100),'payload_hash'=>$hash,'status'=>'received','received_at'=>VWLB_Helpers::now()));if(false===$result)return array('duplicate'=>true);do_action('vwlb_consume_event',$event_name,$payload);$wpdb->update(VWLB_Helpers::table('inbox'),array('status'=>'processed','processed_at'=>VWLB_Helpers::now()),array('event_id'=>$event_id));return array('processed'=>true);}
}
