<?php
/** R71: private File 10 assets must resolve through an explicit short-lived secure grant, never a raw derivative URL. */
defined( 'ABSPATH' ) || exit;
final class VWLB_R71_Private_Download_Guard {
	public static function register(){add_filter('rest_request_before_callbacks',array(__CLASS__,'resolve_private'),25,3);}
	private static function matches($request){if(!$request instanceof WP_REST_Request||'POST'!==strtoupper((string)$request->get_method()))return false;$route=(string)$request->get_route();foreach(VWLB_Contracts::namespaces() as $n)if(preg_match('#^/'.preg_quote($n,'#').'/downloads/[A-Za-z0-9_-]+/resolve$#',$route))return true;return false;}
	private static function allowed($type,$object){if('video'===$type){$rights=VWLB_Helpers::json($object['rights_json']??'{}');return !empty($rights['download_allowed'])&&in_array($object['rights_status']??'',array('declared','verified'),true);}return !empty($object['download_allowed'])&&in_array($object['rights_status']??'',array('declared','verified'),true);}
	private static function body_token($request){$d=$request->get_json_params();return is_array($d)?VWLB_Helpers::text($d['download_token']??'',200):'';}
	public static function resolve_private($response,$handler,$request){
		if(null!==$response||!self::matches($request))return $response;if(!is_user_logged_in())return $response;global $wpdb;$table=VWLB_Helpers::table('download_tokens');$wpdb->last_error='';$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$table} WHERE public_id=%s LIMIT 1",VWLB_Helpers::text($request['id'],64)),ARRAY_A);if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_download_token_unreadable',__('Download token state could not be verified safely.',VWLB_TEXT_DOMAIN),503);if(!$row)return $response;$token=self::body_token($request);if((int)$row['user_id']!==get_current_user_id()||'active'!==($row['status']??'')||strtotime(($row['expires_at']??'').' UTC')<=time()||!password_verify((string)$token,(string)$row['token_hash']))return $response;if((int)$row['download_count']>=(int)$row['max_downloads'])return $response;
		$object='video'===$row['object_type']?VWLB_Repository::video_bundle($row['object_id']):VWLB_Podcasts::episode($row['object_id'],true);if(!$object||('podcast'===$row['object_type']&&'published'!==($object['status']??''))||!VWLB_Security::can_view($object,'download')||!self::allowed($row['object_type'],$object))return $response;$asset='video'===$row['object_type']?($object['asset']??array()):VWLB_Repository::find('media_assets',$object['asset_id']??0);$storage=VWLB_Helpers::json($asset['storage_json']??'{}');if('private_file'!==($storage['driver']??''))return $response;
		try{$grant=apply_filters('vwlb_private_download_grant','',$asset,$object,$row);}catch(Throwable $e){do_action('vwlb_operational_failure','download','vwlb_private_download_grant_exception',array('token_public_id'=>$row['public_id']??'','exception'=>sanitize_key(get_class($e))));return VWLB_Helpers::error('vwlb_private_download_grant_failed',__('Secure private download delivery failed safely.',VWLB_TEXT_DOMAIN),503);}$grant=esc_url_raw((string)$grant,array('https'));if(!$grant)return VWLB_Helpers::error('vwlb_secure_download_required',__('Private media requires a short-lived secure download grant.',VWLB_TEXT_DOMAIN),503);
		$now=VWLB_Helpers::now();$consumed=$wpdb->query($wpdb->prepare("UPDATE {$table} SET download_count=download_count+1,updated_at=%s WHERE id=%d AND user_id=%d AND status='active' AND expires_at>%s AND download_count<max_downloads",$now,$row['id'],get_current_user_id(),$now));if(1!==$consumed)return VWLB_Helpers::error('vwlb_download_limit_reached',__('Download token was already consumed or changed concurrently.',VWLB_TEXT_DOMAIN),410);$out=rest_ensure_response(array('url'=>$grant,'expires_in'=>120,'checksum'=>$asset['checksum']??'','rights_status'=>$object['rights_status']??''));$out->header('Cache-Control','private, no-store');$out->header('X-Sabri-File','10');$out->header('X-VWLB-Version',VWLB_VERSION);return $out;
	}
}
