<?php
/** Bounded data access; public DTOs never expose internal rows. */
defined( 'ABSPATH' ) || exit;
final class VWLB_Repository {
	public static function find( $entity, $id_or_public, $for_update=false ) {
		global $wpdb; $allowed=array('channels','playlists','media_assets','videos','live_events','captions','moderation','takedowns','processing_jobs'); if(!in_array($entity,$allowed,true))return null;$table=VWLB_Helpers::table($entity);$column=is_numeric($id_or_public)?'id':'public_id';$suffix=$for_update?' FOR UPDATE':'';return $wpdb->get_row($wpdb->prepare("SELECT * FROM $table WHERE $column=%s LIMIT 1$suffix",(string)$id_or_public),ARRAY_A);
	}
	public static function update_versioned( $entity, $id, $expected_version, $changes, $formats=array() ) {
		global $wpdb; $allowed=array('channels','playlists','media_assets','videos','live_events','captions','takedowns'); if(!in_array($entity,$allowed,true))return VWLB_Helpers::error('vwlb_bad_entity',__('Invalid entity.',VWLB_TEXT_DOMAIN));$changes['version']=absint($expected_version)+1;$changes['updated_at']=VWLB_Helpers::now();$where=array('id'=>absint($id),'version'=>absint($expected_version));$result=$wpdb->update(VWLB_Helpers::table($entity),$changes,$where,$formats,array('%d','%d'));if(false===$result)return VWLB_Helpers::error('vwlb_database_error',__('The record could not be updated.',VWLB_TEXT_DOMAIN),500);if(0===$result)return VWLB_Helpers::error('vwlb_version_conflict',__('The record changed. Refresh and retry.',VWLB_TEXT_DOMAIN),409);return self::find($entity,$id);
	}
	public static function browse_videos( $args=array() ) {
		global $wpdb;$table=VWLB_Helpers::table('videos');$limit=max(1,min(24,absint($args['per_page']??12)));$cursor=VWLB_Helpers::cursor_id($args['cursor']??'');$where=array("status='published'","visibility='public'","deleted_at IS NULL");$params=array();if($cursor){$where[]='id < %d';$params[]=$cursor;}if(!empty($args['channel_id'])){$where[]='channel_id=%d';$params[]=absint($args['channel_id']);}if(!empty($args['language'])){$where[]='language=%s';$params[]=sanitize_text_field($args['language']);}$sql="SELECT id,public_id,channel_id,owner_id,title,slug,excerpt,language,provider,embed_url,thumbnail_id,duration_seconds,visibility,status,published_at,view_count,like_count,dislike_count FROM $table WHERE ".implode(' AND ',$where)." ORDER BY published_at DESC,id DESC LIMIT %d";$params[]=$limit+1;
		$wpdb->last_error='';$rows=$wpdb->get_results($wpdb->prepare($sql,$params),ARRAY_A);
		if(''!==(string)$wpdb->last_error){do_action('vwlb_operational_failure','repository','vwlb_video_browse_read_failed',array());return array('items'=>array(),'next_cursor'=>'','error_code'=>'vwlb_video_browse_read_failed');}
		$rows=is_array($rows)?$rows:array();$next='';if(count($rows)>$limit){array_pop($rows);$last=end($rows);$next=$last?VWLB_Helpers::opaque_cursor($last['id']):'';reset($rows);}foreach($rows as &$r){$channel_id=(int)($r['channel_id']??0);$thumbnail_id=(int)($r['thumbnail_id']??0);unset($r['id'],$r['channel_id'],$r['owner_id'],$r['thumbnail_id']);$r['channel_public_id']='';if($channel_id){$wpdb->last_error='';$channel=self::find('channels',$channel_id);if(''!==(string)$wpdb->last_error){do_action('vwlb_operational_failure','repository','vwlb_video_browse_channel_read_failed',array());return array('items'=>array(),'next_cursor'=>'','error_code'=>'vwlb_video_browse_read_failed');}$r['channel_public_id']=$channel['public_id']??'';}$r['thumbnail_url']=$thumbnail_id?(wp_get_attachment_image_url($thumbnail_id,'large')?:''):'';$r['url']=home_url('/video/'.$r['public_id'].'/'.$r['slug'].'/');}unset($r);return array('items'=>$rows,'next_cursor'=>$next);
	}
	public static function video_bundle( $id_or_public ) {
		global $wpdb;$video=self::find('videos',$id_or_public);if(!$video)return null;$asset=$video['asset_id']?self::find('media_assets',$video['asset_id']):null;$captions_table=VWLB_Helpers::table('captions');$captions=$wpdb->get_results($wpdb->prepare("SELECT c.public_id,c.language,c.kind,c.format,c.content,c.status,c.version FROM $captions_table c WHERE c.video_id=%d AND c.status=%s AND NOT EXISTS (SELECT 1 FROM $captions_table newer WHERE newer.video_id=c.video_id AND newer.language=c.language AND newer.kind=c.kind AND newer.status='published' AND newer.version>c.version) ORDER BY c.language,c.kind,c.version DESC LIMIT 100",$video['id'],'published'),ARRAY_A);$video['asset']=$asset;$video['captions']=$captions;return $video;
	}
	public static function public_video_dto( $video ) {
		if(!$video||!VWLB_Security::can_view($video))return null;$channel_public_id='';if(!empty($video['channel_id'])){$channel=self::find('channels',$video['channel_id']);$channel_public_id=$channel['public_id']??'';}return array('public_id'=>$video['public_id'],'channel_public_id'=>$channel_public_id,'title'=>$video['title'],'slug'=>$video['slug'],'description'=>$video['description'],'excerpt'=>$video['excerpt'],'topics'=>VWLB_Helpers::json($video['topics_json']??'[]'),'language'=>$video['language'],'provider'=>$video['provider'],'thumbnail_url'=>$video['thumbnail_id']?wp_get_attachment_image_url($video['thumbnail_id'],'large'):'','duration_seconds'=>(int)$video['duration_seconds'],'visibility'=>$video['visibility'],'published_at'=>VWLB_Helpers::iso_utc($video['published_at']),'counts'=>array('views'=>(int)$video['view_count'],'likes'=>(int)$video['like_count'],'dislikes'=>(int)$video['dislike_count']),'captions'=>array_map(function($c){return array_intersect_key($c,array_flip(array('public_id','language','kind','format','version')));},$video['captions']??array()),'url'=>home_url('/video/'.$video['public_id'].'/'.$video['slug'].'/'));
	}
	public static function live_bundle($id_or_public){return self::find('live_events',$id_or_public);}
	public static function public_live_dto($event){if(!$event||!VWLB_Security::can_view($event))return null;return array('public_id'=>$event['public_id'],'title'=>$event['title'],'slug'=>$event['slug'],'description'=>$event['description'],'language'=>$event['language'],'timezone'=>$event['timezone'],'provider'=>$event['provider'],'visibility'=>$event['visibility'],'status'=>$event['status'],'scheduled_start'=>VWLB_Helpers::iso_utc($event['scheduled_start']),'scheduled_end'=>VWLB_Helpers::iso_utc($event['scheduled_end']),'actual_start'=>VWLB_Helpers::iso_utc($event['actual_start']),'actual_end'=>VWLB_Helpers::iso_utc($event['actual_end']),'replay_video_public_id'=>!empty($event['replay_video_id'])?((self::find('videos',$event['replay_video_id'])['public_id']??'')):'','provider_degraded'=>!empty(VWLB_Helpers::json($event['provider_state_json'])['degraded']),'url'=>home_url('/live/'.$event['public_id'].'/'));
	}
	public static function channel_mutation_dto($row){if(!$row||is_wp_error($row))return $row;return array('public_id'=>$row['public_id']??'','status'=>$row['status']??'','visibility'=>$row['visibility']??'','version'=>(int)($row['version']??0));}
	public static function playlist_mutation_dto($row){if(!$row||is_wp_error($row))return $row;return array('public_id'=>$row['public_id']??'','status'=>$row['status']??'','visibility'=>$row['visibility']??'','version'=>(int)($row['version']??0));}
	public static function video_mutation_dto($row){if(!$row||is_wp_error($row))return $row;return array('public_id'=>$row['public_id']??'','status'=>$row['status']??'','visibility'=>$row['visibility']??'','version'=>(int)($row['version']??0),'scheduled_at'=>VWLB_Helpers::iso_utc($row['scheduled_at']??null),'published_at'=>VWLB_Helpers::iso_utc($row['published_at']??null));}
	public static function asset_mutation_dto($row){if(!$row||is_wp_error($row))return $row;return array('public_id'=>$row['public_id']??'','status'=>$row['status']??'','scan_status'=>$row['scan_status']??'','version'=>(int)($row['version']??0),'checksum'=>$row['checksum']??'');}
	public static function live_mutation_dto($row){if(!$row||is_wp_error($row))return $row;return array('public_id'=>$row['public_id']??'','status'=>$row['status']??'','visibility'=>$row['visibility']??'','version'=>(int)($row['version']??0),'scheduled_start'=>VWLB_Helpers::iso_utc($row['scheduled_start']??null),'actual_start'=>VWLB_Helpers::iso_utc($row['actual_start']??null),'actual_end'=>VWLB_Helpers::iso_utc($row['actual_end']??null));}
	public static function takedown_mutation_dto($row){if(!$row||is_wp_error($row))return $row;return array('public_id'=>$row['public_id']??'','status'=>$row['status']??'','version'=>(int)($row['version']??0),'closed_at'=>VWLB_Helpers::iso_utc($row['closed_at']??null));}
}
