<?php
/** R114: human-reviewed media tracks remain fail-closed and audience-bound at publication and delivery. */
defined('ABSPATH') || exit;
final class VWLB_R114_AI_Track_Delivery_Guard {
	public static function register(){add_filter('rest_request_before_callbacks',array(__CLASS__,'before_publish'),23,3);add_filter('rest_request_after_callbacks',array(__CLASS__,'after_delivery'),86,3);}
	private static function strict_https_remote($url){$url=esc_url_raw((string)$url,array('https'));if(!$url)return '';$p=wp_parse_url($url);$host=strtolower((string)($p['host']??''));$scheme=strtolower((string)($p['scheme']??''));$port=isset($p['port'])?(int)$p['port']:443;if('https'!==$scheme||!$host||443!==$port||isset($p['user'])||isset($p['pass']))return '';if(in_array($host,array('localhost','localhost.localdomain','metadata.google.internal'),true)||str_ends_with($host,'.local')||str_ends_with($host,'.internal'))return '';if(filter_var($host,FILTER_VALIDATE_IP)&&false===filter_var($host,FILTER_VALIDATE_IP,FILTER_FLAG_NO_PRIV_RANGE|FILTER_FLAG_NO_RES_RANGE))return '';return $url;}
	private static function track_transition($request){if(!$request instanceof WP_REST_Request||'POST'!==strtoupper((string)$request->get_method()))return false;$route=(string)$request->get_route();foreach(VWLB_Contracts::namespaces() as $n)if(preg_match('#^/'.preg_quote($n,'#').'/media-tracks/[A-Za-z0-9_-]+/transition$#',$route))return true;return false;}
	public static function before_publish($response,$handler,$request){
		if(null!==$response||!self::track_transition($request))return $response;$body=$request->get_json_params();$body=is_array($body)?$body:array();if('publish'!==sanitize_key((string)($body['action']??'')))return $response;global $wpdb;$table=VWLB_Helpers::table('media_tracks');$wpdb->last_error='';$track=$wpdb->get_row($wpdb->prepare("SELECT public_id,status,file_ref,provider_ref,metadata_json FROM {$table} WHERE public_id=%s LIMIT 1",VWLB_Helpers::text($request['id'],64)),ARRAY_A);if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_media_track_publish_unreadable',__('Media-track publication state could not be verified safely.',VWLB_TEXT_DOMAIN),503);if(!$track)return $response;$meta=VWLB_Helpers::json($track['metadata_json']??'{}');if(in_array(sanitize_key((string)($meta['human_review_required']??'')),array('1','true','yes'),true)&&'reviewed'!==($track['status']??''))return VWLB_Helpers::error('vwlb_review_required',__('Human review must be completed before a generated media track can be published.',VWLB_TEXT_DOMAIN),409);if(!empty($track['file_ref'])&&!self::strict_https_remote($track['file_ref']))return VWLB_Helpers::error('vwlb_media_track_file_ref_invalid',__('A reviewed media track must use an approved HTTPS remote file reference before publication.',VWLB_TEXT_DOMAIN),422);return $response;
	}
	private static function route_object($request){if(!$request instanceof WP_REST_Request||'GET'!==strtoupper((string)$request->get_method()))return array();$route=(string)$request->get_route();foreach(VWLB_Contracts::namespaces() as $n){$q=preg_quote($n,'#');if(preg_match('#^/'.$q.'/videos/([A-Za-z0-9_-]+)/playback$#',$route,$m))return array('type'=>'video','id'=>$m[1]);if(preg_match('#^/'.$q.'/live-events/([A-Za-z0-9_-]+)$#',$route,$m))return array('type'=>'live','id'=>$m[1]);}return array();}
	private static function object($ctx){VWLB_Repository::reset_read_failure();$row='video'===($ctx['type']??'')?VWLB_Repository::find('videos',$ctx['id']??''):('live'===($ctx['type']??'')?VWLB_Repository::find('live_events',$ctx['id']??''):null);if(VWLB_Repository::read_failed())return VWLB_Helpers::error('vwlb_media_track_delivery_unreadable',__('Media-track audience state could not be verified safely.',VWLB_TEXT_DOMAIN),503);return $row;}
	private static function tracks($ctx,$object){global $wpdb;$table=VWLB_Helpers::table('media_tracks');$wpdb->last_error='';$rows=$wpdb->get_results($wpdb->prepare("SELECT public_id,track_type,language,source,file_ref,provider_ref,version FROM {$table} WHERE object_type=%s AND object_id=%d AND status='published' ORDER BY track_type ASC,language ASC,id ASC LIMIT 100",$ctx['type'],(int)$object['id']),ARRAY_A);if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_media_track_delivery_unreadable',__('Published media-track state could not be read safely.',VWLB_TEXT_DOMAIN),503);$out=array();foreach((array)$rows as $row){try{if('public'===($object['visibility']??'private')){$resolved=apply_filters('vwlb_public_media_track_ref','',$row,$object);}else{$resolved=apply_filters('vwlb_secure_media_track_grant','',$row,$object,VWLB_Security::claims());}}catch(Throwable $e){do_action('vwlb_operational_failure','media_track','vwlb_media_track_delivery_exception',array('track_public_id'=>$row['public_id'],'exception'=>sanitize_key(get_class($e))));return VWLB_Helpers::error('vwlb_media_track_delivery_failed',__('Media-track delivery authorization ended unexpectedly.',VWLB_TEXT_DOMAIN),503);}$src=self::strict_https_remote(is_string($resolved)?$resolved:'');if(!$src)return VWLB_Helpers::error('vwlb_media_track_secure_delivery_required',__('A published media track requires an approved HTTPS delivery grant for this audience.',VWLB_TEXT_DOMAIN),503,array('track_public_id'=>$row['public_id']));$out[]=array('public_id'=>$row['public_id'],'track_type'=>$row['track_type'],'language'=>$row['language'],'source'=>$row['source'],'src'=>$src,'available'=>true,'version'=>(int)$row['version']);}return $out;}
	public static function after_delivery($response,$handler,$request){if(is_wp_error($response))return $response;$ctx=self::route_object($request);if(!$ctx)return $response;$object=self::object($ctx);if(is_wp_error($object))return $object;if(!$object||!VWLB_Security::can_view($object))return $response;$tracks=self::tracks($ctx,$object);if(is_wp_error($tracks))return $tracks;$wrapped=rest_ensure_response($response);$data=$wrapped->get_data();if(!is_array($data))return $response;$data['media_tracks']=$tracks;$wrapped->set_data($data);$wrapped->header('Cache-Control','private, no-store');if('public'!==($object['visibility']??''))$wrapped->header('X-Robots-Tag','noindex, nofollow, noarchive');return $wrapped;}
}
