<?php
/** R78: cache privacy for captions and secure public-feed delivery for private podcast storage. */
defined( 'ABSPATH' ) || exit;
final class VWLB_R78_Public_Delivery_Guard {
	public static function register(){add_filter('rest_request_before_callbacks',array(__CLASS__,'podcast_feed'),24,3);add_filter('rest_request_after_callbacks',array(__CLASS__,'caption_cache'),96,3);}
	private static function podcast_route($request){if(!$request instanceof WP_REST_Request||'GET'!==strtoupper((string)$request->get_method()))return '';foreach(VWLB_Contracts::namespaces() as $n){$q=preg_quote($n,'#');if(preg_match('#^/'.$q.'/podcasts/series/([A-Za-z0-9_-]+)/(feed|rss)$#',(string)$request->get_route(),$m))return $m[2];}return '';}
	private static function secure_audio($asset,$episode,$series){$storage=VWLB_Helpers::json($asset['storage_json']??'{}');$der=VWLB_Helpers::json($asset['derivatives_json']??'{}');if('private_file'!==($storage['driver']??''))return esc_url_raw($der['audio_only']??$der['mp3']??'',array('https'));try{$url=apply_filters('vwlb_public_podcast_feed_grant','',$asset,$episode,$series);}catch(Throwable $e){do_action('vwlb_operational_failure','podcast','vwlb_podcast_feed_grant_exception',array('episode_public_id'=>$episode['public_id']??'','exception'=>sanitize_key(get_class($e))));return VWLB_Helpers::error('vwlb_podcast_feed_secure_delivery_failed',__('Secure podcast feed delivery failed safely.',VWLB_TEXT_DOMAIN),503);}$url=esc_url_raw((string)$url,array('https'));return $url?$url:VWLB_Helpers::error('vwlb_podcast_feed_secure_delivery_required',__('Private podcast storage requires a configured short-lived feed delivery grant.',VWLB_TEXT_DOMAIN),503);}
	private static function feed_data($series_id){global $wpdb;$series_table=VWLB_Helpers::table('podcast_series');$episode_table=VWLB_Helpers::table('podcast_episodes');$wpdb->last_error='';$series=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$series_table} WHERE public_id=%s AND status='published' AND visibility IN ('public','unlisted') AND deleted_at IS NULL LIMIT 1",VWLB_Helpers::text($series_id,64)),ARRAY_A);if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_podcast_feed_unreadable',__('Podcast feed state could not be read safely.',VWLB_TEXT_DOMAIN),503);if(!$series)return VWLB_Helpers::error('vwlb_not_found',__('Podcast series not found.',VWLB_TEXT_DOMAIN),404);$wpdb->last_error='';$episodes=$wpdb->get_results($wpdb->prepare("SELECT public_id,title,description,duration_seconds,published_at,asset_id FROM {$episode_table} WHERE series_id=%d AND status='published' AND visibility IN ('public','unlisted') AND deleted_at IS NULL ORDER BY published_at DESC,id DESC LIMIT 200",$series['id']),ARRAY_A);if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_podcast_feed_unreadable',__('Podcast episode feed state could not be read safely.',VWLB_TEXT_DOMAIN),503);$items=array();foreach((array)$episodes as $ep){$asset=VWLB_Repository::find('media_assets',$ep['asset_id']);if(!$asset){if(method_exists('VWLB_Repository','read_failed')&&VWLB_Repository::read_failed())return VWLB_Helpers::error('vwlb_podcast_feed_unreadable',__('Podcast media state could not be verified safely.',VWLB_TEXT_DOMAIN),503);continue;}$audio=self::secure_audio($asset,$ep,$series);if(is_wp_error($audio))return $audio;$items[]=array('id'=>$ep['public_id'],'title'=>$ep['title'],'description'=>$ep['description'],'published_at'=>VWLB_Helpers::iso_utc($ep['published_at']),'duration_seconds'=>(int)$ep['duration_seconds'],'audio_url'=>$audio);}return array('contract'=>'File10PodcastFeed.v1','series'=>array('id'=>$series['public_id'],'title'=>$series['title'],'description'=>$series['description'],'language'=>$series['language']),'episodes'=>$items,'rss_ready'=>true,'canonical_owner'=>'File 10');}
	private static function rss($feed){$s=$feed['series'];$xml='<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>'.esc_html($s['title']).'</title><description>'.esc_html($s['description']).'</description><language>'.esc_html($s['language']).'</language>';foreach($feed['episodes'] as $ep){$xml.='<item><guid isPermaLink="false">'.esc_html($ep['id']).'</guid><title>'.esc_html($ep['title']).'</title><description>'.esc_html(wp_strip_all_tags($ep['description'])).'</description>';if(!empty($ep['published_at']))$xml.='<pubDate>'.esc_html(gmdate(DATE_RSS,strtotime($ep['published_at']))).'</pubDate>';if(!empty($ep['audio_url']))$xml.='<enclosure url="'.esc_attr($ep['audio_url']).'" type="audio/mpeg" />';$xml.='</item>';}$xml.='</channel></rss>';return $xml;}
	public static function podcast_feed($response,$handler,$request){if(null!==$response)return $response;$kind=self::podcast_route($request);if(!$kind)return $response;$feed=self::feed_data($request['id']);if(is_wp_error($feed))return $feed;$out=new WP_REST_Response('rss'===$kind?self::rss($feed):$feed,200);$out->header('X-Sabri-File','10');$out->header('X-VWLB-Version',VWLB_VERSION);$out->header('Cache-Control','no-store');if('rss'===$kind)$out->header('Content-Type','application/rss+xml; charset=UTF-8');return $out;}
	public static function caption_cache($response,$handler,$request){if(is_wp_error($response)||!$request instanceof WP_REST_Request||'GET'!==strtoupper((string)$request->get_method()))return $response;$route=(string)$request->get_route();$id='';foreach(VWLB_Contracts::namespaces() as $n){if(preg_match('#^/'.preg_quote($n,'#').'/captions/([A-Za-z0-9_-]+)$#',$route,$m)){$id=$m[1];break;}}if(!$id)return $response;$caption=VWLB_Repository::find('captions',$id);$video=$caption?VWLB_Repository::find('videos',$caption['video_id']):null;if($video&&('public'!==($video['visibility']??'')||'published'!==($video['status']??''))){$wrapped=rest_ensure_response($response);$wrapped->header('Cache-Control','private, no-store');return $wrapped;}return $response;}
}
