<?php
/** Schema, transactions and migrations. */
defined( 'ABSPATH' ) || exit;
final class VWLB_DB {
	public static function transaction( $callback ) {
		global $wpdb;
		$started = $wpdb->query( 'START TRANSACTION' );
		if ( false === $started ) {
			return VWLB_Helpers::error( 'vwlb_transaction_start_failed', __( 'The operation could not start a database transaction.', VWLB_TEXT_DOMAIN ), 500 );
		}
		try {
			$result = call_user_func( $callback );
			if ( is_wp_error( $result ) ) {
				$wpdb->query( 'ROLLBACK' );
				return $result;
			}
			$committed = $wpdb->query( 'COMMIT' );
			if ( false === $committed ) {
				$wpdb->query( 'ROLLBACK' );
				return VWLB_Helpers::error( 'vwlb_transaction_commit_failed', __( 'The operation could not be committed safely.', VWLB_TEXT_DOMAIN ), 500 );
			}
			return $result;
		} catch ( Throwable $e ) {
			$wpdb->query( 'ROLLBACK' );
			return VWLB_Helpers::error( 'vwlb_transaction_failed', __( 'The operation could not be completed.', VWLB_TEXT_DOMAIN ), 500, array( 'exception' => get_class( $e ) ) );
		}
	}
	public static function schema_sql() {
		global $wpdb; $c=$wpdb->get_charset_collate(); $p=$wpdb->prefix.'vwlb_';
		return array(
		"CREATE TABLE {$p}channels (id bigint unsigned NOT NULL AUTO_INCREMENT,public_id varchar(80) NOT NULL,owner_id bigint unsigned NOT NULL DEFAULT 0,title varchar(191) NOT NULL,slug varchar(191) NOT NULL,description longtext NULL,branding_json longtext NULL,roles_json longtext NULL,status varchar(32) NOT NULL DEFAULT 'active',visibility varchar(32) NOT NULL DEFAULT 'public',version bigint unsigned NOT NULL DEFAULT 1,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY public_id(public_id),UNIQUE KEY slug(slug),KEY owner_status(owner_id,status)) $c",
		"CREATE TABLE {$p}channel_members (id bigint unsigned NOT NULL AUTO_INCREMENT,channel_id bigint unsigned NOT NULL,user_id bigint unsigned NOT NULL,member_role varchar(32) NOT NULL DEFAULT 'contributor',status varchar(32) NOT NULL DEFAULT 'active',created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY channel_user(channel_id,user_id),KEY user_status(user_id,status)) $c",
		"CREATE TABLE {$p}playlists (id bigint unsigned NOT NULL AUTO_INCREMENT,public_id varchar(80) NOT NULL,channel_id bigint unsigned NOT NULL DEFAULT 0,owner_id bigint unsigned NOT NULL DEFAULT 0,title varchar(191) NOT NULL,slug varchar(191) NOT NULL,description longtext NULL,status varchar(32) NOT NULL DEFAULT 'active',visibility varchar(32) NOT NULL DEFAULT 'public',version bigint unsigned NOT NULL DEFAULT 1,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY public_id(public_id),UNIQUE KEY channel_slug(channel_id,slug),KEY owner_status(owner_id,status)) $c",
		"CREATE TABLE {$p}playlist_items (id bigint unsigned NOT NULL AUTO_INCREMENT,playlist_id bigint unsigned NOT NULL,video_id bigint unsigned NOT NULL,sort_order int NOT NULL DEFAULT 0,version bigint unsigned NOT NULL DEFAULT 1,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY playlist_video(playlist_id,video_id),KEY playlist_order(playlist_id,sort_order)) $c",
		"CREATE TABLE {$p}media_assets (id bigint unsigned NOT NULL AUTO_INCREMENT,public_id varchar(80) NOT NULL,owner_id bigint unsigned NOT NULL DEFAULT 0,source_object_type varchar(32) NOT NULL DEFAULT 'video',source_object_id bigint unsigned NOT NULL DEFAULT 0,attachment_id bigint unsigned NOT NULL DEFAULT 0,media_class varchar(32) NOT NULL DEFAULT 'video',provider varchar(64) NOT NULL DEFAULT 'local',provider_ref varchar(191) NULL,source_url text NULL,checksum varchar(128) NULL,mime varchar(128) NULL,bytes bigint unsigned NOT NULL DEFAULT 0,duration_seconds int unsigned NOT NULL DEFAULT 0,status varchar(32) NOT NULL DEFAULT 'initiated',scan_status varchar(32) NOT NULL DEFAULT 'pending',rights_status varchar(32) NOT NULL DEFAULT 'declared',storage_json longtext NULL,derivatives_json longtext NULL,error_code varchar(80) NULL,error_message text NULL,version bigint unsigned NOT NULL DEFAULT 1,created_at datetime NOT NULL,updated_at datetime NOT NULL,deleted_at datetime NULL,PRIMARY KEY(id),UNIQUE KEY public_id(public_id),KEY owner_status(owner_id,status),KEY source(source_object_type,source_object_id),KEY provider_ref(provider,provider_ref)) $c",
		"CREATE TABLE {$p}processing_jobs (id bigint unsigned NOT NULL AUTO_INCREMENT,public_id varchar(80) NOT NULL,asset_id bigint unsigned NOT NULL,job_type varchar(64) NOT NULL,provider varchar(64) NOT NULL DEFAULT 'local',provider_job_ref varchar(191) NULL,status varchar(32) NOT NULL DEFAULT 'pending',priority int NOT NULL DEFAULT 100,attempts int unsigned NOT NULL DEFAULT 0,max_attempts int unsigned NOT NULL DEFAULT 5,available_at datetime NOT NULL,locked_at datetime NULL,locked_by varchar(80) NULL,input_json longtext NULL,output_json longtext NULL,error_code varchar(80) NULL,error_message text NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY public_id(public_id),KEY queue(status,available_at,priority),KEY asset(asset_id,job_type)) $c",
		"CREATE TABLE {$p}videos (id bigint unsigned NOT NULL AUTO_INCREMENT,public_id varchar(80) NOT NULL,channel_id bigint unsigned NOT NULL DEFAULT 0,asset_id bigint unsigned NOT NULL DEFAULT 0,owner_id bigint unsigned NOT NULL DEFAULT 0,title varchar(191) NOT NULL,slug varchar(191) NOT NULL,description longtext NULL,excerpt text NULL,topics_json longtext NULL,language varchar(20) NOT NULL DEFAULT 'en-US',provider varchar(64) NOT NULL DEFAULT 'local',source_url text NULL,embed_url text NULL,thumbnail_id bigint unsigned NOT NULL DEFAULT 0,duration_seconds int unsigned NOT NULL DEFAULT 0,visibility varchar(32) NOT NULL DEFAULT 'private',status varchar(32) NOT NULL DEFAULT 'draft',scheduled_at datetime NULL,published_at datetime NULL,consent_status varchar(32) NOT NULL DEFAULT 'not_patient_case',rights_status varchar(32) NOT NULL DEFAULT 'declared',rights_json longtext NULL,access_policy_json longtext NULL,view_count bigint unsigned NOT NULL DEFAULT 0,like_count bigint unsigned NOT NULL DEFAULT 0,dislike_count bigint unsigned NOT NULL DEFAULT 0,version bigint unsigned NOT NULL DEFAULT 1,created_at datetime NOT NULL,updated_at datetime NOT NULL,deleted_at datetime NULL,PRIMARY KEY(id),UNIQUE KEY public_id(public_id),UNIQUE KEY slug(slug),KEY status_visibility(status,visibility,published_at),KEY owner_status(owner_id,status),KEY channel_status(channel_id,status),KEY asset_id(asset_id)) $c",
		"CREATE TABLE {$p}captions (id bigint unsigned NOT NULL AUTO_INCREMENT,public_id varchar(80) NOT NULL,video_id bigint unsigned NOT NULL,language varchar(20) NOT NULL,kind varchar(32) NOT NULL DEFAULT 'captions',source varchar(32) NOT NULL DEFAULT 'manual',format varchar(16) NOT NULL DEFAULT 'vtt',content longtext NOT NULL,status varchar(32) NOT NULL DEFAULT 'review',quality_score decimal(5,2) NULL,version bigint unsigned NOT NULL DEFAULT 1,created_by bigint unsigned NOT NULL DEFAULT 0,reviewed_by bigint unsigned NOT NULL DEFAULT 0,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY public_id(public_id),UNIQUE KEY video_language_version(video_id,language,kind,version),KEY video_status(video_id,status)) $c",
		"CREATE TABLE {$p}live_events (id bigint unsigned NOT NULL AUTO_INCREMENT,public_id varchar(80) NOT NULL,channel_id bigint unsigned NOT NULL DEFAULT 0,owner_id bigint unsigned NOT NULL DEFAULT 0,title varchar(191) NOT NULL,slug varchar(191) NOT NULL,description longtext NULL,topics_json longtext NULL,language varchar(20) NOT NULL DEFAULT 'en-US',timezone varchar(64) NOT NULL DEFAULT 'UTC',provider varchar(64) NOT NULL DEFAULT 'manual',provider_event_ref varchar(191) NULL,visibility varchar(32) NOT NULL DEFAULT 'private',status varchar(32) NOT NULL DEFAULT 'draft',scheduled_start datetime NULL,scheduled_end datetime NULL,actual_start datetime NULL,actual_end datetime NULL,access_policy_json longtext NULL,chat_policy_json longtext NULL,recording_policy_json longtext NULL,provider_state_json longtext NULL,recording_asset_id bigint unsigned NOT NULL DEFAULT 0,replay_video_id bigint unsigned NOT NULL DEFAULT 0,kill_switch tinyint(1) NOT NULL DEFAULT 0,slow_mode_seconds int unsigned NOT NULL DEFAULT 0,version bigint unsigned NOT NULL DEFAULT 1,created_at datetime NOT NULL,updated_at datetime NOT NULL,deleted_at datetime NULL,PRIMARY KEY(id),UNIQUE KEY public_id(public_id),UNIQUE KEY slug(slug),KEY status_time(status,scheduled_start),KEY owner_status(owner_id,status),KEY provider_ref(provider,provider_event_ref)) $c",
		"CREATE TABLE {$p}stream_credentials (id bigint unsigned NOT NULL AUTO_INCREMENT,public_id varchar(80) NOT NULL,live_event_id bigint unsigned NOT NULL,provider varchar(64) NOT NULL DEFAULT 'manual',credential_hash varchar(255) NOT NULL,ingest_url text NULL,scope varchar(64) NOT NULL DEFAULT 'broadcast',status varchar(32) NOT NULL DEFAULT 'active',expires_at datetime NULL,rotated_at datetime NULL,revoked_at datetime NULL,created_by bigint unsigned NOT NULL DEFAULT 0,created_at datetime NOT NULL,last_used_at datetime NULL,PRIMARY KEY(id),UNIQUE KEY public_id(public_id),KEY event_status(live_event_id,status),KEY expiry(status,expires_at)) $c",
		"CREATE TABLE {$p}playback_sessions (id bigint unsigned NOT NULL AUTO_INCREMENT,public_id varchar(80) NOT NULL,user_id bigint unsigned NOT NULL DEFAULT 0,object_type varchar(32) NOT NULL,object_id bigint unsigned NOT NULL,token_hash varchar(255) NULL,quality varchar(32) NULL,progress_seconds int unsigned NOT NULL DEFAULT 0,duration_seconds int unsigned NOT NULL DEFAULT 0,completed tinyint(1) NOT NULL DEFAULT 0,ip_hash varchar(128) NULL,user_agent_hash varchar(128) NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,expires_at datetime NULL,PRIMARY KEY(id),UNIQUE KEY public_id(public_id),UNIQUE KEY user_object(user_id,object_type,object_id),KEY expiry(expires_at)) $c",
		"CREATE TABLE {$p}interactions (id bigint unsigned NOT NULL AUTO_INCREMENT,user_id bigint unsigned NOT NULL,video_id bigint unsigned NOT NULL,interaction varchar(32) NOT NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY user_video_type(user_id,video_id,interaction),KEY video_type(video_id,interaction)) $c",
		"CREATE TABLE {$p}moderation (id bigint unsigned NOT NULL AUTO_INCREMENT,public_id varchar(80) NOT NULL,target_type varchar(32) NOT NULL,target_id bigint unsigned NOT NULL,reason varchar(191) NOT NULL,action varchar(32) NOT NULL DEFAULT 'reported',status varchar(32) NOT NULL DEFAULT 'open',severity varchar(16) NOT NULL DEFAULT 'medium',note longtext NULL,evidence_json longtext NULL,reporter_id bigint unsigned NOT NULL DEFAULT 0,reviewer_id bigint unsigned NOT NULL DEFAULT 0,created_at datetime NOT NULL,updated_at datetime NOT NULL,closed_at datetime NULL,PRIMARY KEY(id),UNIQUE KEY public_id(public_id),KEY target_status(target_type,target_id,status),KEY queue(status,severity,created_at)) $c",
		"CREATE TABLE {$p}takedowns (id bigint unsigned NOT NULL AUTO_INCREMENT,public_id varchar(80) NOT NULL,target_type varchar(32) NOT NULL,target_id bigint unsigned NOT NULL,claimant_id bigint unsigned NOT NULL DEFAULT 0,claimant_contact_hash varchar(128) NULL,rights_basis varchar(191) NOT NULL,evidence_json longtext NULL,status varchar(32) NOT NULL DEFAULT 'reported',decision_reason longtext NULL,reviewer_id bigint unsigned NOT NULL DEFAULT 0,version bigint unsigned NOT NULL DEFAULT 1,created_at datetime NOT NULL,updated_at datetime NOT NULL,closed_at datetime NULL,PRIMARY KEY(id),UNIQUE KEY public_id(public_id),KEY target_status(target_type,target_id,status),KEY status_created(status,created_at)) $c",
		"CREATE TABLE {$p}audit (id bigint unsigned NOT NULL AUTO_INCREMENT,public_id varchar(80) NOT NULL,object_type varchar(32) NOT NULL,object_id varchar(80) NOT NULL,action varchar(64) NOT NULL,previous_state varchar(32) NULL,new_state varchar(32) NULL,actor_id bigint unsigned NOT NULL DEFAULT 0,purpose varchar(64) NOT NULL DEFAULT 'platform_operation',trace_id varchar(80) NOT NULL,note longtext NULL,meta_json longtext NULL,created_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY public_id(public_id),KEY object_action(object_type,object_id,action),KEY actor_created(actor_id,created_at),KEY trace_id(trace_id)) $c",
		"CREATE TABLE {$p}outbox (id bigint unsigned NOT NULL AUTO_INCREMENT,public_id varchar(80) NOT NULL,event_name varchar(100) NOT NULL,object_type varchar(32) NOT NULL,object_id varchar(80) NOT NULL,payload_json longtext NOT NULL,status varchar(32) NOT NULL DEFAULT 'pending',attempts int unsigned NOT NULL DEFAULT 0,available_at datetime NOT NULL,locked_at datetime NULL,last_error text NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,published_at datetime NULL,PRIMARY KEY(id),UNIQUE KEY public_id(public_id),KEY queue(status,available_at),KEY object_event(object_type,object_id,event_name)) $c",
		"CREATE TABLE {$p}inbox (id bigint unsigned NOT NULL AUTO_INCREMENT,event_id varchar(100) NOT NULL,event_name varchar(100) NOT NULL,payload_hash varchar(128) NOT NULL,status varchar(32) NOT NULL DEFAULT 'received',received_at datetime NOT NULL,processed_at datetime NULL,PRIMARY KEY(id),UNIQUE KEY event_id(event_id),KEY status_received(status,received_at)) $c",
		"CREATE TABLE {$p}webhooks (id bigint unsigned NOT NULL AUTO_INCREMENT,public_id varchar(80) NOT NULL,provider varchar(64) NOT NULL,event_id varchar(191) NOT NULL,event_type varchar(100) NOT NULL,signature_hash varchar(128) NULL,payload_hash varchar(128) NOT NULL,payload_json longtext NOT NULL,status varchar(32) NOT NULL DEFAULT 'received',attempts int unsigned NOT NULL DEFAULT 0,received_at datetime NOT NULL,processed_at datetime NULL,error_message text NULL,PRIMARY KEY(id),UNIQUE KEY public_id(public_id),UNIQUE KEY provider_event(provider,event_id),KEY queue(status,received_at)) $c",
		"CREATE TABLE {$p}idempotency (id bigint unsigned NOT NULL AUTO_INCREMENT,idempotency_key varchar(128) NOT NULL,scope varchar(100) NOT NULL,request_hash varchar(128) NOT NULL,status varchar(32) NOT NULL DEFAULT 'processing',response_json longtext NULL,created_at datetime NOT NULL,expires_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY key_scope(idempotency_key,scope),KEY expiry(expires_at)) $c",
		"CREATE TABLE {$p}rate_limits (id bigint unsigned NOT NULL AUTO_INCREMENT,limit_key varchar(128) NOT NULL,counter int unsigned NOT NULL DEFAULT 0,window_ends_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY limit_key(limit_key),KEY expiry(window_ends_at)) $c",
		"CREATE TABLE {$p}rollback_snapshots (id bigint unsigned NOT NULL AUTO_INCREMENT,public_id varchar(80) NOT NULL,snapshot_type varchar(64) NOT NULL,object_type varchar(32) NULL,object_id varchar(80) NULL,payload_json longtext NOT NULL,created_by bigint unsigned NOT NULL DEFAULT 0,created_at datetime NOT NULL,expires_at datetime NULL,PRIMARY KEY(id),UNIQUE KEY public_id(public_id),KEY object_ref(object_type,object_id),KEY expiry(expires_at)) $c"
		);
	}
	public static function verify_schema_sql($sql){global $wpdb;foreach((array)$sql as $statement){if(!preg_match('/CREATE\s+TABLE\s+([^\s(]+)/i',(string)$statement,$m))continue;$table=trim($m[1],'`');$found=$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$wpdb->esc_like($table)));if($found!==$table)return VWLB_Helpers::error('vwlb_schema_incomplete',__('A required File 10 database table is missing after migration.',VWLB_TEXT_DOMAIN),500,array('table'=>$table));}return true;}
	public static function install_schema() { require_once ABSPATH.'wp-admin/includes/upgrade.php'; $sql=self::schema_sql(); foreach($sql as $statement){ dbDelta($statement); } $verified=self::verify_schema_sql($sql);if(is_wp_error($verified))return $verified;if(!update_option('vwlb_schema_version',VWLB_SCHEMA_VERSION,false)&&get_option('vwlb_schema_version')!==VWLB_SCHEMA_VERSION)return VWLB_Helpers::error('vwlb_schema_version_persist_failed',__('File 10 schema version could not be recorded.',VWLB_TEXT_DOMAIN),500);return true; }
	public static function snapshot( $type, $payload, $object_type='', $object_id='' ) {
		global $wpdb;
		$inserted = $wpdb->insert(
			VWLB_Helpers::table( 'rollback_snapshots' ),
			array(
				'public_id' => VWLB_Helpers::public_id( 'snap' ),
				'snapshot_type' => sanitize_key( $type ),
				'object_type' => sanitize_key( $object_type ),
				'object_id' => (string) $object_id,
				'payload_json' => VWLB_Helpers::json_encode( $payload ),
				'created_by' => get_current_user_id(),
				'created_at' => VWLB_Helpers::now(),
				'expires_at' => gmdate( 'Y-m-d H:i:s', time() + 90 * DAY_IN_SECONDS ),
			)
		);
		if ( ! $inserted || ! $wpdb->insert_id ) {
			return VWLB_Helpers::error( 'vwlb_snapshot_persist_failed', __( 'The rollback snapshot could not be stored.', VWLB_TEXT_DOMAIN ), 500 );
		}
		return (int) $wpdb->insert_id;
	}
}
