<?php
/** Composition root. */
defined( 'ABSPATH' ) || exit;
final class VWLB_Plugin {
	private static $instance;
	public static function instance(){if(!self::$instance)self::$instance=new self();return self::$instance;}
	public function run(){load_plugin_textdomain(VWLB_TEXT_DOMAIN,false,dirname(plugin_basename(VWLB_FILE)).'/languages');VWLB_Providers::register_defaults();$frontend=new VWLB_Frontend();$admin=new VWLB_Admin();$privacy=new VWLB_Privacy();$integrations=new VWLB_Integrations();$rest=new VWLB_REST();$seo=new VWLB_SEO();$frontend->register();$integrations->register();add_action('wp_enqueue_scripts',array($frontend,'assets'));add_action('admin_enqueue_scripts',array($admin,'enqueue'));add_action('admin_menu',array($admin,'register'));add_action('rest_api_init',array($rest,'register'));add_filter('rest_pre_serve_request',array($this,'serve_raw_caption'),10,4);add_action('wp_head',array($seo,'output'));add_filter('wp_privacy_personal_data_exporters',array($privacy,'exporters'));add_filter('wp_privacy_personal_data_erasers',array($privacy,'erasers'));add_filter('wp_get_default_privacy_policy_content',array($privacy,'policy'));add_action('template_redirect',array($privacy,'private_headers'));add_action('admin_notices',array('VWLB_Compatibility','legacy_notice'));add_filter('cron_schedules',array($this,'cron_schedules'));add_action('vwlb_process_jobs',array('VWLB_Jobs','process'));add_action('vwlb_publish_outbox',array('VWLB_Jobs','publish_outbox'));add_action('vwlb_reconcile_states',array('VWLB_Jobs','reconcile'));add_action('vwlb_cleanup',array('VWLB_Jobs','cleanup'));add_action('init',array($this,'rewrite'));add_filter('query_vars',array($this,'query_vars'));add_filter('template_include',array($this,'route_template'));add_action('wp_enqueue_scripts',array($this,'enqueue_route_assets'),20);if(get_option('vwlb_schema_version')!==VWLB_SCHEMA_VERSION)VWLB_DB::install_schema();}
	public function cron_schedules($s){$s['vwlb_five_minutes']=array('interval'=>300,'display'=>__('Every five minutes',VWLB_TEXT_DOMAIN));return $s;}
	public function rewrite(){add_rewrite_rule('^video/([A-Za-z0-9_-]+)/([^/]+)/?$','index.php?vwlb_video_id=$matches[1]','top');add_rewrite_rule('^live/([A-Za-z0-9_-]+)/?$','index.php?vwlb_live_id=$matches[1]','top');}
	public function query_vars($vars){$vars[]='vwlb_video_id';$vars[]='vwlb_live_id';return $vars;}
	public function serve_raw_caption($served,$result,$request,$server){if(str_starts_with($request->get_route(),'/'.VWLB_Contracts::API_NAMESPACE.'/captions/')&&$result instanceof WP_REST_Response&&!is_array($result->get_data())){echo (string)$result->get_data();return true;}return $served;}
	public function enqueue_route_assets(){if(get_query_var('vwlb_video_id')||get_query_var('vwlb_live_id')){wp_enqueue_style('vwlb');wp_enqueue_script('vwlb');}}
	public function route_template($template){if(get_query_var('vwlb_video_id')||get_query_var('vwlb_live_id')){status_header(200);return VWLB_DIR.'templates/route.php';}return $template;}
}
