<?php
/** R1 hardening façade for bounded Future queries, polls and scheduled reconciliation. */
defined( 'ABSPATH' ) || exit;
final class VWLB_Future_Safety {
	public static function register(){
		add_action('rest_api_init',array(__CLASS__,'register_rest_overrides'),20);
		remove_action('vwlb_reconcile_states',array('VWLB_Future_Intelligence','reconcile_consent_expiry'),20);
		remove_action('vwlb_cleanup',array('VWLB_Future_Intelligence','cleanup'),30);
		add_action('vwlb_reconcile_states',array(__CLASS__,'reconcile_consent_expiry'),20);
		add_action('vwlb_cleanup',array(__CLASS__,'cleanup'),30);
	}

	private static function response($value,$status=200){if(is_wp_error($value))return $value;$r=rest_ensure_response($value);$r->set_status($status);$r->header('X-Sabri-File','10');$r->header('X-VWLB-Version',VWLB_VERSION);$r->header('X-VWLB-Future','24');return $r;}
	private static function annotation_dto($row){if(is_wp_error($row)||!is_array($row))return $row;$keys=array('public_id','kind','start_ms','end_ms','title','body','source_owner','source_ref','status','version','created_at','updated_at');$out=array();foreach($keys as $key)if(array_key_exists($key,$row))$out[$key]=$row[$key];return $out;}
	public static function register_rest_overrides(){foreach(VWLB_Contracts::namespaces() as $n){
		register_rest_route($n,'/videos/(?P<id>[A-Za-z0-9_-]+)/playback',array('methods'=>'GET','callback'=>array(__CLASS__,'rest_playback'),'permission_callback'=>'__return_true'),true);
		register_rest_route($n,'/live-events/(?P<id>[A-Za-z0-9_-]+)',array('methods'=>'GET','callback'=>array(__CLASS__,'rest_live'),'permission_callback'=>'__return_true'),true);
		register_rest_route($n,'/live-events/(?P<id>[A-Za-z0-9_-]+)/polls',array('methods'=>'POST','callback'=>array(__CLASS__,'rest_poll_create'),'permission_callback'=>function(){return VWLB_Security::can(VWLB_Contracts::CAP_BROADCAST);}),true);
		register_rest_route($n,'/videos/(?P<id>[A-Za-z0-9_-]+)/annotations',array(
			array('methods'=>'GET','callback'=>array(__CLASS__,'rest_annotations'),'permission_callback'=>'__return_true'),
			array('methods'=>'POST','callback'=>array(__CLASS__,'rest_annotation_create'),'permission_callback'=>function(){return VWLB_Security::can(VWLB_Contracts::CAP_PUBLISH);}),
		),true);
	}}
	public static function rest_playback(WP_REST_Request $r){$payload=VWLB_Videos::playback($r['id']);if(!is_wp_error($payload)&&is_array($payload)){$payload['chapters']=VWLB_Extensions::chapters('video',$payload['video']['id']??0);$payload['media_tracks']=self::published_tracks('video',$payload['video']['id']??0);$payload['preferences']=array('autoplay'=>false,'low_bandwidth'=>(bool)($r['low_bandwidth']??false),'reduced_motion'=>false);}$response=self::response($payload);if(!is_wp_error($response))$response->header('Cache-Control','private, no-store');return $response;}
	public static function rest_live(WP_REST_Request $r){$state=VWLB_Live::state($r['id']);if(!is_wp_error($state)){$event=VWLB_Repository::find('live_events',$r['id']);$state['experience']=VWLB_Extensions::live_extras($event);$state['media_tracks']=$event?self::published_tracks('live',$event['id']):array();}$response=self::response($state);if(!is_wp_error($response))$response->header('Cache-Control','private, no-store');return $response;}
	public static function rest_poll_create(WP_REST_Request $r){$data=$r->get_json_params();return self::response(self::create_poll($r['id'],is_array($data)?$data:array()),201);}
	public static function rest_annotations(WP_REST_Request $r){return self::response(self::annotations($r['id'],!empty($r['include_candidates'])));}
	public static function rest_annotation_create(WP_REST_Request $r){$data=$r->get_json_params();return self::response(self::annotation_dto(VWLB_Future_Intelligence::create_annotation($r['id'],is_array($data)?$data:array())),201);}

	private static function video($id){$v=VWLB_Repository::find('videos',$id);return $v&&is_array($v)?$v:null;}
	private static function live($id){$e=VWLB_Repository::find('live_events',$id);return $e&&is_array($e)?$e:null;}
	public static function published_tracks($object_type,$object_id){
		$object_type=VWLB_Helpers::enum($object_type,array('video','live'),'');$object='video'===$object_type?self::video($object_id):('live'===$object_type?self::live($object_id):null);if(!$object||!VWLB_Security::can_view($object))return array();
		global $wpdb;$rows=$wpdb->get_results($wpdb->prepare('SELECT public_id,track_type,language,source,file_ref,provider_ref,version FROM '.VWLB_Helpers::table('media_tracks').' WHERE object_type=%s AND object_id=%d AND status=%s ORDER BY track_type ASC, language ASC, id ASC LIMIT 100',$object_type,(int)$object['id'],'published'),ARRAY_A);$out=array();
		foreach((array)$rows as $row){$resolved=apply_filters('vwlb_public_media_track_ref','',$row,$object);$src=esc_url_raw(is_string($resolved)?$resolved:'');$out[]=array('public_id'=>$row['public_id'],'track_type'=>$row['track_type'],'language'=>$row['language'],'source'=>$row['source'],'src'=>$src,'available'=>(bool)$src,'version'=>(int)$row['version']);}return $out;
	}
	public static function annotations($video_id,$include_candidates=false){
		$video=self::video($video_id);if(!$video||!VWLB_Security::can_view($video))return VWLB_Helpers::error('vwlb_not_found',__('Video not found.',VWLB_TEXT_DOMAIN),404);global $wpdb;$table=VWLB_Helpers::table('video_annotations');$can_internal=$include_candidates&&VWLB_Security::can(VWLB_Contracts::CAP_REVIEW,$video,'future_annotation_list');$statuses=$can_internal?"('candidate','reviewed','published')":"('published')";$items=$wpdb->get_results($wpdb->prepare("SELECT public_id,kind,start_ms,end_ms,title,body,source_owner,source_ref,status,metadata_json,version FROM $table WHERE video_id=%d AND status IN $statuses ORDER BY start_ms ASC,id ASC LIMIT 500",$video['id']),ARRAY_A);foreach($items as &$i){if($can_internal)$i['metadata']=VWLB_Helpers::json($i['metadata_json']);unset($i['metadata_json']);}return array('items'=>$items,'truncated'=>count((array)$items)>=500);
	}
	public static function create_poll($live_id,$data){
		$data=is_array($data)?$data:array();$normalized=array();foreach((array)($data['options']??array()) as $option){$raw=is_array($option)?$option:array('text'=>$option);$text=VWLB_Helpers::text($raw['text']??'',255);if(''===$text)continue;$normalized[]=array('text'=>$text,'is_correct'=>!empty($raw['is_correct']));}
		if(count($normalized)>20)return VWLB_Helpers::error('vwlb_poll_too_many_options',__('A live poll may contain at most 20 options.',VWLB_TEXT_DOMAIN),422);if(count($normalized)<2)return VWLB_Helpers::error('vwlb_poll_fields_required',__('A question and at least two options are required.',VWLB_TEXT_DOMAIN),422);$type=VWLB_Helpers::enum($data['poll_type']??'single',array('single','multiple','knowledge_check'),'single');if('knowledge_check'===$type&&!array_filter($normalized,function($o){return !empty($o['is_correct']);}))return VWLB_Helpers::error('vwlb_poll_correct_answer_required',__('A knowledge check requires at least one reviewed correct option.',VWLB_TEXT_DOMAIN),422);$data['poll_type']=$type;$data['options']=$normalized;return VWLB_Future_Intelligence::create_poll($live_id,$data);
	}
	private static function restrict_video_for_consent($video,$reason){if(in_array($video['status'],array('removed','restricted'),true))return false;$updated=VWLB_Repository::update_versioned('videos',$video['id'],$video['version'],array('status'=>'restricted'));if(is_wp_error($updated))return $updated;VWLB_Helpers::audit('video',$video['id'],'consent_auto_restrict',$video['status'],'restricted',$reason);VWLB_Helpers::outbox('VideoRestricted','video',$video['id'],array('reason'=>'consent_'.$reason));return true;}
	public static function reconcile_consent_expiry(){
		global $wpdb;$table=VWLB_Helpers::table('consent_links');$rows=$wpdb->get_results($wpdb->prepare("SELECT id FROM $table WHERE status='active' AND expires_at IS NOT NULL AND expires_at<=%s ORDER BY id ASC LIMIT 100",VWLB_Helpers::now()),ARRAY_A);foreach((array)$rows as $candidate){$result=VWLB_DB::transaction(function()use($wpdb,$table,$candidate){$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM $table WHERE id=%d FOR UPDATE",$candidate['id']),ARRAY_A);if(!$row||'active'!==$row['status']||!$row['expires_at']||strtotime($row['expires_at'].' UTC')>time())return array('changed'=>false);$video=VWLB_Repository::find('videos',$row['video_id'],true);if(!$video)return VWLB_Helpers::error('vwlb_video_missing',__('Consent-linked video is missing.',VWLB_TEXT_DOMAIN),409);$changed=$wpdb->update($table,array('status'=>'expired','version'=>(int)$row['version']+1,'updated_at'=>VWLB_Helpers::now()),array('id'=>$row['id'],'version'=>$row['version'],'status'=>'active'));if(1!==$changed)return VWLB_Helpers::error('vwlb_version_conflict',__('Consent expiry changed concurrently.',VWLB_TEXT_DOMAIN),409);$restricted=self::restrict_video_for_consent($video,'expired');if(is_wp_error($restricted))return $restricted;return array('changed'=>true,'restricted'=>(bool)$restricted,'video_public_id'=>$video['public_id']);});if(is_wp_error($result)){do_action('vwlb_operational_failure','consent_expiry',$result->get_error_code(),array('consent_id'=>(int)$candidate['id']));continue;}if(!empty($result['restricted']))do_action('vwlb_purge_media_derivative_caches',$result['video_public_id'],'consent_expired');}
	}
	public static function cleanup(){
		global $wpdb;$health=VWLB_Helpers::table('broadcast_health_samples');$deleted=$wpdb->query($wpdb->prepare("DELETE FROM $health WHERE captured_at<%s LIMIT 5000",gmdate('Y-m-d H:i:s',time()-7*DAY_IN_SECONDS)));if(false===$deleted)do_action('vwlb_operational_failure','future_cleanup','vwlb_health_cleanup_failed',array());$guests=VWLB_Helpers::table('broadcast_guests');$expired=$wpdb->get_results($wpdb->prepare("SELECT * FROM $guests WHERE status IN ('invited','accepted') AND expires_at<=%s ORDER BY id ASC LIMIT 500",VWLB_Helpers::now()),ARRAY_A);foreach((array)$expired as $guest){$changed=$wpdb->update($guests,array('status'=>'expired','version'=>(int)$guest['version']+1,'updated_at'=>VWLB_Helpers::now()),array('id'=>$guest['id'],'version'=>$guest['version'],'status'=>$guest['status']));if(1===$changed){VWLB_Helpers::audit('broadcast_guest',$guest['id'],'expire',$guest['status'],'expired','delegation_ttl',array('live_event_id'=>$guest['live_event_id'],'guest_user_id'=>$guest['user_id']));VWLB_Helpers::outbox('BroadcastGuestExpired','live',$guest['live_event_id'],array('guest_user_id'=>(int)$guest['user_id'],'guest_public_id'=>$guest['public_id']));}elseif(false===$changed){do_action('vwlb_operational_failure','future_cleanup','vwlb_guest_expiry_persist_failed',array('guest_public_id'=>$guest['public_id']));}}
	}
}
