<?php
/** R113: provider outputs are typed and security-revalidated after every provider/filter extension point. */
defined('ABSPATH') || exit;
final class VWLB_R113_Validated_Provider implements VWLB_Provider_Interface {
	private $inner;private $provider_id;
	public function __construct($inner){$this->inner=$inner;$this->provider_id=sanitize_key((string)$inner->id());}
	public function id(){return $this->provider_id;}
	private function error($code,$message,$extra=array()){do_action('vwlb_operational_failure','provider',$code,array_merge(array('provider'=>$this->provider_id),$extra));return VWLB_Helpers::error($code,$message,503,array_merge(array('provider'=>$this->provider_id),$extra));}
	private static function remote_url($url){$url=esc_url_raw((string)$url,array('https'));if(!$url)return '';$p=wp_parse_url($url);$host=strtolower((string)($p['host']??''));$scheme=strtolower((string)($p['scheme']??''));$port=isset($p['port'])?(int)$p['port']:443;if('https'!==$scheme||!$host||443!==$port||isset($p['user'])||isset($p['pass']))return '';if(in_array($host,array('localhost','localhost.localdomain','metadata.google.internal'),true)||str_ends_with($host,'.local')||str_ends_with($host,'.internal'))return '';if(filter_var($host,FILTER_VALIDATE_IP)){if(false===filter_var($host,FILTER_VALIDATE_IP,FILTER_FLAG_NO_PRIV_RANGE|FILTER_FLAG_NO_RES_RANGE))return '';}return $url;}
	private function validate_normalized($value){if(is_wp_error($value))return $value;if(!is_array($value))return $this->error('vwlb_provider_source_contract_invalid',__('Media provider returned an invalid source contract.',VWLB_TEXT_DOMAIN));$provider=sanitize_key((string)($value['provider']??$this->provider_id));if($provider!==$this->provider_id)return $this->error('vwlb_provider_source_contract_invalid',__('Media provider source ownership did not match the selected provider.',VWLB_TEXT_DOMAIN));foreach(array('source_url','embed_url') as $key){if(empty($value[$key]))continue;$url=self::remote_url($value[$key]);if(!$url)return $this->error('vwlb_provider_source_url_invalid',__('Media provider returned an unsafe source URL.',VWLB_TEXT_DOMAIN),array('field'=>$key));$value[$key]=$url;}return $value;}
	private function compensate_ingest($event,$ingest,$code){$context=array('provider'=>$this->provider_id,'live_public_id'=>VWLB_Helpers::text($event['public_id']??'',80),'provider_ref'=>VWLB_Helpers::text($ingest['provider_ref']??'',191),'reason'=>sanitize_key($code));try{$result=apply_filters('vwlb_provider_revoke_ingest_result',null,$context);}catch(Throwable $e){$result=null;} $confirmed=true===$result||(is_array($result)&&in_array(sanitize_key((string)($result['status']??'')),array('revoked','deleted','disabled','rotated','not_found'),true));if(!$confirmed)return $this->error('vwlb_provider_ingest_reconcile_required',__('Provider ingest output was unsafe and provider revocation could not be confirmed. Reconciliation is required.',VWLB_TEXT_DOMAIN),array('reconcile_required'=>true,'live_public_id'=>$context['live_public_id']));return $this->error($code,__('Provider ingest output failed File 10 security validation and was compensated.',VWLB_TEXT_DOMAIN));}
	public function capabilities(){return (array)$this->inner->capabilities();}
	public function normalize_source($source){return $this->validate_normalized($this->inner->normalize_source($source));}
	public function create_live($event){$value=$this->inner->create_live($event);if(is_wp_error($value))return $value;if(!is_array($value))return $this->error('vwlb_provider_live_reconcile_required',__('The provider returned an invalid live-event result. Its external outcome is uncertain and requires reconciliation.',VWLB_TEXT_DOMAIN),array('reconcile_required'=>true,'live_public_id'=>VWLB_Helpers::text($event['public_id']??'',80)));$safe=array();foreach(array('provider_event_ref','status','degraded','region') as $key)if(array_key_exists($key,$value))$safe[$key]=$value[$key];return $safe;}
	public function issue_ingest($event){$value=$this->inner->issue_ingest($event);if(is_wp_error($value))return $value;if(!is_array($value))return $this->error('vwlb_provider_ingest_reconcile_required',__('The provider returned an invalid ingest result. Its external outcome is uncertain and requires reconciliation.',VWLB_TEXT_DOMAIN),array('reconcile_required'=>true,'live_public_id'=>VWLB_Helpers::text($event['public_id']??'',80)));$url=self::remote_url($value['ingest_url']??'');if(!$url)return $this->compensate_ingest($event,$value,'vwlb_provider_ingest_url_invalid');$value['ingest_url']=$url;if(array_key_exists('stream_key',$value)){if(!is_scalar($value['stream_key']))return $this->compensate_ingest($event,$value,'vwlb_provider_stream_secret_invalid');$secret=(string)$value['stream_key'];if(strlen($secret)<16||strlen($secret)>512||preg_match('/[\x00-\x1F\x7F]/',$secret))return $this->compensate_ingest($event,$value,'vwlb_provider_stream_secret_invalid');$value['stream_key']=$secret;}if(isset($value['provider_ref']))$value['provider_ref']=VWLB_Helpers::text($value['provider_ref'],191);return $value;}
	public function playback($object,$viewer){$value=$this->inner->playback($object,$viewer);if(is_wp_error($value))return $value;if(!is_array($value)||empty($value['url']))return $this->error('vwlb_provider_playback_contract_invalid',__('Media provider returned an invalid playback contract.',VWLB_TEXT_DOMAIN));$url=self::remote_url($value['url']);if(!$url)return $this->error('vwlb_provider_playback_url_invalid',__('Media provider returned an unsafe playback URL.',VWLB_TEXT_DOMAIN));if('youtube'===$this->provider_id&&'www.youtube-nocookie.com'!==strtolower((string)wp_parse_url($url,PHP_URL_HOST)))return $this->error('vwlb_provider_playback_url_invalid',__('YouTube playback must remain on the approved privacy-enhanced host.',VWLB_TEXT_DOMAIN));if('vimeo'===$this->provider_id&&'player.vimeo.com'!==strtolower((string)wp_parse_url($url,PHP_URL_HOST)))return $this->error('vwlb_provider_playback_url_invalid',__('Vimeo playback must remain on the approved player host.',VWLB_TEXT_DOMAIN));$value['url']=$url;return $value;}
	public function process_asset($asset,$job){$value=$this->inner->process_asset($asset,$job);if(is_wp_error($value))return $value;if(!is_array($value))return $this->error('vwlb_provider_processing_contract_invalid',__('Media processor returned an invalid result contract.',VWLB_TEXT_DOMAIN));if(isset($value['derivatives'])&&!is_array($value['derivatives']))return $this->error('vwlb_provider_processing_contract_invalid',__('Media processor returned invalid derivative metadata.',VWLB_TEXT_DOMAIN));foreach((array)($value['derivatives']??array()) as $key=>$url){if(!in_array(sanitize_key((string)$key),array('hls','hls_low','mp4','mp4_high','mp4_low','audio_only','mp3','poster','storyboard'),true))continue;if(!is_scalar($url)||!self::remote_url((string)$url))return $this->error('vwlb_provider_derivative_url_invalid',__('Media processor returned an unsafe derivative URL.',VWLB_TEXT_DOMAIN),array('derivative'=>sanitize_key((string)$key)));$value['derivatives'][$key]=self::remote_url((string)$url);}return $value;}
	public function verify_webhook($headers,$body){return (bool)$this->inner->verify_webhook($headers,$body);}
	public function reconcile($object_type,$object){$value=$this->inner->reconcile($object_type,$object);if(is_wp_error($value))return $value;return is_array($value)?$value:$this->error('vwlb_provider_reconcile_contract_invalid',__('Media provider returned an invalid reconciliation result.',VWLB_TEXT_DOMAIN));}
}
final class VWLB_R113_Provider_Output_Guard {
	public static function register(){foreach(VWLB_Providers::all() as $provider){if($provider instanceof VWLB_R113_Validated_Provider)continue;VWLB_Providers::register(new VWLB_R113_Validated_Provider($provider));}}
}
