<?php
/** R112: fail-closed live attendance, reminder reconciliation and execution-time reminder truth. */
defined('ABSPATH') || exit;
final class VWLB_R112_Live_Attendance_Durability_Guard {
	public static function register(){
		add_filter('rest_request_before_callbacks',array(__CLASS__,'before'),19,3);
		add_filter('rest_request_after_callbacks',array(__CLASS__,'after'),8,3);
		remove_filter('vwlb_process_job',array('VWLB_Extensions','process_job'),10);
		add_filter('vwlb_process_job',array(__CLASS__,'process_job'),10,3);
	}
	private static function route_kind($request){
		if(!$request instanceof WP_REST_Request)return '';$method=strtoupper((string)$request->get_method());$route=(string)$request->get_route();
		foreach(VWLB_Contracts::namespaces() as $n){$q=preg_quote($n,'#');
			if('POST'===$method&&preg_match('#^/'.$q.'/live-events/([A-Za-z0-9_-]+)/waiting-room$#',$route))return 'waiting';
			if('POST'===$method&&preg_match('#^/'.$q.'/live-events/([A-Za-z0-9_-]+)/recording-consent$#',$route))return 'consent';
			if('POST'===$method&&'/'.$n.'/live-events'===$route)return 'schedule';
			if('POST'===$method&&'/'.$n.'/premieres'===$route)return 'premiere';
		}return '';
	}
	private static function response($value,$status=200){if(is_wp_error($value))return $value;$r=rest_ensure_response($value);$r->set_status($status);$r->header('X-Sabri-File','10');$r->header('X-VWLB-Version',VWLB_VERSION);$r->header('X-VWLB-Canonical-API',VWLB_Contracts::CANONICAL_API_NAMESPACE);return $r;}
	private static function body($request){$d=$request->get_json_params();return is_array($d)?$d:array();}
	private static function reminders($data){$raw=array_key_exists('reminders',$data)?(array)$data['reminders']:array(1440,60,15);$out=array();foreach($raw as $value){$m=absint($value);if($m>0&&$m<=10080)$out[$m]=$m;}return array_values($out);}
	private static function preflight_schedule($data){$raw=array_key_exists('reminders',$data)?(array)$data['reminders']:array(1440,60,15);if(count($raw)>32)return VWLB_Helpers::error('vwlb_live_reminder_limit',__('Too many live reminders were requested.',VWLB_TEXT_DOMAIN),422);foreach($raw as $value){if(!is_numeric($value)||absint($value)<1||absint($value)>10080)return VWLB_Helpers::error('vwlb_live_reminder_invalid',__('Live reminder minutes must be between 1 and 10080.',VWLB_TEXT_DOMAIN),422);}return true;}
	public static function before($response,$handler,$request){
		if(null!==$response)return $response;$kind=self::route_kind($request);if(!$kind)return $response;$data=self::body($request);
		if(in_array($kind,array('schedule','premiere'),true)){ $valid=self::preflight_schedule($data);return is_wp_error($valid)?$valid:$response; }
		if('waiting'===$kind)return self::waiting_room($request,$data);
		if('consent'===$kind)return self::recording_consent($request,$data);
		return $response;
	}
	private static function waiting_room($request,$data){
		if(!is_user_logged_in())return VWLB_Helpers::error('vwlb_login_required',__('Sign in to join the waiting room.',VWLB_TEXT_DOMAIN),401);
		VWLB_Repository::reset_read_failure();$event=VWLB_Repository::find('live_events',$request['id']);if(VWLB_Repository::read_failed())return VWLB_Helpers::error('vwlb_waiting_room_state_unreadable',__('Live waiting-room state could not be verified safely.',VWLB_TEXT_DOMAIN),503);if(!$event||!VWLB_Security::can_view($event,'waiting_room'))return VWLB_Helpers::error('vwlb_not_found',__('Live event not found.',VWLB_TEXT_DOMAIN),404);
		if(!in_array($event['status'],array('scheduled','rehearsal','ready','live'),true))return VWLB_Helpers::error('vwlb_waiting_room_closed',__('The waiting room is closed.',VWLB_TEXT_DOMAIN),409);
		return self::response(VWLB_DB::transaction(function()use($event,$data){global $wpdb;$events=VWLB_Helpers::table('live_events');$wpdb->last_error='';$fresh=$wpdb->get_row($wpdb->prepare("SELECT * FROM $events WHERE id=%d FOR UPDATE",$event['id']),ARRAY_A);if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_waiting_room_state_unreadable',__('Live waiting-room state could not be verified safely.',VWLB_TEXT_DOMAIN),503);if(!$fresh||!VWLB_Security::can_view($fresh,'waiting_room'))return VWLB_Helpers::error('vwlb_not_found',__('Live event not found.',VWLB_TEXT_DOMAIN),404);if(!in_array($fresh['status'],array('scheduled','rehearsal','ready','live'),true))return VWLB_Helpers::error('vwlb_waiting_room_closed',__('The waiting room is closed.',VWLB_TEXT_DOMAIN),409);
			$policy=VWLB_Helpers::json($fresh['access_policy_json']??'{}');if(array_key_exists('waiting_room',$policy)&&empty($policy['waiting_room']))return VWLB_Helpers::error('vwlb_waiting_room_disabled',__('The waiting room is disabled for this event.',VWLB_TEXT_DOMAIN),409);$capacity=max(0,min(100000,(int)($policy['capacity']??0)));$table=VWLB_Helpers::table('live_attendees');$uid=get_current_user_id();$wpdb->last_error='';$existing=$wpdb->get_row($wpdb->prepare("SELECT * FROM $table WHERE live_event_id=%d AND user_id=%d FOR UPDATE",$fresh['id'],$uid),ARRAY_A);if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_waiting_room_state_unreadable',__('Live attendee state could not be verified safely.',VWLB_TEXT_DOMAIN),503);
			$already_active=$existing&&in_array($existing['state']??'',array('waiting','approved','joined'),true);if(!$already_active&&$capacity>0){$wpdb->last_error='';$count=$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM $table WHERE live_event_id=%d AND state IN ('waiting','approved','joined')",$fresh['id']));if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_waiting_room_capacity_unreadable',__('Live-event capacity could not be verified safely.',VWLB_TEXT_DOMAIN),503);if((int)$count>=$capacity)return VWLB_Helpers::error('vwlb_live_capacity_reached',__('This live event has reached capacity.',VWLB_TEXT_DOMAIN),409);}
			$state='live'===$fresh['status']?'joined':'waiting';$reminder=max(0,min(1440,(int)($data['reminder_minutes']??15)));$now=VWLB_Helpers::now();if($existing){$changed=$wpdb->update($table,array('state'=>$state,'reminder_minutes'=>$reminder,'joined_at'=>'joined'===$state?$now:($existing['joined_at']??null),'version'=>(int)$existing['version']+1,'updated_at'=>$now),array('id'=>$existing['id'],'version'=>$existing['version']));if(1!==$changed)return VWLB_Helpers::error('vwlb_waiting_room_conflict',__('Waiting-room state changed concurrently. Retry safely.',VWLB_TEXT_DOMAIN),409);$id=(int)$existing['id'];$public=(string)($existing['public_id']??'');$consent=!empty($existing['recording_consent']);}else{$public=VWLB_Helpers::public_id('att');$saved=$wpdb->insert($table,array('public_id'=>$public,'live_event_id'=>$fresh['id'],'user_id'=>$uid,'state'=>$state,'reminder_minutes'=>$reminder,'recording_consent'=>0,'consent_version'=>'','joined_at'=>'joined'===$state?$now:null,'version'=>1,'created_at'=>$now,'updated_at'=>$now));if(!$saved||!(int)$wpdb->insert_id)return VWLB_Helpers::error('vwlb_database_error',__('Waiting-room attendance could not be saved.',VWLB_TEXT_DOMAIN),500);$id=(int)$wpdb->insert_id;$consent=false;}VWLB_Helpers::audit('live_attendee',$id,'waiting_room_join','',$state,'',array('live_event_id'=>$fresh['id']));return array('attendee_public_id'=>$public,'state'=>$state,'reminder_minutes'=>$reminder,'recording_consent'=>$consent);
		}));
	}
	private static function recording_consent($request,$data){
		if(!is_user_logged_in())return VWLB_Helpers::error('vwlb_login_required',__('Sign in first.',VWLB_TEXT_DOMAIN),401);VWLB_Repository::reset_read_failure();$event=VWLB_Repository::find('live_events',$request['id']);if(VWLB_Repository::read_failed())return VWLB_Helpers::error('vwlb_recording_consent_unverifiable',__('Recording consent state could not be verified safely.',VWLB_TEXT_DOMAIN),503);if(!$event||!VWLB_Security::can_view($event,'recording_consent'))return VWLB_Helpers::error('vwlb_not_found',__('Live event not found.',VWLB_TEXT_DOMAIN),404);$policy=VWLB_Helpers::json($event['recording_policy_json']??'{}');$required=VWLB_Helpers::text($policy['consent_version']??'v1',64);$consent=!empty($data['consent']);$submitted=VWLB_Helpers::text($data['consent_version']??'',64);if($consent&&!$submitted)return VWLB_Helpers::error('vwlb_recording_consent_version_required',__('Recording consent requires the explicit current consent-text version.',VWLB_TEXT_DOMAIN),422);if($consent&&!hash_equals($required,$submitted))return VWLB_Helpers::error('vwlb_recording_consent_version_stale',__('The recording-consent text changed. Review the current policy before consenting.',VWLB_TEXT_DOMAIN),409,array('required_consent_version'=>$required));
		return self::response(VWLB_DB::transaction(function()use($event,$consent,$required){global $wpdb;$table=VWLB_Helpers::table('live_attendees');$wpdb->last_error='';$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM $table WHERE live_event_id=%d AND user_id=%d FOR UPDATE",$event['id'],get_current_user_id()),ARRAY_A);if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_recording_consent_unverifiable',__('Recording consent state could not be verified safely.',VWLB_TEXT_DOMAIN),503);if(!$row)return VWLB_Helpers::error('vwlb_attendee_missing',__('Join the waiting room before setting recording consent.',VWLB_TEXT_DOMAIN),409);$now=VWLB_Helpers::now();$changed=$wpdb->update($table,array('recording_consent'=>$consent?1:0,'consent_version'=>$required,'consented_at'=>$now,'version'=>(int)$row['version']+1,'updated_at'=>$now),array('id'=>$row['id'],'version'=>$row['version']));if(1!==$changed)return VWLB_Helpers::error('vwlb_recording_consent_conflict',__('Recording consent changed concurrently. Refresh and try again.',VWLB_TEXT_DOMAIN),409);VWLB_Helpers::audit('live_attendee',$row['id'],'recording_consent_change',$row['recording_consent']?'yes':'no',$consent?'yes':'no','',array('live_event_id'=>$event['id'],'purpose'=>'recording_consent','consent_version'=>$required));VWLB_Helpers::outbox('LiveRecordingConsentChanged','live',$event['id'],array('attendee_public_id'=>$row['public_id'],'consented'=>$consent,'consent_version'=>$required));return array('recording_consent'=>$consent,'consent_version'=>$required,'consented_at'=>VWLB_Helpers::iso_utc($now));}));
	}
	public static function after($response,$handler,$request){
		$kind=self::route_kind($request);if(!in_array($kind,array('schedule','premiere'),true)||is_wp_error($response))return $response;$wrapped=rest_ensure_response($response);if((int)$wrapped->get_status()>=400)return $response;$data=$wrapped->get_data();if(!is_array($data))return $response;$public='schedule'===$kind?VWLB_Helpers::text($data['public_id']??'',80):VWLB_Helpers::text($data['live_public_id']??'',80);if(!$public)return $response;VWLB_Repository::reset_read_failure();$event=VWLB_Repository::find('live_events',$public);if(VWLB_Repository::read_failed())return VWLB_Helpers::error('vwlb_provider_live_reconcile_required',__('Live-event reminder state became unreadable after provider/local creation; reconciliation is required.',VWLB_TEXT_DOMAIN),503,array('reconcile_required'=>true));if(!$event)return VWLB_Helpers::error('vwlb_provider_live_reconcile_required',__('Live-event reminder state could not be reconciled after creation.',VWLB_TEXT_DOMAIN),503,array('reconcile_required'=>true));$ok=self::reconcile_reminders($event,self::body($request));if(is_wp_error($ok))return $ok;return $response;
	}
	private static function reconcile_reminders($event,$data){
		return VWLB_DB::transaction(function()use($event,$data){global $wpdb;$events=VWLB_Helpers::table('live_events');$jobs=VWLB_Helpers::table('processing_jobs');$wpdb->last_error='';$fresh=$wpdb->get_row($wpdb->prepare("SELECT * FROM $events WHERE id=%d FOR UPDATE",$event['id']),ARRAY_A);if(''!==(string)$wpdb->last_error||!$fresh)return VWLB_Helpers::error('vwlb_provider_live_reconcile_required',__('Live-event reminder state could not be locked for reconciliation.',VWLB_TEXT_DOMAIN),503,array('reconcile_required'=>true));$after=0;do{$wpdb->last_error='';$rows=$wpdb->get_results($wpdb->prepare("SELECT id,input_json FROM $jobs WHERE job_type='send_live_reminder' AND asset_id=0 AND status IN ('pending','retry') AND id>%d ORDER BY id ASC LIMIT 200",$after),ARRAY_A);if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_provider_live_reconcile_required',__('Existing live reminders could not be read safely for reconciliation.',VWLB_TEXT_DOMAIN),503,array('reconcile_required'=>true));foreach((array)$rows as $row){$after=max($after,(int)$row['id']);$input=VWLB_Helpers::json($row['input_json']??'{}');if((int)($input['live_event_id']??0)!==(int)$fresh['id'])continue;$deleted=$wpdb->delete($jobs,array('id'=>(int)$row['id']),array('%d'));if(false===$deleted)return VWLB_Helpers::error('vwlb_provider_live_reconcile_required',__('Existing live reminders could not be reconciled safely.',VWLB_TEXT_DOMAIN),503,array('reconcile_required'=>true));}}while(count((array)$rows)===200);$start=strtotime(($fresh['scheduled_start']??'').' UTC');if(!$start)return VWLB_Helpers::error('vwlb_provider_live_reconcile_required',__('Live-event schedule time is unavailable for reminder reconciliation.',VWLB_TEXT_DOMAIN),503,array('reconcile_required'=>true));foreach(self::reminders($data) as $minutes){$available=$start-$minutes*MINUTE_IN_SECONDS;if($available<=time())continue;$saved=$wpdb->insert($jobs,array('public_id'=>VWLB_Helpers::public_id('job'),'asset_id'=>0,'job_type'=>'send_live_reminder','provider'=>'local','status'=>'pending','priority'=>50,'attempts'=>0,'max_attempts'=>5,'available_at'=>gmdate('Y-m-d H:i:s',$available),'input_json'=>VWLB_Helpers::json_encode(array('live_event_id'=>$fresh['id'],'minutes'=>$minutes,'scheduled_start'=>$fresh['scheduled_start'])),'output_json'=>'{}','created_at'=>VWLB_Helpers::now(),'updated_at'=>VWLB_Helpers::now()));if(!$saved)return VWLB_Helpers::error('vwlb_provider_live_reconcile_required',__('Live reminders could not be persisted after reconciliation.',VWLB_TEXT_DOMAIN),503,array('reconcile_required'=>true));}return true;});
	}
	public static function process_job($default,$job,$asset){
		if('send_live_reminder'!==($job['job_type']??''))return $default;$input=VWLB_Helpers::json($job['input_json']??'{}');$live_id=absint($input['live_event_id']??0);$minutes=absint($input['minutes']??0);if(!$live_id||!$minutes)return VWLB_Helpers::error('vwlb_live_reminder_invalid',__('Live reminder job is missing required state.',VWLB_TEXT_DOMAIN),422);VWLB_Repository::reset_read_failure();$event=VWLB_Repository::find('live_events',$live_id);if(VWLB_Repository::read_failed())return VWLB_Helpers::error('vwlb_live_reminder_state_unreadable',__('Live reminder execution state could not be verified safely.',VWLB_TEXT_DOMAIN),503);if(!$event||!in_array($event['status'],array('scheduled','rehearsal','ready'),true))return array('status'=>'complete','skipped'=>'event_not_remindable');$scheduled=(string)($event['scheduled_start']??'');$job_schedule=(string)($input['scheduled_start']??$scheduled);if(!$scheduled||!hash_equals($scheduled,$job_schedule))return array('status'=>'complete','skipped'=>'stale_schedule');$expected=strtotime($scheduled.' UTC')-$minutes*MINUTE_IN_SECONDS;$available=strtotime((string)($job['available_at']??'').' UTC');if(!$expected||!$available||abs($expected-$available)>1)return array('status'=>'complete','skipped'=>'stale_reminder');VWLB_Helpers::outbox('LiveReminderDue','live',$live_id,array('audience'=>'registered_attendees','minutes'=>$minutes,'live_public_id'=>$event['public_id'],'scheduled_start'=>$scheduled));return array('status'=>'complete');
	}
}
