<?php
/** R31/R51: provider webhook dedupe is content-bound and durable dispatch cannot be lost between persistence and handler execution. */
defined('ABSPATH') || exit;
final class VWLB_R31_Webhook_Integrity {
	const PROCESSING_STALE_SECONDS = 300;
	public static function register(){add_action('rest_api_init',array(__CLASS__,'routes'),40);add_action('vwlb_reconcile_states',array(__CLASS__,'reconcile'),55);}
	public static function routes(){foreach(VWLB_Contracts::namespaces() as $n)register_rest_route($n,'/webhooks/(?P<provider>[a-z0-9_-]+)',array('methods'=>'POST','callback'=>array(__CLASS__,'webhook'),'permission_callback'=>'__return_true'),true);}
	private static function response($value,$status=200){if(is_wp_error($value))return $value;$r=rest_ensure_response($value);$r->set_status($status);$r->header('X-Sabri-File','10');$r->header('X-VWLB-Version',VWLB_VERSION);return $r;}
	private static function header_value($headers,$name){foreach((array)$headers as $k=>$v)if(strtolower((string)$k)===strtolower($name))return is_array($v)?(string)reset($v):(string)$v;return '';}
	private static function decode_payload($row){$raw=VWLB_Helpers::json($row['payload_json']??'{}');return is_array($raw)?$raw:array();}
	private static function claim($id,$allow_failed=true){
		global $wpdb;$table=VWLB_Helpers::table('webhooks');$statuses=$allow_failed?array('received','failed'):array('received');$placeholders=implode(',',array_fill(0,count($statuses),'%s'));$args=array_merge(array(VWLB_Helpers::now(),(int)$id),$statuses);$sql=$wpdb->prepare("UPDATE {$table} SET status='processing',attempts=attempts+1,error_message=NULL,processed_at=%s WHERE id=%d AND status IN ({$placeholders})",$args);$changed=$wpdb->query($sql);if(false===$changed)return VWLB_Helpers::error('vwlb_webhook_claim_failed',__('Verified webhook could not be claimed for durable processing.',VWLB_TEXT_DOMAIN),503);return 1===$changed;
	}
	private static function dispatch($row,$data=null){
		global $wpdb;$table=VWLB_Helpers::table('webhooks');$id=(int)($row['id']??0);if(!$id)return VWLB_Helpers::error('vwlb_webhook_missing',__('Verified webhook record is unavailable.',VWLB_TEXT_DOMAIN),503);$claimed=self::claim($id,true);if(is_wp_error($claimed))return $claimed;if(!$claimed)return array('claimed'=>false);
		if(null===$data){$stored=(string)($row['payload_json']??'');$data=self::decode_payload($row);if(!$data&&'{}'!==$stored){$wpdb->update($table,array('status'=>'failed','error_message'=>'payload_decode_failed','processed_at'=>VWLB_Helpers::now()),array('id'=>$id,'status'=>'processing'));return VWLB_Helpers::error('vwlb_webhook_payload_unreadable',__('Verified webhook payload could not be decoded for processing.',VWLB_TEXT_DOMAIN),503);}}
		try{do_action('vwlb_verified_webhook',(string)$row['provider'],$data,$id);}catch(Throwable $e){$wpdb->update($table,array('status'=>'failed','error_message'=>'handler_exception:'.sanitize_key(get_class($e)),'processed_at'=>VWLB_Helpers::now()),array('id'=>$id,'status'=>'processing'));do_action('vwlb_operational_failure','webhook','vwlb_webhook_handler_failed',array('provider'=>(string)$row['provider'],'event_id_hash'=>hash('sha256',(string)$row['event_id'])));return VWLB_Helpers::error('vwlb_webhook_handler_failed',__('Verified webhook handling failed and is retained for reconciliation.',VWLB_TEXT_DOMAIN),503);}
		$done=$wpdb->update($table,array('status'=>'processed','processed_at'=>VWLB_Helpers::now(),'error_message'=>null),array('id'=>$id,'status'=>'processing'));if(1!==$done){do_action('vwlb_operational_failure','webhook','vwlb_webhook_finalize_failed',array('provider'=>(string)$row['provider'],'event_id_hash'=>hash('sha256',(string)$row['event_id'])));return VWLB_Helpers::error('vwlb_webhook_finalize_failed',__('Verified webhook was dispatched but durable completion could not be recorded; reconciliation is required.',VWLB_TEXT_DOMAIN),503);}return array('claimed'=>true,'processed'=>true);
	}
	private static function duplicate_result($existing,$event_type,$payload_hash,$data){
		if(!hash_equals((string)$existing['payload_hash'],$payload_hash)||(string)$existing['event_type']!==$event_type){do_action('vwlb_operational_failure','webhook','vwlb_webhook_event_conflict',array('provider'=>(string)$existing['provider'],'event_id_hash'=>hash('sha256',(string)$existing['event_id'])));return VWLB_Helpers::error('vwlb_webhook_event_conflict',__('The same provider event identifier was received with different content.',VWLB_TEXT_DOMAIN),409);}
		if('processed'===(string)$existing['status'])return self::response(array('accepted'=>true,'duplicate'=>true,'status'=>'processed'));
		if('processing'===(string)$existing['status'])return self::response(array('accepted'=>true,'duplicate'=>true,'status'=>'processing'),202);
		$dispatched=self::dispatch($existing,$data);if(is_wp_error($dispatched))return $dispatched;if(empty($dispatched['claimed']))return self::response(array('accepted'=>true,'duplicate'=>true,'status'=>'processing'),202);return self::response(array('accepted'=>true,'duplicate'=>true,'reprocessed'=>true,'status'=>'processed'),202);
	}
	public static function webhook(WP_REST_Request $r){
		$provider=VWLB_Providers::get($r['provider']);if(!$provider)return VWLB_Helpers::error('vwlb_provider_missing',__('Provider not found.',VWLB_TEXT_DOMAIN),404);
		$body=(string)$r->get_body();if(strlen($body)>1048576)return VWLB_Helpers::error('vwlb_webhook_too_large',__('Webhook payload is too large.',VWLB_TEXT_DOMAIN),413);$headers=$r->get_headers();if(!$provider->verify_webhook($headers,$body))return VWLB_Helpers::error('vwlb_webhook_signature_invalid',__('Webhook signature verification failed.',VWLB_TEXT_DOMAIN),401);
		$data=json_decode($body,true);if(!is_array($data))return VWLB_Helpers::error('vwlb_webhook_invalid',__('Webhook payload is invalid.',VWLB_TEXT_DOMAIN),400);
		if('custom'===$provider->id()){$timestamp=self::header_value($headers,'x-vwlb-timestamp');if(!$timestamp||!ctype_digit((string)$timestamp)||abs(time()-(int)$timestamp)>300)return VWLB_Helpers::error('vwlb_webhook_replay_window',__('Webhook timestamp is missing or outside the replay window.',VWLB_TEXT_DOMAIN),401);}
		$event_id=VWLB_Helpers::text($data['id']??hash('sha256',$body),191);$event_type=VWLB_Helpers::text($data['type']??'unknown',100);$payload_hash=hash('sha256',$body);global $wpdb;$table=VWLB_Helpers::table('webhooks');
		$inserted=$wpdb->insert($table,array('public_id'=>VWLB_Helpers::public_id('wh'),'provider'=>$provider->id(),'event_id'=>$event_id,'event_type'=>$event_type,'signature_hash'=>hash('sha256',VWLB_Helpers::json_encode($headers)),'payload_hash'=>$payload_hash,'payload_json'=>VWLB_Helpers::json_encode($data),'status'=>'received','received_at'=>VWLB_Helpers::now()));
		if(false===$inserted){$wpdb->last_error='';$existing=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$table} WHERE provider=%s AND event_id=%s LIMIT 1",$provider->id(),$event_id),ARRAY_A);if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_webhook_persist_failed',__('Verified webhook persistence state could not be read safely.',VWLB_TEXT_DOMAIN),503);if($existing)return self::duplicate_result($existing,$event_type,$payload_hash,$data);return VWLB_Helpers::error('vwlb_webhook_persist_failed',__('Verified webhook could not be persisted for durable processing.',VWLB_TEXT_DOMAIN),503);}
		$id=(int)$wpdb->insert_id;$row=array('id'=>$id,'provider'=>$provider->id(),'event_id'=>$event_id,'event_type'=>$event_type,'payload_hash'=>$payload_hash,'payload_json'=>VWLB_Helpers::json_encode($data),'status'=>'received');$dispatched=self::dispatch($row,$data);if(is_wp_error($dispatched))return $dispatched;return self::response(array('accepted'=>true,'status'=>'processed'),202);
	}
	public static function reconcile(){
		global $wpdb;$table=VWLB_Helpers::table('webhooks');$cutoff=gmdate('Y-m-d H:i:s',time()-self::PROCESSING_STALE_SECONDS);$reset=$wpdb->query($wpdb->prepare("UPDATE {$table} SET status='failed',error_message='stale_processing_recovered' WHERE status='processing' AND processed_at IS NOT NULL AND processed_at<%s LIMIT 50",$cutoff));if(false===$reset){do_action('vwlb_operational_failure','webhook','vwlb_webhook_stale_reset_failed',array());return;}
		$wpdb->last_error='';$rows=$wpdb->get_results("SELECT * FROM {$table} WHERE status IN ('received','failed') ORDER BY received_at ASC,id ASC LIMIT 25",ARRAY_A);if(''!==(string)$wpdb->last_error){do_action('vwlb_operational_failure','webhook','vwlb_webhook_reconcile_read_failed',array());return;}foreach((array)$rows as $row)self::dispatch($row,null);
	}
}
