<?php
/** WordPress privacy lifecycle including File 10 v1.2 private media/live/Future extensions. */
defined( 'ABSPATH' ) || exit;
final class VWLB_Privacy {
	public function exporters($exporters){$exporters['vwlb']=array('exporter_friendly_name'=>__('Video Wall and Live Broadcasting',VWLB_TEXT_DOMAIN),'callback'=>array($this,'export'));return $exporters;}
	public function erasers($erasers){$erasers['vwlb']=array('eraser_friendly_name'=>__('Video Wall and Live Broadcasting',VWLB_TEXT_DOMAIN),'callback'=>array($this,'erase'));return $erasers;}
	public function policy($content){$text='<p>'.esc_html__('File 10 stores private watch progress, saves/reactions, resumable-upload state, live waiting-room and recording-consent records, questions, poll responses, guest delegation, media-review attribution, rights-aware download grants, creator aggregates, reports, moderation history and short-lived security metadata as required for the service. Raw private uploads and stream credentials are never public. Eligible user data can be exported or erased; rights, safety and audit evidence may instead be anonymized or retained only under a scoped lawful hold.',VWLB_TEXT_DOMAIN).'</p>';return $content.$text;}
	private function item($group,$label,$id,$row){$data=array();foreach($row as $k=>$v){if(in_array($k,array('token_hash','private_filename','credential_hash','metadata_json','scope_json'),true))continue;$data[]=array('name'=>ucwords(str_replace('_',' ',$k)),'value'=>is_scalar($v)?(string)$v:wp_json_encode($v));}return array('group_id'=>$group,'group_label'=>$label,'item_id'=>$id,'data'=>$data);}
	private function export_query($user_id,$table,$column,$fields,$limit,$offset){global $wpdb;$wpdb->last_error='';$rows=$wpdb->get_results($wpdb->prepare("SELECT $fields FROM ".VWLB_Helpers::table($table)." WHERE $column=%d ORDER BY id LIMIT %d OFFSET %d",$user_id,$limit,$offset),ARRAY_A);if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_privacy_export_read_failed',__('File 10 personal data could not be read safely for export.',VWLB_TEXT_DOMAIN),503,array('table'=>$table));return is_array($rows)?$rows:array();}
	public function export($email,$page=1){
		$user=get_user_by('email',$email);if(!$user)return array('data'=>array(),'done'=>true);$limit=100;$offset=(max(1,(int)$page)-1)*$limit;$data=array();$max_count=0;
		$queries=array('history'=>array(__('Video history',VWLB_TEXT_DOMAIN),'playback_sessions','user_id','public_id,object_type,object_id,quality,progress_seconds,duration_seconds,completed,created_at,updated_at,expires_at'),'interactions'=>array(__('Video interactions',VWLB_TEXT_DOMAIN),'interactions','user_id','video_id,interaction,created_at,updated_at'),'live'=>array(__('Live participation and recording consent',VWLB_TEXT_DOMAIN),'live_attendees','user_id','public_id,live_event_id,state,reminder_minutes,recording_consent,consent_version,consented_at,joined_at,left_at,updated_at'),'questions'=>array(__('Live questions',VWLB_TEXT_DOMAIN),'live_questions','user_id','public_id,live_event_id,question,status,answer,created_at,updated_at'),'uploads'=>array(__('Private upload sessions',VWLB_TEXT_DOMAIN),'upload_sessions','owner_id','public_id,asset_id,expected_bytes,received_bytes,status,expires_at,created_at,updated_at'),'downloads'=>array(__('Media download grants',VWLB_TEXT_DOMAIN),'download_tokens','user_id','public_id,object_type,object_id,max_downloads,download_count,status,expires_at,created_at,updated_at'),'guests'=>array(__('Broadcast guest participation',VWLB_TEXT_DOMAIN),'broadcast_guests','user_id','public_id,live_event_id,role_name,status,expires_at,accepted_at,created_at,updated_at'),'polls'=>array(__('Live poll responses',VWLB_TEXT_DOMAIN),'live_poll_responses','user_id','poll_id,option_id,created_at'));
		foreach($queries as $gid=>$q){[$label,$table,$column,$fields]=$q;$rows=$this->export_query($user->ID,$table,$column,$fields,$limit,$offset);if(is_wp_error($rows)){do_action('vwlb_operational_failure','privacy',$rows->get_error_code(),array('phase'=>'export','table'=>$table));return $rows;}$max_count=max($max_count,count($rows));foreach($rows as $i=>$row)$data[]=$this->item('vwlb-'.$gid,$label,$gid.'-'.($offset+$i+1),$row);}return array('data'=>$data,'done'=>$max_count<$limit);
	}
	private function delete_user_rows($table,$column,$uid,&$removed,$limit=100){global $wpdb;$t=VWLB_Helpers::table($table);$result=$wpdb->query($wpdb->prepare("DELETE FROM $t WHERE $column=%d ORDER BY id ASC LIMIT %d",$uid,max(1,(int)$limit)));if(false===$result)return VWLB_Helpers::error('vwlb_privacy_delete_failed',__('Privacy erasure could not delete an eligible File 10 record.',VWLB_TEXT_DOMAIN),500,array('table'=>$table));$removed=$removed||$result>0;return true;}
	private function anonymize_user_rows($table,$column,$uid,$changes,$limit=100){global $wpdb;$t=VWLB_Helpers::table($table);$sets=array();$args=array();foreach($changes as $field=>$value){$sets[]=$field.'=%s';$args[]=is_scalar($value)?(string)$value:VWLB_Helpers::json_encode($value);}$args[]=$uid;$args[]=max(1,(int)$limit);$sql="UPDATE $t SET ".implode(',',$sets)." WHERE $column=%d ORDER BY id ASC LIMIT %d";$result=$wpdb->query($wpdb->prepare($sql,$args));return false===$result?VWLB_Helpers::error('vwlb_privacy_anonymize_failed',__('Privacy erasure could not anonymize a retained File 10 record.',VWLB_TEXT_DOMAIN),500,array('table'=>$table,'column'=>$column)):true;}
	private function erasure_has_more($uid){global $wpdb;$checks=array(array('playback_sessions','user_id'),array('interactions','user_id'),array('download_tokens','user_id'),array('upload_sessions','owner_id'),array('live_poll_responses','user_id'),array('broadcast_guests','user_id'),array('live_attendees','user_id'),array('live_questions','user_id'),array('moderation','reporter_id'),array('audit','actor_id'),array('creator_metrics_daily','owner_id'),array('production_sources','owner_id'),array('production_scenes','owner_id'),array('simulcast_targets','created_by'),array('media_tracks','created_by'),array('media_tracks','reviewed_by'),array('video_annotations','created_by'),array('video_annotations','reviewed_by'),array('live_polls','created_by'),array('consent_links','created_by'),array('watermark_policies','updated_by'),array('broadcast_guests','invited_by'),array('captions','created_by'),array('captions','reviewed_by'),array('stream_credentials','created_by'),array('moderation','reviewer_id'),array('takedowns','claimant_id'),array('takedowns','reviewer_id'));foreach($checks as $spec){$t=VWLB_Helpers::table($spec[0]);$wpdb->last_error='';$found=$wpdb->get_var($wpdb->prepare("SELECT id FROM $t WHERE {$spec[1]}=%d LIMIT 1",$uid));if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_privacy_completion_unverifiable',__('Privacy erasure completion could not be verified safely.',VWLB_TEXT_DOMAIN),503,array('table'=>$spec[0]));if(null!==$found)return true;}$idem=VWLB_Helpers::table('idempotency');$scope='%'.$wpdb->esc_like(':u'.$uid).'%';$wpdb->last_error='';$found=$wpdb->get_var($wpdb->prepare("SELECT id FROM $idem WHERE scope LIKE %s LIMIT 1",$scope));if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_privacy_completion_unverifiable',__('Privacy erasure completion could not verify replay state.',VWLB_TEXT_DOMAIN),503,array('table'=>'idempotency'));return null!==$found;}
	public function erase($email,$page=1){
		$user=get_user_by('email',$email);if(!$user)return array('items_removed'=>false,'items_retained'=>false,'messages'=>array(),'done'=>true);global $wpdb;$uid=(int)$user->ID;$removed=false;$messages=array();
		$wpdb->last_error='';$uploads=$wpdb->get_results($wpdb->prepare('SELECT id,private_filename,status FROM '.VWLB_Helpers::table('upload_sessions').' WHERE owner_id=%d ORDER BY id ASC LIMIT 100',$uid),ARRAY_A);if(''!==(string)$wpdb->last_error)return array('items_removed'=>false,'items_retained'=>true,'messages'=>array(__('Private upload state could not be read safely; erasure was stopped for retry.',VWLB_TEXT_DOMAIN)),'done'=>false);foreach((array)$uploads as $s){if('active'===$s['status']&&!empty($s['private_filename'])){$base=trailingslashit(WP_CONTENT_DIR).VWLB_Extensions::PRIVATE_DIR;$path=$base.'/'.sanitize_file_name($s['private_filename']);if(is_file($path)&&!unlink($path))return array('items_removed'=>$removed,'items_retained'=>true,'messages'=>array(__('A private upload could not be deleted from storage; database erasure was stopped so the request can be retried safely.',VWLB_TEXT_DOMAIN)),'done'=>false);}}
		$wpdb->last_error='';$affected=$wpdb->get_col($wpdb->prepare('SELECT DISTINCT video_id FROM '.VWLB_Helpers::table('interactions').' WHERE user_id=%d ORDER BY video_id ASC LIMIT 100',$uid));if(''!==(string)$wpdb->last_error)return array('items_removed'=>$removed,'items_retained'=>true,'messages'=>array(__('Interaction state could not be read safely; erasure was stopped for retry.',VWLB_TEXT_DOMAIN)),'done'=>false);$affected=is_array($affected)?$affected:array();
		$result=VWLB_DB::transaction(function()use($wpdb,$uid,$affected,&$removed){
			foreach(array(array('playback_sessions','user_id'),array('interactions','user_id'),array('download_tokens','user_id'),array('upload_sessions','owner_id'),array('live_poll_responses','user_id'),array('broadcast_guests','user_id')) as $spec){$ok=$this->delete_user_rows($spec[0],$spec[1],$uid,$removed);if(is_wp_error($ok))return $ok;}$idem_table=VWLB_Helpers::table('idempotency');$scope_like='%'.$wpdb->esc_like(':u'.$uid).'%';$idem_deleted=$wpdb->query($wpdb->prepare("DELETE FROM $idem_table WHERE scope LIKE %s LIMIT 200",$scope_like));if(false===$idem_deleted)return VWLB_Helpers::error('vwlb_privacy_delete_failed',__('Privacy erasure could not remove historical idempotency records.',VWLB_TEXT_DOMAIN),500,array('table'=>'idempotency'));$removed=$removed||$idem_deleted>0;
			foreach($affected as $video_id){foreach(array('like','dislike') as $type){$wpdb->last_error='';$count=$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.VWLB_Helpers::table('interactions').' WHERE video_id=%d AND interaction=%s',$video_id,$type));if(''!==(string)$wpdb->last_error)return VWLB_Helpers::error('vwlb_privacy_counter_read_failed',__('Privacy erasure could not read an interaction counter safely.',VWLB_TEXT_DOMAIN),503);$changed=$wpdb->update(VWLB_Helpers::table('videos'),array($type.'_count'=>(int)$count),array('id'=>$video_id));if(false===$changed)return VWLB_Helpers::error('vwlb_privacy_counter_failed',__('Privacy erasure could not reconcile an interaction counter.',VWLB_TEXT_DOMAIN),500);}}
			$anonymize=array(array('live_attendees','user_id',array('user_id'=>0,'state'=>'anonymized')),array('live_questions','user_id',array('user_id'=>0,'question'=>'[erased by privacy request]')),array('moderation','reporter_id',array('reporter_id'=>0,'note'=>'[anonymized by privacy erasure]')),array('audit','actor_id',array('actor_id'=>0)),array('creator_metrics_daily','owner_id',array('owner_id'=>0)),array('production_sources','owner_id',array('owner_id'=>0)),array('production_scenes','owner_id',array('owner_id'=>0)),array('simulcast_targets','created_by',array('created_by'=>0)),array('media_tracks','created_by',array('created_by'=>0)),array('media_tracks','reviewed_by',array('reviewed_by'=>0)),array('video_annotations','created_by',array('created_by'=>0)),array('video_annotations','reviewed_by',array('reviewed_by'=>0)),array('live_polls','created_by',array('created_by'=>0)),array('consent_links','created_by',array('created_by'=>0)),array('watermark_policies','updated_by',array('updated_by'=>0)),array('broadcast_guests','invited_by',array('invited_by'=>0)),array('captions','created_by',array('created_by'=>0)),array('captions','reviewed_by',array('reviewed_by'=>0)),array('stream_credentials','created_by',array('created_by'=>0)),array('moderation','reviewer_id',array('reviewer_id'=>0)),array('takedowns','claimant_id',array('claimant_id'=>0,'claimant_contact_hash'=>'')),array('takedowns','reviewer_id',array('reviewer_id'=>0)));
			foreach($anonymize as $spec){$ok=$this->anonymize_user_rows($spec[0],$spec[1],$uid,$spec[2]);if(is_wp_error($ok))return $ok;}return true;
		});
		if(is_wp_error($result))return array('items_removed'=>$removed,'items_retained'=>true,'messages'=>array($result->get_error_message()),'done'=>false);$more=$this->erasure_has_more($uid);if(is_wp_error($more)){do_action('vwlb_operational_failure','privacy',$more->get_error_code(),array('phase'=>'erase-postcheck'));return array('items_removed'=>$removed,'items_retained'=>true,'messages'=>array($more->get_error_message()),'done'=>false);}$done=!$more;if($done){$receipt=VWLB_Helpers::public_id('erase');VWLB_Helpers::audit('privacy',$receipt,'erase','','complete','Eligible File 10 private data erased; retained safety/rights evidence anonymized',array('purpose'=>'privacy_erasure','subject'=>'anonymized'));$messages[]=__('Safety, copyright, recording-consent, moderation and audit records were anonymized where retention was required.',VWLB_TEXT_DOMAIN);}else{$messages[]=__('File 10 erased one bounded privacy batch; additional eligible records remain and will be processed on the next eraser page.',VWLB_TEXT_DOMAIN);}return array('items_removed'=>$removed,'items_retained'=>true,'messages'=>$messages,'done'=>$done);
	}
	public function private_headers(){$private_slugs=array('video-history','studio-video','studio-live');if(is_page(array_values((array)get_option('vwlb_page_map',array())))&&(is_user_logged_in()||is_page($private_slugs)))VWLB_Helpers::no_cache_private();if(get_query_var('vwlb_video_id')){$v=VWLB_Repository::find('videos',get_query_var('vwlb_video_id'));if(!$v||'published'!==($v['status']??'')||'public'!==($v['visibility']??''))VWLB_Helpers::no_cache_private();}if(get_query_var('vwlb_live_id')){$e=VWLB_Repository::find('live_events',get_query_var('vwlb_live_id'));if(!$e||'public'!==($e['visibility']??'')||!in_array($e['status']??'',array('scheduled','live','ended','replay_published'),true))VWLB_Helpers::no_cache_private();}}
}
