<?php
/** R76: starvation-safe, DB-error-aware cleanup for private uploads and expiring security state. */
defined( 'ABSPATH' ) || exit;
final class VWLB_R76_Cleanup_Durability {
	const UPLOAD_CURSOR_OPTION='vwlb_r76_upload_cleanup_cursor';
	const UPLOAD_PAGE_SIZE=100;
	public static function register(){remove_action('vwlb_cleanup',array('VWLB_Jobs','cleanup'));remove_action('vwlb_cleanup',array('VWLB_Extensions','cleanup'),20);add_action('vwlb_cleanup',array(__CLASS__,'cleanup'),20);}
	private static function signal($code,$context=array()){do_action('vwlb_operational_failure','cleanup',$code,$context);}
	private static function cursor($value){$value=max(0,(int)$value);if(0===$value){$deleted=delete_option(self::UPLOAD_CURSOR_OPTION);if(!$deleted&&false!==get_option(self::UPLOAD_CURSOR_OPTION,false)){self::signal('vwlb_cleanup_cursor_persist_failed',array('action'=>'reset'));return false;}return true;}$saved=update_option(self::UPLOAD_CURSOR_OPTION,$value,false);if(!$saved&&(int)get_option(self::UPLOAD_CURSOR_OPTION,0)!==$value){self::signal('vwlb_cleanup_cursor_persist_failed',array('action'=>'advance'));return false;}return true;}
	private static function upload_path($filename){$base=trailingslashit(WP_CONTENT_DIR).VWLB_Extensions::PRIVATE_DIR;if(is_link($base)||!is_dir($base))return null;$root=realpath($base);$content=realpath(WP_CONTENT_DIR);if(!$root||!$content||0!==strpos($root,$content.DIRECTORY_SEPARATOR))return null;$name=sanitize_file_name(basename((string)$filename));if(!$name||!str_ends_with($name,'.part'))return null;$path=trailingslashit($root).$name;if(is_link($path))return null;return $path;}
	private static function cleanup_uploads($now){global $wpdb;$table=VWLB_Helpers::table('upload_sessions');$cursor=max(0,(int)get_option(self::UPLOAD_CURSOR_OPTION,0));$wpdb->last_error='';$rows=$wpdb->get_results($wpdb->prepare("SELECT id,private_filename,status FROM {$table} WHERE status IN ('active','failed') AND expires_at<%s AND id>%d ORDER BY id ASC LIMIT %d",$now,$cursor,self::UPLOAD_PAGE_SIZE),ARRAY_A);if(''!==(string)$wpdb->last_error){self::signal('vwlb_upload_cleanup_read_failed');return;}if(!$rows){if($cursor)self::cursor(0);return;}$last=$cursor;foreach($rows as $row){$last=max($last,(int)$row['id']);$path=self::upload_path($row['private_filename']??'');if(null===$path){self::signal('vwlb_upload_cleanup_path_unverifiable',array('session_id'=>(int)$row['id']));continue;}if(is_file($path)&&!@unlink($path)){self::signal('vwlb_upload_cleanup_file_delete_failed',array('session_id'=>(int)$row['id']));continue;}$changed=$wpdb->update($table,array('status'=>'expired','updated_at'=>$now),array('id'=>(int)$row['id'],'status'=>$row['status']),array('%s','%s'),array('%d','%s'));if(false===$changed){self::signal('vwlb_upload_cleanup_state_write_failed',array('session_id'=>(int)$row['id']));continue;}if(1===$changed)VWLB_Helpers::audit('upload_session',(int)$row['id'],'expire',$row['status'],'expired');}self::cursor(count($rows)<self::UPLOAD_PAGE_SIZE?0:$last);}
	private static function delete_expired($table,$column,$now){global $wpdb;$result=$wpdb->query($wpdb->prepare('DELETE FROM '.VWLB_Helpers::table($table)." WHERE {$column} IS NOT NULL AND {$column}<%s LIMIT 1000",$now));if(false===$result)self::signal('vwlb_cleanup_delete_failed',array('table'=>$table));}
	public static function cleanup(){global $wpdb;$now=VWLB_Helpers::now();self::cleanup_uploads($now);foreach(array('idempotency'=>'expires_at','rate_limits'=>'window_ends_at','playback_sessions'=>'expires_at','rollback_snapshots'=>'expires_at') as $table=>$column)self::delete_expired($table,$column,$now);$changed=$wpdb->query($wpdb->prepare("UPDATE ".VWLB_Helpers::table('stream_credentials')." SET status='expired' WHERE status='active' AND expires_at IS NOT NULL AND expires_at<%s",$now));if(false===$changed)self::signal('vwlb_stream_credential_cleanup_failed');$downloads=$wpdb->query($wpdb->prepare("UPDATE ".VWLB_Helpers::table('download_tokens')." SET status='expired',updated_at=%s WHERE status='active' AND expires_at<%s",$now,$now));if(false===$downloads)self::signal('vwlb_download_token_cleanup_failed');}
}
