from pathlib import Path
import re
p=Path('video-wall-and-live-broadcasting/includes/class-vwlb-future-intelligence.php');reg=Path('tests/fresh-40-review-contracts.sh');t=p.read_text()
create=r'''	public static function create_poll( $live_id, $data ) {
		$event=self::live($live_id);if(!self::require_live_control($event,'future_live_poll'))return VWLB_Helpers::error('vwlb_forbidden',__('You cannot create this poll.',VWLB_TEXT_DOMAIN),403);$q=VWLB_Helpers::textarea($data['question']??'');$options=array_values(array_filter(array_map(function($v){return VWLB_Helpers::text(is_array($v)?($v['text']??''):$v,255);},(array)($data['options']??array()))));if(!$q||count($options)<2)return VWLB_Helpers::error('vwlb_poll_fields_required',__('A question and at least two options are required.',VWLB_TEXT_DOMAIN),422);
		$tz=$data['timezone']??'UTC';$opens=!empty($data['opens_at'])?VWLB_Helpers::datetime_in_timezone($data['opens_at'],$tz):null;$closes=!empty($data['closes_at'])?VWLB_Helpers::datetime_in_timezone($data['closes_at'],$tz):null;if(!empty($data['opens_at'])&&!$opens||!empty($data['closes_at'])&&!$closes)return VWLB_Helpers::error('vwlb_poll_time_invalid',__('Poll opening or closing time is invalid.',VWLB_TEXT_DOMAIN),422);if($opens&&$closes&&strtotime($closes.' UTC')<=strtotime($opens.' UTC'))return VWLB_Helpers::error('vwlb_poll_time_invalid',__('Poll closing time must be after its opening time.',VWLB_TEXT_DOMAIN),422);
		global $wpdb;$now=VWLB_Helpers::now();return VWLB_DB::transaction(function()use($wpdb,$event,$data,$q,$options,$now,$opens,$closes){$public=VWLB_Helpers::public_id('poll');$ok=$wpdb->insert(VWLB_Helpers::table('live_polls'),array('public_id'=>$public,'live_event_id'=>$event['id'],'question'=>$q,'poll_type'=>VWLB_Helpers::enum($data['poll_type']??'single',array('single','multiple','knowledge_check'),'single'),'status'=>VWLB_Helpers::enum($data['status']??'draft',array('draft','open','closed','removed'),'draft'),'opens_at'=>$opens,'closes_at'=>$closes,'metadata_json'=>VWLB_Helpers::json_encode(array('educational_only'=>true,'not_diagnostic'=>true)),'version'=>1,'created_by'=>get_current_user_id(),'created_at'=>$now,'updated_at'=>$now));if(!$ok||!$wpdb->insert_id)return VWLB_Helpers::error('vwlb_database_error',__('Poll could not be saved.',VWLB_TEXT_DOMAIN),500);$poll_id=(int)$wpdb->insert_id;foreach($options as $idx=>$text){$raw=(array)($data['options'][$idx]??array());$saved=$wpdb->insert(VWLB_Helpers::table('live_poll_options'),array('poll_id'=>$poll_id,'public_id'=>VWLB_Helpers::public_id('opt'),'option_text'=>$text,'is_correct'=>!empty($raw['is_correct'])?1:0,'sort_order'=>$idx));if(!$saved)return VWLB_Helpers::error('vwlb_database_error',__('Poll option could not be saved.',VWLB_TEXT_DOMAIN),500);}VWLB_Helpers::audit('live_poll',$poll_id,'create','','',$q,array('live_event_id'=>$event['id']));VWLB_Helpers::outbox('LivePollChanged','live',$event['id'],array('poll_public_id'=>$public));return self::poll($public,true);});
	}
'''
poll=r'''	public static function poll( $poll_id, $include_answers=false ) {
		$poll=self::public_row('live_polls',$poll_id);if(!$poll)return null;$event=self::live($poll['live_event_id']);if(!$event||!VWLB_Security::can_view($event))return null;global $wpdb;$options=$wpdb->get_results($wpdb->prepare('SELECT id,public_id,option_text,is_correct,sort_order FROM '.VWLB_Helpers::table('live_poll_options').' WHERE poll_id=%d ORDER BY sort_order ASC,id ASC',$poll['id']),ARRAY_A);$can_answers=$include_answers&&VWLB_Security::can(VWLB_Contracts::CAP_BROADCAST,$event,'future_poll_answers');foreach($options as &$o){if(!$can_answers)unset($o['is_correct']);$o['responses']=(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(DISTINCT user_id) FROM '.VWLB_Helpers::table('live_poll_responses').' WHERE poll_id=%d AND option_id=%d',$poll['id'],$o['id']));unset($o['id']);}
		$dto=array('public_id'=>$poll['public_id'],'question'=>$poll['question'],'poll_type'=>$poll['poll_type'],'status'=>$poll['status'],'opens_at'=>VWLB_Helpers::iso_utc($poll['opens_at']),'closes_at'=>VWLB_Helpers::iso_utc($poll['closes_at']),'version'=>(int)$poll['version'],'not_diagnostic'=>true,'options'=>$options);return $dto;
	}
'''
answer=r'''	public static function answer_poll( $poll_id, $option_ids ) {
		if(!is_user_logged_in())return VWLB_Helpers::error('vwlb_login_required',__('Login is required.',VWLB_TEXT_DOMAIN),401);$poll=self::public_row('live_polls',$poll_id);if(!$poll||'open'!==$poll['status'])return VWLB_Helpers::error('vwlb_poll_unavailable',__('Poll is not open.',VWLB_TEXT_DOMAIN),409);$now=time();if($poll['opens_at']&&strtotime($poll['opens_at'].' UTC')>$now||$poll['closes_at']&&strtotime($poll['closes_at'].' UTC')<=$now)return VWLB_Helpers::error('vwlb_poll_unavailable',__('Poll is outside its active response window.',VWLB_TEXT_DOMAIN),409);$event=self::live($poll['live_event_id']);if(!$event||!VWLB_Security::can_view($event))return VWLB_Helpers::error('vwlb_not_found',__('Poll not found.',VWLB_TEXT_DOMAIN),404);$raw_ids=array_values(array_unique(array_filter(array_map(function($v){return VWLB_Helpers::text($v,64);},(array)$option_ids))));if('single'===$poll['poll_type']&&count($raw_ids)>1)return VWLB_Helpers::error('vwlb_poll_single_choice',__('Only one option may be selected.',VWLB_TEXT_DOMAIN),422);global $wpdb;$option_table=VWLB_Helpers::table('live_poll_options');$ids=array();foreach($raw_ids as $raw){if(ctype_digit($raw))$id=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM $option_table WHERE poll_id=%d AND id=%d",$poll['id'],(int)$raw));else$id=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM $option_table WHERE poll_id=%d AND public_id=%s",$poll['id'],$raw));if($id)$ids[]=$id;}$ids=array_values(array_unique($ids));if(!$ids)return VWLB_Helpers::error('vwlb_poll_option_invalid',__('Selected option is invalid.',VWLB_TEXT_DOMAIN),422);
		return VWLB_DB::transaction(function()use($wpdb,$poll,$ids){$deleted=$wpdb->delete(VWLB_Helpers::table('live_poll_responses'),array('poll_id'=>$poll['id'],'user_id'=>get_current_user_id()));if(false===$deleted)return VWLB_Helpers::error('vwlb_database_error',__('Previous poll response could not be replaced.',VWLB_TEXT_DOMAIN),500);foreach($ids as $id){$saved=$wpdb->insert(VWLB_Helpers::table('live_poll_responses'),array('poll_id'=>$poll['id'],'user_id'=>get_current_user_id(),'option_id'=>$id,'created_at'=>VWLB_Helpers::now()));if(!$saved)return VWLB_Helpers::error('vwlb_database_error',__('Poll response could not be saved.',VWLB_TEXT_DOMAIN),500);}return array('accepted'=>true,'poll_public_id'=>$poll['public_id']);});
	}
'''
for name,repl in [('create_poll',create),('poll',poll),('answer_poll',answer)]:
    pat=re.compile(r"\tpublic static function "+name+r"\(.*?\n\t}\n",re.S);m=pat.search(t)
    if not m:raise SystemExit('R13 '+name+' missing')
    t=t[:m.start()]+repl+t[m.end():]
p.write_text(t)
r=reg.read_text();marker="""# R13 — live polls validate UTC windows, roll back failed options/responses and return a bounded public DTO.\nneed \"Poll closing time must be after its opening time\" \"$P/includes/class-vwlb-future-intelligence.php\" r13-window-order\nneed \"Poll option could not be saved\" \"$P/includes/class-vwlb-future-intelligence.php\" r13-option-atomic\nneed \"outside its active response window\" \"$P/includes/class-vwlb-future-intelligence.php\" r13-window-enforce\nneed \"Previous poll response could not be replaced\" \"$P/includes/class-vwlb-future-intelligence.php\" r13-response-atomic\nneed \"'not_diagnostic'=>true\" \"$P/includes/class-vwlb-future-intelligence.php\" r13-public-dto\n"""
if '# R13 —' not in r:r=r.replace("printf '%s\\n' 'fresh 40-review regression contracts PASS'\n",marker+"printf '%s\\n' 'fresh 40-review regression contracts PASS'\n")
reg.write_text(r)
