from pathlib import Path
import re
p=Path('video-wall-and-live-broadcasting/includes/class-vwlb-future-intelligence.php');reg=Path('tests/fresh-40-review-contracts.sh');t=p.read_text()
upsert=r'''	public static function upsert_consent_link( $video_id, $data ) {
		$video=self::video($video_id);if(!$video||!VWLB_Security::can(VWLB_Contracts::CAP_REVIEW,$video,'future_consent_link'))return VWLB_Helpers::error('vwlb_forbidden',__('You cannot manage consent for this video.',VWLB_TEXT_DOMAIN),403);$ref=VWLB_Helpers::text($data['consent_ref']??'',191);if(!$ref)return VWLB_Helpers::error('vwlb_consent_ref_required',__('Consent reference is required.',VWLB_TEXT_DOMAIN),422);$status=VWLB_Helpers::enum($data['status']??'active',array('active','expired','withdrawn','superseded'),'active');$expires=!empty($data['expires_at'])?VWLB_Helpers::datetime_in_timezone($data['expires_at'],$data['timezone']??'UTC'):null;if(!empty($data['expires_at'])&&!$expires)return VWLB_Helpers::error('vwlb_consent_time_invalid',__('Consent expiry time is invalid.',VWLB_TEXT_DOMAIN),422);$metadata=(array)($data['metadata']??array());if(self::contains_raw_secret($metadata))return VWLB_Helpers::error('vwlb_consent_secret_forbidden',__('Raw credentials cannot be stored in consent metadata.',VWLB_TEXT_DOMAIN),422);
		global $wpdb;$table=VWLB_Helpers::table('consent_links');$result=VWLB_DB::transaction(function()use($wpdb,$table,$video,$ref,$status,$expires,$data,$metadata){$locked=VWLB_Repository::find('videos',$video['id'],true);if(!$locked)return VWLB_Helpers::error('vwlb_video_missing',__('Video not found.',VWLB_TEXT_DOMAIN),404);$current=$wpdb->get_row($wpdb->prepare("SELECT * FROM $table WHERE video_id=%d AND consent_ref=%s FOR UPDATE",$locked['id'],$ref),ARRAY_A);$row=array('subject_ref'=>VWLB_Helpers::text($data['subject_ref']??'',191),'status'=>$status,'expires_at'=>$expires,'withdrawn_at'=>'withdrawn'===$status?VWLB_Helpers::now():null,'metadata_json'=>VWLB_Helpers::json_encode($metadata),'updated_at'=>VWLB_Helpers::now());if($current){$row['version']=(int)$current['version']+1;$changed=$wpdb->update($table,$row,array('id'=>$current['id'],'version'=>$current['version']));if(1!==$changed)return VWLB_Helpers::error('vwlb_version_conflict',__('Consent record changed concurrently.',VWLB_TEXT_DOMAIN),409);$id=(int)$current['id'];}else{$row+=array('video_id'=>(int)$locked['id'],'consent_ref'=>$ref,'version'=>1,'created_by'=>get_current_user_id(),'created_at'=>VWLB_Helpers::now());if(!$wpdb->insert($table,$row))return VWLB_Helpers::error('vwlb_database_error',__('Consent link could not be saved.',VWLB_TEXT_DOMAIN),500);$id=(int)$wpdb->insert_id;}
		$restricted=false;if(in_array($status,array('expired','withdrawn'),true)){$restricted=self::restrict_video_for_consent($locked,$status);if(is_wp_error($restricted))return $restricted;}$saved=$wpdb->get_row($wpdb->prepare("SELECT * FROM $table WHERE id=%d",$id),ARRAY_A);return array('consent'=>$saved,'restricted'=>(bool)$restricted,'video_public_id'=>$locked['public_id'],'reason'=>$status);});if(is_wp_error($result))return $result;if(!empty($result['restricted']))do_action('vwlb_purge_media_derivative_caches',$result['video_public_id'],'consent_'.$result['reason']);return $result['consent'];
	}
'''
restrict=r'''	private static function restrict_video_for_consent( $video, $reason ) {
		if(in_array($video['status'],array('removed','restricted'),true))return false;$updated=VWLB_Repository::update_versioned('videos',$video['id'],$video['version'],array('status'=>'restricted'));if(is_wp_error($updated))return $updated;VWLB_Helpers::audit('video',$video['id'],'consent_auto_restrict',$video['status'],'restricted',$reason);VWLB_Helpers::outbox('VideoRestricted','video',$video['id'],array('reason'=>'consent_'.$reason));return true;
	}
'''
reconcile=r'''	public static function reconcile_consent_expiry() {
		global $wpdb;$table=VWLB_Helpers::table('consent_links');$rows=$wpdb->get_results($wpdb->prepare("SELECT id FROM $table WHERE status='active' AND expires_at IS NOT NULL AND expires_at<=%s ORDER BY id ASC LIMIT 100",VWLB_Helpers::now()),ARRAY_A);foreach($rows as $candidate){$result=VWLB_DB::transaction(function()use($wpdb,$table,$candidate){$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM $table WHERE id=%d FOR UPDATE",$candidate['id']),ARRAY_A);if(!$row||'active'!==$row['status']||!$row['expires_at']||strtotime($row['expires_at'].' UTC')>time())return array('changed'=>false);$video=VWLB_Repository::find('videos',$row['video_id'],true);if(!$video)return VWLB_Helpers::error('vwlb_video_missing',__('Consent-linked video is missing.',VWLB_TEXT_DOMAIN),409);$changed=$wpdb->update($table,array('status'=>'expired','version'=>(int)$row['version']+1,'updated_at'=>VWLB_Helpers::now()),array('id'=>$row['id'],'version'=>$row['version'],'status'=>'active'));if(1!==$changed)return VWLB_Helpers::error('vwlb_version_conflict',__('Consent expiry changed concurrently.',VWLB_TEXT_DOMAIN),409);$restricted=self::restrict_video_for_consent($video,'expired');if(is_wp_error($restricted))return $restricted;return array('changed'=>true,'restricted'=>(bool)$restricted,'video_public_id'=>$video['public_id']);});if(!is_wp_error($result)&&!empty($result['restricted']))do_action('vwlb_purge_media_derivative_caches',$result['video_public_id'],'consent_expired');}
	}
'''
for name,repl in [('upsert_consent_link',upsert),('restrict_video_for_consent',restrict),('reconcile_consent_expiry',reconcile)]:
    pat=re.compile(r"\t(?:public|private) static function "+name+r"\(.*?\n\t}\n",re.S);m=pat.search(t)
    if not m:raise SystemExit('R14 '+name+' missing')
    t=t[:m.start()]+repl+t[m.end():]
p.write_text(t)
r=reg.read_text();marker="""# R14 — consent withdrawal/expiry and video restriction are one fail-closed transaction; races cannot leave public media after consent loss.\nneed \"FOR UPDATE\" \"$P/includes/class-vwlb-future-intelligence.php\" r14-consent-lock\nneed \"Consent record changed concurrently\" \"$P/includes/class-vwlb-future-intelligence.php\" r14-consent-cas\nneed \"restrict_video_for_consent(\$locked\" \"$P/includes/class-vwlb-future-intelligence.php\" r14-atomic-restrict\nneed \"if(is_wp_error(\$restricted))return \$restricted\" \"$P/includes/class-vwlb-future-intelligence.php\" r14-fail-closed\nneed \"vwlb_purge_media_derivative_caches\" \"$P/includes/class-vwlb-future-intelligence.php\" r14-cache-purge\n"""
if '# R14 —' not in r:r=r.replace("printf '%s\\n' 'fresh 40-review regression contracts PASS'\n",marker+"printf '%s\\n' 'fresh 40-review regression contracts PASS'\n")
reg.write_text(r)
