from pathlib import Path

p=Path('video-wall-and-live-broadcasting/includes/class-vwlb-videos.php')
reg=Path('tests/fresh-40-review-contracts.sh')
t=p.read_text()

old="\tpublic static function playback($video_id){$video=VWLB_Repository::video_bundle($video_id);if(!$video||!VWLB_Security::can_view($video))return VWLB_Helpers::error('vwlb_not_found',__('Video not found.',VWLB_TEXT_DOMAIN),404);$provider=VWLB_Providers::get($video['provider']);if(!$provider)return VWLB_Helpers::error('vwlb_provider_missing',__('Playback provider is unavailable.',VWLB_TEXT_DOMAIN),503);$payload=$provider->playback($video,VWLB_Security::claims());if(is_wp_error($payload))return $payload;$session=self::playback_session($video);if(!in_array($video['visibility'],array('public','unlisted'),true)){$secure=apply_filters('vwlb_secure_playback_grant','',$video,$payload,$session,VWLB_Security::claims());if(!$secure)return VWLB_Helpers::error('vwlb_secure_delivery_required',__('Secure playback delivery is not configured.',VWLB_TEXT_DOMAIN),503);$payload['url']=esc_url_raw($secure);}self::count_view($video);return array('video'=>VWLB_Repository::public_video_dto($video),'playback'=>$payload,'session'=>$session);}\n"
new="\tpublic static function playback($video_id){$video=VWLB_Repository::video_bundle($video_id);if(!$video||!VWLB_Security::can_view($video))return VWLB_Helpers::error('vwlb_not_found',__('Video not found.',VWLB_TEXT_DOMAIN),404);$provider=VWLB_Providers::get($video['provider']);if(!$provider)return VWLB_Helpers::error('vwlb_provider_missing',__('Playback provider is unavailable.',VWLB_TEXT_DOMAIN),503);$payload=$provider->playback($video,VWLB_Security::claims());if(is_wp_error($payload))return $payload;$session=self::playback_session($video);if(is_wp_error($session))return $session;if(!in_array($video['visibility'],array('public','unlisted'),true)){$secure=apply_filters('vwlb_secure_playback_grant','',$video,$payload,$session,VWLB_Security::claims());if(!$secure)return VWLB_Helpers::error('vwlb_secure_delivery_required',__('Secure playback delivery is not configured.',VWLB_TEXT_DOMAIN),503);$payload['url']=esc_url_raw($secure);}self::count_view($video);return array('video'=>VWLB_Repository::public_video_dto($video),'playback'=>$payload,'session'=>$session);}\n"
if old not in t: raise SystemExit('R35 playback pattern missing')
t=t.replace(old,new,1)

old="\tprivate static function playback_session($video){global $wpdb;$user=get_current_user_id();$now=VWLB_Helpers::now();$token=VWLB_Helpers::public_id('play');$hash=hash_hmac('sha256',$token,wp_salt('logged_in'));if($user){$row=$wpdb->get_row($wpdb->prepare('SELECT id,public_id,progress_seconds FROM '.VWLB_Helpers::table('playback_sessions').' WHERE user_id=%d AND object_type=%s AND object_id=%d',$user,'video',$video['id']),ARRAY_A);if($row){$wpdb->update(VWLB_Helpers::table('playback_sessions'),array('token_hash'=>$hash,'updated_at'=>$now,'expires_at'=>gmdate('Y-m-d H:i:s',time()+30*DAY_IN_SECONDS)),array('id'=>$row['id']));return array('token'=>$token,'resume_seconds'=>(int)$row['progress_seconds']);}}$wpdb->insert(VWLB_Helpers::table('playback_sessions'),array('public_id'=>VWLB_Helpers::public_id('ses'),'user_id'=>$user,'object_type'=>'video','object_id'=>$video['id'],'token_hash'=>$hash,'progress_seconds'=>0,'duration_seconds'=>(int)$video['duration_seconds'],'ip_hash'=>VWLB_Helpers::ip_hash(),'user_agent_hash'=>VWLB_Helpers::ua_hash(),'created_at'=>$now,'updated_at'=>$now,'expires_at'=>gmdate('Y-m-d H:i:s',time()+($user?30*DAY_IN_SECONDS:2*HOUR_IN_SECONDS))));return array('token'=>$token,'resume_seconds'=>0);}\n"
new="\tprivate static function playback_session($video){global $wpdb;$user=get_current_user_id();$now=VWLB_Helpers::now();$token=VWLB_Helpers::public_id('play');$hash=hash_hmac('sha256',$token,wp_salt('logged_in'));if($user){$row=$wpdb->get_row($wpdb->prepare('SELECT id,public_id,progress_seconds FROM '.VWLB_Helpers::table('playback_sessions').' WHERE user_id=%d AND object_type=%s AND object_id=%d',$user,'video',$video['id']),ARRAY_A);if($row){$changed=$wpdb->update(VWLB_Helpers::table('playback_sessions'),array('token_hash'=>$hash,'updated_at'=>$now,'expires_at'=>gmdate('Y-m-d H:i:s',time()+30*DAY_IN_SECONDS)),array('id'=>$row['id']));if(false===$changed)return VWLB_Helpers::error('vwlb_playback_session_failed',__('Playback session could not be refreshed.',VWLB_TEXT_DOMAIN),503);return array('token'=>$token,'resume_seconds'=>(int)$row['progress_seconds']);}}$saved=$wpdb->insert(VWLB_Helpers::table('playback_sessions'),array('public_id'=>VWLB_Helpers::public_id('ses'),'user_id'=>$user,'object_type'=>'video','object_id'=>$video['id'],'token_hash'=>$hash,'progress_seconds'=>0,'duration_seconds'=>(int)$video['duration_seconds'],'ip_hash'=>VWLB_Helpers::ip_hash(),'user_agent_hash'=>VWLB_Helpers::ua_hash(),'created_at'=>$now,'updated_at'=>$now,'expires_at'=>gmdate('Y-m-d H:i:s',time()+($user?30*DAY_IN_SECONDS:2*HOUR_IN_SECONDS))));if(!$saved)return VWLB_Helpers::error('vwlb_playback_session_failed',__('Playback session could not be created.',VWLB_TEXT_DOMAIN),503);return array('token'=>$token,'resume_seconds'=>0);}\n"
if old not in t: raise SystemExit('R35 playback session pattern missing')
t=t.replace(old,new,1)

old="\tpublic static function clear_history(){if(!is_user_logged_in())return VWLB_Helpers::error('vwlb_login_required',__('Sign in to clear history.',VWLB_TEXT_DOMAIN),401);global $wpdb;$removed=$wpdb->delete(VWLB_Helpers::table('playback_sessions'),array('user_id'=>get_current_user_id(),'object_type'=>'video'),array('%d','%s'));VWLB_Helpers::audit('history',get_current_user_id(),'clear','','complete','User cleared private watch history');return array('removed'=>(int)$removed);}\n"
new="\tpublic static function clear_history(){if(!is_user_logged_in())return VWLB_Helpers::error('vwlb_login_required',__('Sign in to clear history.',VWLB_TEXT_DOMAIN),401);global $wpdb;$removed=$wpdb->delete(VWLB_Helpers::table('playback_sessions'),array('user_id'=>get_current_user_id(),'object_type'=>'video'),array('%d','%s'));if(false===$removed)return VWLB_Helpers::error('vwlb_history_delete_failed',__('Private watch history could not be cleared.',VWLB_TEXT_DOMAIN),500);VWLB_Helpers::audit('history',get_current_user_id(),'clear','','complete','User cleared private watch history');return array('removed'=>(int)$removed);}\n"
if old not in t: raise SystemExit('R35 clear history pattern missing')
t=t.replace(old,new,1)

old="\tpublic static function progress($video_id,$seconds,$duration=0){if(!is_user_logged_in())return VWLB_Helpers::error('vwlb_login_required',__('Sign in to save progress.',VWLB_TEXT_DOMAIN),401);$video=VWLB_Repository::find('videos',$video_id);if(!$video||!VWLB_Security::can_view($video))return VWLB_Helpers::error('vwlb_not_found',__('Video not found.',VWLB_TEXT_DOMAIN),404);global $wpdb;$seconds=max(0,min((int)$seconds,max((int)$duration,(int)$video['duration_seconds'],DAY_IN_SECONDS)));$duration=max((int)$duration,(int)$video['duration_seconds']);$completed=$duration>0&&$seconds>=(int)floor($duration*.9);$table=VWLB_Helpers::table('playback_sessions');$existing=$wpdb->get_row($wpdb->prepare(\"SELECT id FROM $table WHERE user_id=%d AND object_type='video' AND object_id=%d\",get_current_user_id(),$video['id']),ARRAY_A);$data=array('progress_seconds'=>$seconds,'duration_seconds'=>$duration,'completed'=>$completed?1:0,'updated_at'=>VWLB_Helpers::now(),'expires_at'=>gmdate('Y-m-d H:i:s',time()+30*DAY_IN_SECONDS));if($existing)$wpdb->update($table,$data,array('id'=>$existing['id']));else{$data=array_merge($data,array('public_id'=>VWLB_Helpers::public_id('ses'),'user_id'=>get_current_user_id(),'object_type'=>'video','object_id'=>$video['id'],'created_at'=>VWLB_Helpers::now()));$wpdb->insert($table,$data);}return array('saved'=>true,'progress_seconds'=>$seconds,'completed'=>$completed);}\n"
new="\tpublic static function progress($video_id,$seconds,$duration=0){if(!is_user_logged_in())return VWLB_Helpers::error('vwlb_login_required',__('Sign in to save progress.',VWLB_TEXT_DOMAIN),401);$video=VWLB_Repository::find('videos',$video_id);if(!$video||!VWLB_Security::can_view($video))return VWLB_Helpers::error('vwlb_not_found',__('Video not found.',VWLB_TEXT_DOMAIN),404);global $wpdb;$verified=max(0,(int)$video['duration_seconds']);$reported=max(0,min(DAY_IN_SECONDS,(int)$duration));$duration=$verified?:$reported;$cap=$duration?:DAY_IN_SECONDS;$seconds=max(0,min((int)$seconds,$cap));$completed=$duration>0&&$seconds>=(int)floor($duration*.9);$table=VWLB_Helpers::table('playback_sessions');$existing=$wpdb->get_row($wpdb->prepare(\"SELECT id FROM $table WHERE user_id=%d AND object_type='video' AND object_id=%d\",get_current_user_id(),$video['id']),ARRAY_A);$data=array('progress_seconds'=>$seconds,'duration_seconds'=>$duration,'completed'=>$completed?1:0,'updated_at'=>VWLB_Helpers::now(),'expires_at'=>gmdate('Y-m-d H:i:s',time()+30*DAY_IN_SECONDS));if($existing){$saved=$wpdb->update($table,$data,array('id'=>$existing['id']));if(false===$saved)return VWLB_Helpers::error('vwlb_progress_save_failed',__('Watch progress could not be saved.',VWLB_TEXT_DOMAIN),500);}else{$data=array_merge($data,array('public_id'=>VWLB_Helpers::public_id('ses'),'user_id'=>get_current_user_id(),'object_type'=>'video','object_id'=>$video['id'],'created_at'=>VWLB_Helpers::now()));$saved=$wpdb->insert($table,$data);if(!$saved)return VWLB_Helpers::error('vwlb_progress_save_failed',__('Watch progress could not be saved.',VWLB_TEXT_DOMAIN),500);}return array('saved'=>true,'progress_seconds'=>$seconds,'completed'=>$completed);}\n"
if old not in t: raise SystemExit('R35 progress pattern missing')
t=t.replace(old,new,1)

old="\tpublic static function interact($video_id,$type){if(!is_user_logged_in())return VWLB_Helpers::error('vwlb_login_required',__('Sign in to react.',VWLB_TEXT_DOMAIN),401);$type=VWLB_Helpers::enum($type,array('like','dislike','save'),'');if(!$type)return VWLB_Helpers::error('vwlb_bad_interaction',__('Invalid interaction.',VWLB_TEXT_DOMAIN));$video=VWLB_Repository::find('videos',$video_id);if(!$video||!VWLB_Security::can_view($video))return VWLB_Helpers::error('vwlb_not_found',__('Video not found.',VWLB_TEXT_DOMAIN),404);return VWLB_DB::transaction(function()use($video,$type){global $wpdb;$table=VWLB_Helpers::table('interactions');$user=get_current_user_id();if(in_array($type,array('like','dislike'),true))$wpdb->delete($table,array('user_id'=>$user,'video_id'=>$video['id'],'interaction'=>$type==='like'?'dislike':'like'));$exists=$wpdb->get_var($wpdb->prepare(\"SELECT id FROM $table WHERE user_id=%d AND video_id=%d AND interaction=%s\",$user,$video['id'],$type));if($exists){$wpdb->delete($table,array('id'=>$exists));$active=false;}else{$wpdb->insert($table,array('user_id'=>$user,'video_id'=>$video['id'],'interaction'=>$type,'created_at'=>VWLB_Helpers::now(),'updated_at'=>VWLB_Helpers::now()));$active=true;}foreach(array('like','dislike') as $count_type){$count=(int)$wpdb->get_var($wpdb->prepare(\"SELECT COUNT(*) FROM $table WHERE video_id=%d AND interaction=%s\",$video['id'],$count_type));$wpdb->update(VWLB_Helpers::table('videos'),array($count_type.'_count'=>$count),array('id'=>$video['id']));}return array('interaction'=>$type,'active'=>$active);});}\n"
new="\tpublic static function interact($video_id,$type){if(!is_user_logged_in())return VWLB_Helpers::error('vwlb_login_required',__('Sign in to react.',VWLB_TEXT_DOMAIN),401);$type=VWLB_Helpers::enum($type,array('like','dislike','save'),'');if(!$type)return VWLB_Helpers::error('vwlb_bad_interaction',__('Invalid interaction.',VWLB_TEXT_DOMAIN));$video=VWLB_Repository::find('videos',$video_id);if(!$video||!VWLB_Security::can_view($video))return VWLB_Helpers::error('vwlb_not_found',__('Video not found.',VWLB_TEXT_DOMAIN),404);return VWLB_DB::transaction(function()use($video,$type){global $wpdb;$table=VWLB_Helpers::table('interactions');$user=get_current_user_id();$wpdb->get_var($wpdb->prepare('SELECT id FROM '.VWLB_Helpers::table('videos').' WHERE id=%d FOR UPDATE',$video['id']));if(in_array($type,array('like','dislike'),true)){$deleted=$wpdb->delete($table,array('user_id'=>$user,'video_id'=>$video['id'],'interaction'=>$type==='like'?'dislike':'like'));if(false===$deleted)return VWLB_Helpers::error('vwlb_interaction_save_failed',__('Interaction could not be saved.',VWLB_TEXT_DOMAIN),500);}$exists=$wpdb->get_var($wpdb->prepare(\"SELECT id FROM $table WHERE user_id=%d AND video_id=%d AND interaction=%s\",$user,$video['id'],$type));if($exists){$deleted=$wpdb->delete($table,array('id'=>$exists));if(false===$deleted)return VWLB_Helpers::error('vwlb_interaction_save_failed',__('Interaction could not be saved.',VWLB_TEXT_DOMAIN),500);$active=false;}else{$saved=$wpdb->insert($table,array('user_id'=>$user,'video_id'=>$video['id'],'interaction'=>$type,'created_at'=>VWLB_Helpers::now(),'updated_at'=>VWLB_Helpers::now()));if(!$saved)return VWLB_Helpers::error('vwlb_interaction_save_failed',__('Interaction could not be saved.',VWLB_TEXT_DOMAIN),500);$active=true;}foreach(array('like','dislike') as $count_type){$count=(int)$wpdb->get_var($wpdb->prepare(\"SELECT COUNT(*) FROM $table WHERE video_id=%d AND interaction=%s\",$video['id'],$count_type));$changed=$wpdb->update(VWLB_Helpers::table('videos'),array($count_type.'_count'=>$count),array('id'=>$video['id']));if(false===$changed)return VWLB_Helpers::error('vwlb_interaction_counter_failed',__('Interaction counters could not be reconciled.',VWLB_TEXT_DOMAIN),500);}return array('interaction'=>$type,'active'=>$active);});}\n"
if old not in t: raise SystemExit('R35 interact pattern missing')
t=t.replace(old,new,1)

p.write_text(t)
r=reg.read_text();marker="""# R35 — playback/progress/history/interactions fail closed on persistence errors and progress is bounded by verified duration.\nneed \"vwlb_playback_session_failed\" \"$P/includes/class-vwlb-videos.php\" r35-session\nneed \"vwlb_history_delete_failed\" \"$P/includes/class-vwlb-videos.php\" r35-history\nneed \"vwlb_progress_save_failed\" \"$P/includes/class-vwlb-videos.php\" r35-progress\nneed \"$verified?:$reported\" \"$P/includes/class-vwlb-videos.php\" r35-duration\nneed \"FOR UPDATE\" \"$P/includes/class-vwlb-videos.php\" r35-interaction-lock\nneed \"vwlb_interaction_counter_failed\" \"$P/includes/class-vwlb-videos.php\" r35-counter\n"""
if '# R35 —' not in r:r=r.replace("printf '%s\\n' 'fresh 40-review regression contracts PASS'\n",marker+"printf '%s\\n' 'fresh 40-review regression contracts PASS'\n")
reg.write_text(r)
